import type { EventContract } from './eventContract.types'
import { validatePayloadAgainstContract } from './eventValidation'

const companyProjectionKeys = ['companyList', 'companyDetail']
const branchProjectionKeys = ['branchList', 'branchSummary', 'companyDetail']
const partnerProjectionKeys = ['partnerList', 'currentOwnership', 'companyDetail']
const representativeProjectionKeys = ['representativeList', 'companyDetail']

export const allEventContracts: EventContract[] = [
  {
    eventType: 'company.created',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    description: 'Sirket taslak kaydi olusturuldu.',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.scope_attached',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    description: 'Sirket kullanici kapsamlarina baglandi.',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'company.updated',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    description: 'Sirket kart bilgileri guncellendi.',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.opened',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.liquidation_started',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.deregistered',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.title_changed',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.address_changed',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.public_registration_updated',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.capital_increased',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: ['companyDetail', 'companyList', 'partnerList', 'currentOwnership'],
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.capital_increase.completed',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company_capital_increase_transaction',
    projectionKeys: ['companyDetail', 'companyList', 'partnerList', 'currentOwnership'],
    auditRequired: true,
    aiContextRelevant: true,
    deprecated: true,
  },
  {
    eventType: 'company.capital_decrease_requested',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: ['companyDetail', 'companyList', 'partnerList', 'currentOwnership'],
    auditRequired: true,
  },
  {
    eventType: 'company.nace_changed',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.activity_subject_changed',
    version: '1.0',
    moduleKey: 'companies',
    domain: 'company',
    aggregateType: 'company',
    projectionKeys: companyProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.branch_opened',
    version: '1.0',
    moduleKey: 'branches',
    domain: 'branch',
    aggregateType: 'company_branch',
    description: 'Sirket subesi acildi.',
    projectionKeys: branchProjectionKeys,
    notificationType: 'branch_opened',
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.branch_closed',
    version: '1.0',
    moduleKey: 'branches',
    domain: 'branch',
    aggregateType: 'company_branch',
    description: 'Sirket subesi kapatildi.',
    projectionKeys: branchProjectionKeys,
    notificationType: 'branch_closed',
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'company.branch_documents_updated',
    version: '1.0',
    moduleKey: 'branches',
    domain: 'branch',
    aggregateType: 'company_branch',
    projectionKeys: ['branchList', 'branchSummary', 'companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'company.branch_updated',
    version: '1.0',
    moduleKey: 'branches',
    domain: 'branch',
    aggregateType: 'company_branch',
    projectionKeys: ['branchList', 'branchSummary', 'companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'partner.created',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'company_partner',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'partner.updated',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'company_partner',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'partner.deleted',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'company_partner',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'ownership.transaction_created',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    notificationType: 'ownership_transaction_created',
    auditRequired: true,
  },
  {
    eventType: 'ownership_transaction.created',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    notificationType: 'ownership_transaction_created',
    auditRequired: true,
    deprecated: true,
  },
  {
    eventType: 'ownership.transaction_approved',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'ownership.transaction_completed',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'ownership.transaction_cancelled',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'ownership.transaction_reversed',
    version: '1.0',
    moduleKey: 'partners',
    domain: 'ownership',
    aggregateType: 'ownership_transaction',
    projectionKeys: partnerProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'representative.created',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'company_representative',
    projectionKeys: representativeProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'representative.updated',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'company_representative',
    projectionKeys: representativeProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'representative.deleted',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'company_representative',
    projectionKeys: representativeProjectionKeys,
    auditRequired: true,
  },
  {
    eventType: 'representative.authority_started',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    notificationType: 'representative_authority_changed',
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'representative.authority_updated',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    notificationType: 'representative_authority_changed',
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'representative.authority.updated',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    notificationType: 'representative_authority_changed',
    auditRequired: true,
    aiContextRelevant: true,
    deprecated: true,
  },
  {
    eventType: 'representative.authority_changed',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    notificationType: 'representative_authority_changed',
    auditRequired: true,
    aiContextRelevant: true,
    deprecated: true,
  },
  {
    eventType: 'representative.authority_suspended',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'representative.authority_terminated',
    version: '1.0',
    moduleKey: 'representatives',
    domain: 'representative',
    aggregateType: 'representative_authority_transaction',
    projectionKeys: representativeProjectionKeys,
    auditRequired: true,
    aiContextRelevant: true,
  },
  {
    eventType: 'organization.unit_created',
    version: '1.0',
    moduleKey: 'organization',
    domain: 'organization',
    aggregateType: 'organization_unit',
    projectionKeys: ['companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'organization.unit_updated',
    version: '1.0',
    moduleKey: 'organization',
    domain: 'organization',
    aggregateType: 'organization_unit',
    projectionKeys: ['companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'organization.unit_closed',
    version: '1.0',
    moduleKey: 'organization',
    domain: 'organization',
    aggregateType: 'organization_unit',
    projectionKeys: ['companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'organization.position_updated',
    version: '1.0',
    moduleKey: 'organization',
    domain: 'organization',
    aggregateType: 'position',
    projectionKeys: ['companyDetail'],
    auditRequired: true,
  },
  {
    eventType: 'facility.created',
    version: '1.0',
    moduleKey: 'facilities',
    domain: 'facility',
    aggregateType: 'company_facility',
    projectionKeys: ['companyDetail', 'branchList'],
    auditRequired: true,
  },
  {
    eventType: 'facility.updated',
    version: '1.0',
    moduleKey: 'facilities',
    domain: 'facility',
    aggregateType: 'company_facility',
    projectionKeys: ['companyDetail', 'branchList'],
    auditRequired: true,
  },
  {
    eventType: 'facility.linked_to_branch',
    version: '1.0',
    moduleKey: 'facilities',
    domain: 'facility',
    aggregateType: 'company_facility',
    projectionKeys: ['companyDetail', 'branchList', 'branchSummary'],
    auditRequired: true,
  },
  {
    eventType: 'facility.deactivated',
    version: '1.0',
    moduleKey: 'facilities',
    domain: 'facility',
    aggregateType: 'company_facility',
    projectionKeys: ['companyDetail', 'branchList'],
    auditRequired: true,
  },
  ...[
    'process.started',
    'process.step_completed',
    'process.task_created',
    'process.approval_requested',
    'process.approved',
    'process.rejected',
    'process.completed',
    'process.cancelled',
    'process.failed',
  ].map<EventContract>(eventType => ({
    eventType,
    version: '1.0',
    moduleKey: 'process',
    domain: 'process',
    aggregateType: eventType === 'process.task_created' ? 'process_task' : 'process_instance',
    notificationType: eventType === 'process.task_created' ? 'process_task_created' : undefined,
    auditRequired: eventType !== 'process.step_completed',
  })),
  {
    eventType: 'projection.refresh_requested',
    version: '1.0',
    moduleKey: 'system',
    domain: 'system',
    aggregateType: 'system',
    projectionKeys: [],
  },
  {
    eventType: 'notification.created',
    version: '1.0',
    moduleKey: 'system',
    domain: 'notification',
    aggregateType: 'system',
  },
  {
    eventType: 'audit.recorded',
    version: '1.0',
    moduleKey: 'system',
    domain: 'audit',
    aggregateType: 'system',
  },
  {
    eventType: 'ai_context.refresh_requested',
    version: '1.0',
    moduleKey: 'system',
    domain: 'ai',
    aggregateType: 'system',
    aiContextRelevant: true,
  },
]

const contractsByType = new Map(allEventContracts.map(contract => [contract.eventType, contract]))

export function getEventContract(eventType: string) {
  return contractsByType.get(eventType) || null
}

export function listEventContracts() {
  return [...allEventContracts]
}

export function listEventsByModule(moduleKey: string) {
  return allEventContracts.filter(contract => contract.moduleKey === moduleKey)
}

export function listEventsByProjection(projectionKey: string) {
  return allEventContracts.filter(contract => (contract.projectionKeys || []).includes(projectionKey))
}

export function validateEventPayload(eventType: string, payload: Record<string, any> | null | undefined) {
  return validatePayloadAgainstContract(getEventContract(eventType), eventType, payload)
}

export function getEventVersion(eventType: string) {
  return getEventContract(eventType)?.version || '1.0'
}

export function isEventDeprecated(eventType: string) {
  return !!getEventContract(eventType)?.deprecated
}
