import type { DashboardWidgetConfig } from '@/components/dashboard/dashboard.types'

export const employeesDashboardLayout: DashboardWidgetConfig[] = [
  {
    id: 'employees-total',
    type: 'kpi',
    title: 'Toplam Çalışan',
    module: 'employees',
    size: { w: 4, h: 2 },
    dataSource: 'dashboard.employees.summary',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-gender',
    type: 'stackedBar',
    title: 'Cinsiyet Dağılımı',
    module: 'employees',
    size: { w: 4, h: 1 },
    dataSource: 'dashboard.employees.gender',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-education',
    type: 'stackedBar',
    title: 'Eğitim Dağılımı',
    module: 'employees',
    size: { w: 4, h: 1 },
    dataSource: 'dashboard.employees.education',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-work-type',
    type: 'stackedBar',
    title: 'Çalışma Tipi',
    module: 'employees',
    size: { w: 4, h: 1 },
    dataSource: 'dashboard.employees.workType',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-department',
    type: 'stackedBar',
    title: 'Departman Dağılımı',
    module: 'employees',
    size: { w: 4, h: 1 },
    dataSource: 'dashboard.employees.department',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-age-group',
    type: 'stackedBar',
    title: 'Yaş Grubu',
    module: 'employees',
    size: { w: 4, h: 1 },
    dataSource: 'dashboard.employees.ageGroup',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-hire-trend',
    type: 'trend',
    title: 'İşe Giriş Trendi',
    module: 'employees',
    size: { w: 4, h: 2 },
    dataSource: 'dashboard.employees.hireTrend',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-department-detail',
    type: 'distribution',
    title: 'Departman Detayı',
    module: 'employees',
    size: { w: 4, h: 2 },
    dataSource: 'dashboard.employees.departmentDetail',
    permissions: ['employees.view'],
  },
  {
    id: 'employees-actions',
    type: 'actionList',
    title: 'Yaklaşan Aksiyonlar',
    module: 'employees',
    size: { w: 4, h: 2 },
    dataSource: 'dashboard.employees.actions',
    permissions: ['employees.view'],
  },
]
