from __future__ import annotations

from app.projections.types import ProjectionDefinition

PROJECTIONS: dict[str, ProjectionDefinition] = {
    "companyList": ProjectionDefinition(
        key="companyList",
        name="Company List",
        version="1.0",
        source_name="companies",
        source_type="table",
        source_tables=["companies"],
        fields=[
            "id",
            "organization_id",
            "short_name",
            "trade_name",
            "tax_number",
            "tax_office",
            "company_type",
            "city",
            "district",
            "address",
            "phone",
            "email",
            "record_status",
            "company_status",
            "committed_capital_amount",
            "paid_capital_amount",
            "logo_url",
            "country",
            "website",
            "created_at",
            "updated_at",
            "version",
            "is_deleted",
        ],
        searchable_fields=["trade_name", "short_name", "tax_number", "tax_office", "city"],
        sortable_fields=[
            "trade_name",
            "created_at",
            "updated_at",
            "record_status",
            "company_status",
        ],
        status_field="record_status",
        performance_budget_ms=500,
        default_page_size=50,
        max_page_size=100,
        requires_index_hint="companies(tenant_id, is_deleted, record_status, updated_at)",
    ),
    "companyDetail": ProjectionDefinition(
        key="companyDetail",
        name="Company Detail",
        version="1.0",
        source_name="companies",
        source_type="table",
        source_tables=["companies"],
        company_scoped=True,
        performance_budget_ms=700,
    ),
    "branchList": ProjectionDefinition(
        key="branchList",
        name="Branch List",
        version="1.0",
        source_name="v_company_branch_list",
        source_type="view",
        source_tables=["company_branches"],
        searchable_fields=[
            "branch_name",
            "branch_short_name",
            "company_name",
            "city",
            "district",
            "address",
            "trade_registry_number",
            "tax_office",
        ],
        sortable_fields=["branch_name", "created_at", "updated_at", "record_status", "status"],
        status_field="record_status",
        company_scoped=True,
        fallback_strategy="company_branches_table",
        performance_budget_ms=500,
        default_page_size=50,
        max_page_size=100,
        requires_index_hint="company_branches(tenant_id, company_id, record_status, updated_at)",
    ),
    "branchSummary": ProjectionDefinition(
        key="branchSummary",
        name="Branch Summary",
        version="1.0",
        source_name="company_branches",
        source_type="table",
        source_tables=["company_branches"],
        company_scoped=True,
        performance_budget_ms=500,
        max_page_size=100,
    ),
    "partnerList": ProjectionDefinition(
        key="partnerList",
        name="Partner List",
        version="1.0",
        source_name="company_partners",
        source_type="table",
        source_tables=["company_partners"],
        searchable_fields=["display_name", "trade_name", "first_name", "last_name"],
        sortable_fields=["display_name", "created_at", "updated_at", "record_status", "status"],
        status_field="record_status",
        company_scoped=True,
        fallback_strategy="hydrate_current_ownership_if_available",
        performance_budget_ms=500,
        default_page_size=50,
        max_page_size=100,
        requires_index_hint="company_partners(tenant_id, company_id, record_status, updated_at)",
    ),
    "representativeList": ProjectionDefinition(
        key="representativeList",
        name="Representative List",
        version="1.0",
        source_name="company_representatives",
        source_type="table",
        source_tables=["company_representatives"],
        searchable_fields=["display_name", "full_name", "job_title"],
        sortable_fields=["display_name", "created_at", "updated_at", "record_status", "status"],
        status_field="record_status",
        company_scoped=True,
        fallback_strategy="hydrate_current_authority_if_available",
        performance_budget_ms=500,
        default_page_size=50,
        max_page_size=100,
        requires_index_hint=(
            "company_representatives(tenant_id, company_id, record_status, updated_at)"
        ),
    ),
    "currentOwnership": ProjectionDefinition(
        key="currentOwnership",
        name="Current Ownership",
        version="1.0",
        source_name="v_current_ownership",
        source_type="view",
        source_tables=["company_partners", "ownership_transactions"],
        company_scoped=True,
        fallback_strategy="ownership_transaction_aggregation",
        performance_budget_ms=500,
        max_page_size=100,
        requires_index_hint="ownership_transactions(tenant_id, company_id, effective_date)",
    ),
    "currentRepresentativeAuthorities": ProjectionDefinition(
        key="currentRepresentativeAuthorities",
        name="Current Representative Authorities",
        version="1.0",
        source_name="v_current_representative_authorities",
        source_type="view",
        source_tables=["company_representatives", "company_representative_authority_transactions"],
        company_scoped=True,
        fallback_strategy="company_representative_authority_transactions_latest",
        performance_budget_ms=500,
        max_page_size=100,
        requires_index_hint=(
            "company_representative_authority_transactions(tenant_id, company_id, effective_date)"
        ),
    ),
}


def get_projection_definition(key: str) -> ProjectionDefinition | None:
    return PROJECTIONS.get(key)


def list_projection_definitions() -> list[ProjectionDefinition]:
    return list(PROJECTIONS.values())
