import type { ModuleContract } from '../moduleContract.types'

export const accountingModule: ModuleContract = {
  key: 'accounting',
  name: 'Muhasebe',
  description: 'Cari kart, banka hareketi, e-belge ve mutabakat operasyonlari.',
  domain: 'finance',
  category: 'operations',
  version: '2026-05-28.1',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: true,
  setupRequired: true,
  dependencies: [{ moduleKey: 'companies', required: true, reason: 'Cari hareketler sirket kapsaminda tutulur.' }],
  entities: [
    { key: 'accounting_cari_account', tableName: 'accounting_cari_accounts', displayName: 'Cari kart', draftSupported: true },
    { key: 'accounting_cari_transaction', tableName: 'accounting_cari_transactions', displayName: 'Cari hareket', draftSupported: true },
    { key: 'accounting_bank_account', tableName: 'accounting_bank_accounts', displayName: 'Banka hesabi', draftSupported: true },
    { key: 'accounting_bank_transaction', tableName: 'accounting_bank_transactions', displayName: 'Banka hareketi', draftSupported: true },
    { key: 'accounting_card_transaction', tableName: 'accounting_card_transactions', displayName: 'Kredi karti hareketi', draftSupported: true },
    { key: 'accounting_e_document', tableName: 'accounting_e_documents', displayName: 'e-Fatura/e-Arsiv', draftSupported: true },
    { key: 'accounting_reconciliation_link', tableName: 'accounting_reconciliation_links', displayName: 'Mutabakat baglantisi', draftSupported: false },
    { key: 'accounting_capital_reconciliation', tableName: 'accounting_capital_reconciliation', displayName: 'Sermaye mutabakati', draftSupported: false },
  ],
  routes: [
    { path: '/app/muhasebe', type: 'page', permission: 'accounting.view' },
    { path: '/app/muhasebe/cari-kartlar', type: 'page', permission: 'accounting.view' },
    { path: '/app/muhasebe/cari-hareketler', type: 'page', permission: 'accounting.view' },
    { path: '/app/muhasebe/banka-hesaplari', type: 'page', permission: 'accounting.bankAccountsView' },
    { path: '/app/muhasebe/banka-hareketleri', type: 'page', permission: 'accounting.bankTransactionsView' },
    { path: '/app/muhasebe/e-fatura-e-arsiv', type: 'page', permission: 'accounting.eDocumentsView' },
    { path: '/app/muhasebe/mutabakat', type: 'page', permission: 'accounting.reconciliationView' },
    { path: '/app/muhasebe/sermaye-mutabakati', type: 'page', permission: 'accounting.capitalReconciliationView' },
  ],
  menus: [
    { label: 'Muhasebe', path: '/app/muhasebe', icon: 'CreditCard', order: 100, permission: 'accounting.view' },
    { label: 'Cari Kartlar', path: '/app/muhasebe/cari-kartlar', icon: 'WalletCards', parent: 'Muhasebe', order: 101, permission: 'accounting.view', featureFlag: 'accounting.cariAccounts' },
    { label: 'Cari Hareketler', path: '/app/muhasebe/cari-hareketler', icon: 'FileText', parent: 'Muhasebe', order: 102, permission: 'accounting.view', featureFlag: 'accounting.cariTransactions' },
    { label: 'Banka Hesaplari', path: '/app/muhasebe/banka-hesaplari', icon: 'Landmark', parent: 'Muhasebe', order: 103, permission: 'accounting.bankAccountsView', featureFlag: 'accounting.bankAccounts' },
    { label: 'Banka Hareketleri', path: '/app/muhasebe/banka-hareketleri', icon: 'ArrowLeftRight', parent: 'Muhasebe', order: 104, permission: 'accounting.bankTransactionsView', featureFlag: 'accounting.bankTransactions' },
    { label: 'e-Fatura / e-Arsiv', path: '/app/muhasebe/e-fatura-e-arsiv', icon: 'ReceiptText', parent: 'Muhasebe', order: 105, permission: 'accounting.eDocumentsView', featureFlag: 'accounting.eDocuments' },
    { label: 'Mutabakat', path: '/app/muhasebe/mutabakat', icon: 'GitCompareArrows', parent: 'Muhasebe', order: 106, permission: 'accounting.reconciliationView', featureFlag: 'accounting.reconciliation' },
    { label: 'Sermaye Mutabakati', path: '/app/muhasebe/sermaye-mutabakati', icon: 'Scale', parent: 'Muhasebe', order: 107, permission: 'accounting.capitalReconciliationView', featureFlag: 'accounting.capitalReconciliation' },
  ],
  permissions: [
    { key: 'accounting.view', label: 'Muhasebe goruntuleme' },
    { key: 'accounting.edit', label: 'Muhasebe duzenleme' },
    { key: 'accounting.transactionCreate', label: 'Cari hareket olusturma', fallback: ['accounting.edit'] },
    { key: 'accounting.transactionApprove', label: 'Cari hareket onaylama', fallback: ['accounting.edit'] },
    { key: 'accounting.reconcile', label: 'Mutabakat yapma', fallback: ['accounting.edit'] },
    { key: 'accounting.bankAccountsView', label: 'Banka hesaplari goruntuleme', fallback: ['accounting.view'] },
    { key: 'accounting.bankAccountsEdit', label: 'Banka hesaplari duzenleme', fallback: ['accounting.edit'] },
    { key: 'accounting.bankTransactionsView', label: 'Banka/kart hareketleri goruntuleme', fallback: ['accounting.view'] },
    { key: 'accounting.bankTransactionsImport', label: 'Banka/kart hareketleri import', fallback: ['accounting.edit'] },
    { key: 'accounting.eDocumentsView', label: 'e-Belge goruntuleme', fallback: ['accounting.view'] },
    { key: 'accounting.eDocumentsImport', label: 'e-Belge import', fallback: ['accounting.edit'] },
    { key: 'accounting.reconciliationView', label: 'Mutabakat goruntuleme', fallback: ['accounting.view'] },
    { key: 'accounting.reconciliationManage', label: 'Mutabakat yonetimi', fallback: ['accounting.reconcile'] },
    { key: 'accounting.capitalReconciliationView', label: 'Sermaye mutabakati goruntuleme', fallback: ['accounting.view'] },
    { key: 'accounting.capitalReconciliationManage', label: 'Sermaye mutabakati yonetimi', fallback: ['accounting.reconciliationManage'] },
    { key: 'accounting.export', label: 'Muhasebe disari aktarma', fallback: ['accounting.view'] },
  ],
  actions: [
    { key: 'create_cari_account', label: 'Cari kart olustur', actionType: 'create_draft', targetPage: '/app/muhasebe/cari-kartlar', permission: 'accounting.edit' },
    { key: 'create_cari_transaction', label: 'Cari hareket olustur', actionType: 'create_draft', targetPage: '/app/muhasebe/cari-hareketler', permission: 'accounting.transactionCreate' },
    { key: 'reconcile_transaction', label: 'Cari hareket mutabakati', actionType: 'operation', targetPage: '/app/muhasebe/cari-hareketler', permission: 'accounting.reconcile' },
    { key: 'cancel_transaction', label: 'Cari hareket iptali', actionType: 'operation', targetPage: '/app/muhasebe/cari-hareketler', permission: 'accounting.edit' },
    { key: 'import_bank_statement', label: 'Banka ekstresi aktar', actionType: 'operation', targetPage: '/app/muhasebe/banka-hareketleri', permission: 'accounting.bankTransactionsImport' },
    { key: 'import_e_document', label: 'e-Fatura/e-Arsiv aktar', actionType: 'operation', targetPage: '/app/muhasebe/e-fatura-e-arsiv', permission: 'accounting.eDocumentsImport' },
    { key: 'open_reconciliation', label: 'Mutabakat onerilerini incele', actionType: 'operation', targetPage: '/app/muhasebe/mutabakat', permission: 'accounting.reconciliationView' },
    { key: 'open_capital_reconciliation', label: 'Sermaye odeme mutabakati', actionType: 'operation', targetPage: '/app/muhasebe/sermaye-mutabakati', permission: 'accounting.capitalReconciliationView' },
  ],
  projections: [
    { key: 'cari_accounts', projectionKey: 'accounting_cari_accounts', required: false },
    { key: 'cari_transactions', projectionKey: 'accounting_cari_transactions', required: false },
    { key: 'bank_accounts', projectionKey: 'accounting_bank_accounts', required: false },
    { key: 'bank_transactions', projectionKey: 'accounting_bank_transactions', required: false },
    { key: 'e_documents', projectionKey: 'accounting_e_documents', required: false },
  ],
  featureFlags: [
    { key: 'accounting.enabled', label: 'Muhasebe aktif', defaultEnabled: true },
    { key: 'accounting.cariAccounts', label: 'Cari Kartlar', defaultEnabled: true },
    { key: 'accounting.cariTransactions', label: 'Cari Hareketler', defaultEnabled: true },
    { key: 'accounting.bankAccounts', label: 'Banka Hesaplari', defaultEnabled: true },
    { key: 'accounting.bankTransactions', label: 'Banka Hareketleri', defaultEnabled: true },
    { key: 'accounting.cardTransactions', label: 'Kredi Karti Hareketleri', defaultEnabled: true },
    { key: 'accounting.eDocuments', label: 'e-Fatura / e-Arsiv', defaultEnabled: true },
    { key: 'accounting.reconciliation', label: 'Mutabakat', defaultEnabled: true },
    { key: 'accounting.autoMatching', label: 'Otomatik eslestirme onerileri', defaultEnabled: true },
    { key: 'accounting.capitalReconciliation', label: 'Sermaye mutabakati', defaultEnabled: true },
    { key: 'accounting.bankImport', label: 'Banka ekstresi import', defaultEnabled: true },
    { key: 'accounting.eDocumentImport', label: 'e-Belge import', defaultEnabled: true },
  ],
  events: [],
}
