import { PERMISSIONS } from '@/packages/shared/src'
import type { ModuleContract } from '../moduleContract.types'

export const adminConsoleModule: ModuleContract = {
  key: 'adminConsole',
  name: 'Admin Console',
  description: 'Calisma alani ayarlari, moduller, feature flags, saglik, entegrasyon ve outbox yonetimi.',
  domain: 'platform',
  category: 'platform',
  version: '2026-05-29.24',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: false,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'security', required: true, reason: 'Admin Console permission ve system.admin kontrolleriyle korunur.' },
    { moduleKey: 'audit', required: false, reason: 'Riskli ayar degisiklikleri ve admin aksiyonlari denetim izine yazilir.' },
    { moduleKey: 'outbox', required: false, reason: 'Admin eventleri ve retry islemleri outbox durumuyla izlenir.' },
  ],
  entities: [
    { key: 'workspace_settings', tableName: 'workspace_settings', displayName: 'Calisma alani ayari' },
    { key: 'admin_settings', tableName: 'admin_settings', displayName: 'Admin ayari' },
    { key: 'feature_flag_override', tableName: 'feature_flag_overrides', displayName: 'Feature flag override' },
    { key: 'integration_status', tableName: 'integration_status_cache', displayName: 'Entegrasyon durumu' },
    { key: 'worker_heartbeat', tableName: 'worker_heartbeats', displayName: 'Worker heartbeat' },
  ],
  routes: [
    { path: '/app/sistem', type: 'page', permission: PERMISSIONS.adminConsole.view, fallbackPermission: 'settings.view' },
    { path: '/app/sistem/genel', type: 'page', permission: PERMISSIONS.adminConsole.manage, fallbackPermission: 'settings.edit' },
    { path: '/app/sistem/moduller', type: 'page', permission: PERMISSIONS.adminConsole.manage, fallbackPermission: 'settings.modulesManage' },
    { path: '/app/sistem/ozellikler', type: 'page', permission: PERMISSIONS.adminConsole.manage, fallbackPermission: 'settings.edit' },
    { path: '/app/sistem/saglik', type: 'page', permission: PERMISSIONS.adminConsole.view, fallbackPermission: 'settings.view' },
    { path: '/app/sistem/outbox', type: 'page', permission: PERMISSIONS.adminConsole.outboxAdmin, fallbackPermission: 'outbox.dispatch' },
    { path: '/app/sistem/entegrasyonlar', type: 'page', permission: PERMISSIONS.adminConsole.manage, fallbackPermission: 'settings.edit' },
    { path: '/app/sistem/teknik', type: 'page', permission: PERMISSIONS.adminConsole.technical, fallbackPermission: 'system.admin' },
    { path: '/api/admin/workspace-settings', type: 'api', permission: PERMISSIONS.adminConsole.manage },
    { path: '/api/admin/modules', type: 'api', permission: PERMISSIONS.adminConsole.manage },
    { path: '/api/admin/features', type: 'api', permission: PERMISSIONS.adminConsole.manage },
    { path: '/api/admin/health', type: 'api', permission: PERMISSIONS.adminConsole.view },
    { path: '/api/admin/outbox', type: 'api', permission: PERMISSIONS.adminConsole.outboxAdmin },
    { path: '/api/admin/integrations', type: 'api', permission: PERMISSIONS.adminConsole.manage },
  ],
  menus: [
    { label: 'Admin Console', path: '/app/sistem', icon: 'Settings', order: 900, permission: PERMISSIONS.adminConsole.view, featureFlag: 'adminConsole.enabled' },
    { label: 'Genel Ayarlar', path: '/app/sistem/genel', icon: 'SlidersHorizontal', order: 901, parent: 'settings', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.workspaceSettings' },
    { label: 'Moduller', path: '/app/sistem/moduller', icon: 'Wrench', order: 902, parent: 'settings', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.enabled' },
    { label: 'Ozellikler', path: '/app/sistem/ozellikler', icon: 'Flag', order: 903, parent: 'settings', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.enabled' },
    { label: 'Sistem Sagligi', path: '/app/sistem/saglik', icon: 'Activity', order: 904, parent: 'settings', permission: PERMISSIONS.adminConsole.view, featureFlag: 'adminConsole.healthDashboard' },
    { label: 'Outbox', path: '/app/sistem/outbox', icon: 'Send', order: 905, parent: 'settings', permission: PERMISSIONS.adminConsole.outboxAdmin, featureFlag: 'adminConsole.outboxAdmin' },
    { label: 'Entegrasyonlar', path: '/app/sistem/entegrasyonlar', icon: 'Database', order: 906, parent: 'settings', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.enabled' },
    { label: 'Teknik', path: '/app/sistem/teknik', icon: 'KeyRound', order: 907, parent: 'settings', permission: PERMISSIONS.adminConsole.technical, featureFlag: 'adminConsole.technicalPage' },
  ],
  permissions: [
    { key: PERMISSIONS.adminConsole.view, label: 'Admin Console goruntule' },
    { key: PERMISSIONS.adminConsole.manage, label: 'Admin Console ayarlarini yonet' },
    { key: PERMISSIONS.adminConsole.outboxAdmin, label: 'Outbox admin islemleri' },
    { key: PERMISSIONS.adminConsole.technical, label: 'Teknik admin bilgilerini goruntule' },
  ],
  actions: [
    { key: 'admin_console_open', label: 'Admin Console ac', actionType: 'navigate', targetPage: '/app/sistem', permission: PERMISSIONS.adminConsole.view, featureFlag: 'adminConsole.enabled' },
    { key: 'workspace_settings_update', label: 'Calisma alani ayarlarini guncelle', actionType: 'edit', targetPage: '/app/sistem/genel', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.workspaceSettings' },
    { key: 'feature_flag_toggle', label: 'Feature flag ac/kapat', actionType: 'operation', targetPage: '/app/sistem/ozellikler', permission: PERMISSIONS.adminConsole.manage, featureFlag: 'adminConsole.enabled' },
    { key: 'outbox_retry_failed', label: 'Failed outbox event tekrar dene', actionType: 'operation', targetPage: '/app/sistem/outbox', permission: PERMISSIONS.adminConsole.outboxAdmin, featureFlag: 'adminConsole.outboxAdmin' },
    { key: 'admin_health_open', label: 'Sistem sagligini incele', actionType: 'view', targetPage: '/app/sistem/saglik', permission: PERMISSIONS.adminConsole.view, featureFlag: 'adminConsole.healthDashboard' },
  ],
  projections: [],
  events: [
    { eventType: 'admin.workspace_settings_updated', version: '1', aggregateType: 'admin_console' },
    { eventType: 'admin.feature_flag_updated', version: '1', aggregateType: 'admin_console' },
    { eventType: 'admin.module_activation_updated', version: '1', aggregateType: 'admin_console' },
    { eventType: 'admin.outbox_retried', version: '1', aggregateType: 'admin_console' },
  ],
  featureFlags: [
    { key: 'adminConsole.enabled', label: 'Admin Console', defaultEnabled: true },
    { key: 'adminConsole.workspaceSettings', label: 'Calisma alani ayarlari', defaultEnabled: true },
    { key: 'adminConsole.healthDashboard', label: 'Saglik dashboardu', defaultEnabled: true },
    { key: 'adminConsole.outboxAdmin', label: 'Outbox admin', defaultEnabled: true },
    { key: 'adminConsole.technicalPage', label: 'Teknik admin sayfasi', defaultEnabled: true },
  ],
}
