import { PERMISSIONS } from '@/packages/shared/src'
import type { ModuleContract } from '../moduleContract.types'

export const afterSalesModule: ModuleContract = {
  key: 'after_sales',
  name: 'Satis Sonrasi Hizmetler',
  domain: 'service',
  category: 'operations',
  version: '2026-05-29.23',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: true,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Servis kayitlari sirket ve musteri kapsamiyla calisir.' },
    { moduleKey: 'product_services', required: true, reason: 'Kurulu urunler katalogdaki servis verilebilir urunlerden secilir.' },
    { moduleKey: 'project_management', required: false, reason: 'Servis gorevleri ve takip isleri Action Center entegrasyonunu guclendirir.' },
    { moduleKey: 'hr', required: false, reason: 'Teknisyen atamasi calisan kayitlariyla zenginlesir.' },
    { moduleKey: 'facilities', required: false, reason: 'Kurulu urun lokasyon baglantilari icin onerilir.' },
  ],
  entities: [
    { key: 'after_sales_installed_asset', tableName: 'after_sales_installed_assets', displayName: 'Kurulu Urun', lifecycle: true, draftSupported: false },
    { key: 'after_sales_service_request', tableName: 'after_sales_service_requests', displayName: 'Servis Talebi', lifecycle: true, draftSupported: true },
    { key: 'after_sales_service_record', tableName: 'after_sales_service_records', displayName: 'Servis Kaydi', lifecycle: true, draftSupported: true },
    { key: 'after_sales_maintenance_plan', tableName: 'after_sales_maintenance_plans', displayName: 'Bakim Plani', lifecycle: true, draftSupported: false },
    { key: 'after_sales_maintenance_due_item', tableName: 'after_sales_maintenance_due_items', displayName: 'Bakim Takvimi', lifecycle: true, draftSupported: false },
    { key: 'after_sales_field_assignment', tableName: 'after_sales_field_assignments', displayName: 'Saha Servis Gorevi', lifecycle: true, draftSupported: false },
    { key: 'after_sales_checklist_template', tableName: 'after_sales_checklist_templates', displayName: 'Servis Checklist Sablonu', lifecycle: true, draftSupported: false },
  ],
  routes: [
    { path: '/app/satis-sonrasi', type: 'page', permission: PERMISSIONS.afterSales.view },
    { path: '/app/satis-sonrasi/kurulu-urunler', type: 'page', permission: PERMISSIONS.afterSales.view },
    { path: '/app/satis-sonrasi/servis-talepleri', type: 'page', permission: PERMISSIONS.afterSales.view },
    { path: '/app/satis-sonrasi/servis-kayitlari', type: 'page', permission: PERMISSIONS.afterSales.view },
    { path: '/app/satis-sonrasi/bakim-planlari', type: 'page', permission: PERMISSIONS.afterSales.maintenanceView },
    { path: '/app/satis-sonrasi/bakimi-gelenler', type: 'page', permission: PERMISSIONS.afterSales.maintenanceView },
    { path: '/app/satis-sonrasi/saha-gorevleri', type: 'page', permission: PERMISSIONS.afterSales.fieldServiceView },
    { path: '/app/satis-sonrasi/checklistler', type: 'page', permission: PERMISSIONS.afterSales.fieldServiceView },
  ],
  menus: [{ label: 'Satis Sonrasi Hizmetler', path: '/app/satis-sonrasi', icon: 'Headphones', order: 150, permission: PERMISSIONS.afterSales.view }],
  permissions: [
    { key: PERMISSIONS.afterSales.view, label: 'Satis sonrasi goruntuleme' },
    { key: PERMISSIONS.afterSales.edit, label: 'Satis sonrasi kayit duzenleme' },
    { key: PERMISSIONS.afterSales.assetCreate, label: 'Kurulu urun olusturma' },
    { key: PERMISSIONS.afterSales.requestCreate, label: 'Servis talebi olusturma' },
    { key: PERMISSIONS.afterSales.requestAssign, label: 'Servis talebi atama' },
    { key: PERMISSIONS.afterSales.serviceRecordCreate, label: 'Servis kaydi olusturma' },
    { key: PERMISSIONS.afterSales.serviceComplete, label: 'Servis kaydi tamamlama' },
    { key: PERMISSIONS.afterSales.maintenanceView, label: 'Bakim planlarini goruntuleme' },
    { key: PERMISSIONS.afterSales.maintenanceManage, label: 'Bakim planlarini yonetme' },
    { key: PERMISSIONS.afterSales.fieldServiceView, label: 'Saha servis gorevlerini goruntuleme' },
    { key: PERMISSIONS.afterSales.fieldServiceAssign, label: 'Saha servis teknisyeni atama' },
    { key: PERMISSIONS.afterSales.fieldServiceExecute, label: 'Saha servis uygulama' },
    { key: PERMISSIONS.afterSales.checklistManage, label: 'Checklist yonetimi' },
    { key: PERMISSIONS.afterSales.serviceReportView, label: 'Servis raporu goruntuleme' },
    { key: PERMISSIONS.afterSales.serviceReportGenerate, label: 'Servis raporu uretme' },
    { key: PERMISSIONS.afterSales.warrantyOverride, label: 'Garanti override' },
    { key: PERMISSIONS.afterSales.manage, label: 'Satis sonrasi yonetim' },
  ],
  actions: [
    { key: 'create_installed_asset', label: 'Kurulu urun olustur', actionType: 'operation', targetPage: '/app/satis-sonrasi/kurulu-urunler', permission: PERMISSIONS.afterSales.assetCreate },
    { key: 'create_service_request', label: 'Servis talebi olustur', actionType: 'operation', targetPage: '/app/satis-sonrasi/servis-talepleri', permission: PERMISSIONS.afterSales.requestCreate },
    { key: 'assign_service_request', label: 'Servis talebi ata', actionType: 'operation', targetPage: '/app/satis-sonrasi/servis-talepleri', permission: PERMISSIONS.afterSales.requestAssign },
    { key: 'create_service_record', label: 'Servis kaydi olustur', actionType: 'operation', targetPage: '/app/satis-sonrasi/servis-kayitlari', permission: PERMISSIONS.afterSales.serviceRecordCreate },
    { key: 'complete_service_record', label: 'Servis kaydini tamamla', actionType: 'operation', targetPage: '/app/satis-sonrasi/servis-kayitlari', permission: PERMISSIONS.afterSales.serviceComplete },
    { key: 'create_followup_task', label: 'Takip gorevi olustur', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/gorevler', permission: PERMISSIONS.afterSales.serviceComplete },
    { key: 'create_maintenance_plan', label: 'Bakim plani olustur', actionType: 'operation', targetPage: '/app/satis-sonrasi/bakim-planlari', permission: PERMISSIONS.afterSales.maintenanceManage },
    { key: 'assign_field_technician', label: 'Teknisyen ata', actionType: 'operation', targetPage: '/app/satis-sonrasi/saha-gorevleri', permission: PERMISSIONS.afterSales.fieldServiceAssign },
    { key: 'open_mobile_service', label: 'Mobil servisi ac', actionType: 'operation', targetPage: '/app/satis-sonrasi/saha-gorevleri', permission: PERMISSIONS.afterSales.fieldServiceExecute },
  ],
  featureFlags: [
    { key: 'afterSales.enabled', label: 'Satis sonrasi modulunu etkinlestir', defaultEnabled: true },
    { key: 'afterSales.installedAssets', label: 'Kurulu urunleri etkinlestir', defaultEnabled: true },
    { key: 'afterSales.serviceRequests', label: 'Servis taleplerini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.serviceRecords', label: 'Servis kayitlarini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.maintenanceDue', label: 'Bakimi gelenleri etkinlestir', defaultEnabled: true },
    { key: 'afterSales.maintenancePlanning', label: 'Bakim planlamayi etkinlestir', defaultEnabled: true },
    { key: 'afterSales.fieldService', label: 'Saha servisi etkinlestir', defaultEnabled: true },
    { key: 'afterSales.mobileServiceFlow', label: 'Mobil servis akisini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.serviceChecklist', label: 'Servis checklistlerini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.partsUsed', label: 'Kullanilan parca girisini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.projectTaskIntegration', label: 'Project task entegrasyonunu etkinlestir', defaultEnabled: true },
    { key: 'afterSales.customerSignature', label: 'Musteri imzasi alanini etkinlestir', defaultEnabled: false },
    { key: 'afterSales.servicePhotos', label: 'Servis fotograflarini etkinlestir', defaultEnabled: true },
    { key: 'afterSales.serviceReport', label: 'Servis raporu onizlemeyi etkinlestir', defaultEnabled: true },
    { key: 'afterSales.warrantyCheck', label: 'Garanti kontrolunu etkinlestir', defaultEnabled: true },
    { key: 'afterSales.technicianAssignment', label: 'Teknisyen atamayi etkinlestir', defaultEnabled: true },
    { key: 'afterSales.accountingIntegration', label: 'Muhasebe entegrasyonu hazirligini etkinlestir', defaultEnabled: false },
  ],
  projections: [],
  events: [
    { eventType: 'after_sales.asset_created', version: '1', aggregateType: 'after_sales_installed_asset' },
    { eventType: 'after_sales.request_created', version: '1', aggregateType: 'after_sales_service_request' },
    { eventType: 'after_sales.service_completed', version: '1', aggregateType: 'after_sales_service_record' },
    { eventType: 'after_sales.maintenance_due', version: '1', aggregateType: 'after_sales_maintenance_due_item' },
    { eventType: 'after_sales.field_assignment_assigned', version: '1', aggregateType: 'after_sales_field_assignment' },
  ],
}
