import { PERMISSIONS } from '@/packages/shared/src/permissions'
import type { ModuleContract } from '../moduleContract.types'

export const crmModule: ModuleContract = {
  key: 'crm',
  name: 'CRM / Paydaslar',
  description: 'Master kisi/kurum, musteri, tedarikci, lead, etkilesim ve iliskili rol yonetimi.',
  domain: 'crm',
  category: 'business',
  version: '2026-05-28.14',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: false,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Paydas iliskisi kendi sirketimizle kurulur.' },
    { moduleKey: 'accounting', required: false, reason: 'Musteri/tedarikci icin cari kart baglantisi onerilir.' },
    { moduleKey: 'project_management', required: false, reason: 'Follow-up gorevleri Project/Task domaininde olusturulur.' },
    { moduleKey: 'after_sales', required: false, reason: 'Musteri kurulu urun ve servis kayitlari CRM paydasina baglanabilir.' },
    { moduleKey: 'hr', required: false, reason: 'Calisan/personel rolu iliskili kayit panelinde gosterilir.' },
  ],
  entities: [
    { key: 'master_person', tableName: 'master_persons', displayName: 'Master Kisi', lifecycle: false, draftSupported: false },
    { key: 'master_organization', tableName: 'master_organizations', displayName: 'Master Kurum', lifecycle: false, draftSupported: false },
    { key: 'crm_stakeholder', tableName: 'crm_stakeholders', displayName: 'Paydas', lifecycle: true, draftSupported: true },
    { key: 'crm_interaction', tableName: 'crm_interactions', displayName: 'Etkilesim', lifecycle: false, draftSupported: false },
  ],
  routes: [
    { path: '/app/crm/paydaslar', type: 'page', permission: PERMISSIONS.crm.view },
    { path: '/app/sirket/paydaslar', type: 'page', permission: PERMISSIONS.crm.view },
  ],
  menus: [{ label: 'CRM / Paydaslar', path: '/app/crm/paydaslar', icon: 'Handshake', order: 145, permission: PERMISSIONS.crm.view }],
  permissions: [
    { key: PERMISSIONS.crm.view, label: 'CRM/Paydas goruntuleme' },
    { key: PERMISSIONS.crm.create, label: 'CRM/Paydas olusturma' },
    { key: PERMISSIONS.crm.edit, label: 'CRM/Paydas duzenleme' },
    { key: PERMISSIONS.crm.delete, label: 'CRM/Paydas arsivleme' },
    { key: PERMISSIONS.crm.interactionsManage, label: 'CRM etkilesim yonetimi' },
    { key: PERMISSIONS.crm.leadsManage, label: 'Lead yonetimi' },
    { key: PERMISSIONS.crm.createCariAccount, label: 'Paydastan cari kart olusturma' },
    { key: PERMISSIONS.crm.createTask, label: 'Paydas takip gorevi olusturma' },
  ],
  actions: [
    { key: 'create_stakeholder', label: 'Paydas olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'update_stakeholder', label: 'Paydas guncelle', actionType: 'edit', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.edit },
    { key: 'create_customer', label: 'Musteri olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'create_supplier', label: 'Tedarikci olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'create_lead', label: 'Lead olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.leadsManage },
    { key: 'create_interaction', label: 'Etkilesim ekle', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.interactionsManage },
    { key: 'create_cari_from_stakeholder', label: 'Cari kart olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.createCariAccount },
    { key: 'create_followup_task', label: 'Takip gorevi olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.createTask },
    { key: 'link_existing_master_record', label: 'Mevcut master kayda bagla', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
  ],
  projections: [],
  events: [
    { eventType: 'crm.stakeholder_created', version: '1', aggregateType: 'crm_stakeholder' },
    { eventType: 'crm.interaction_created', version: '1', aggregateType: 'crm_interaction' },
    { eventType: 'crm.followup_task_created', version: '1', aggregateType: 'crm_stakeholder' },
  ],
  featureFlags: [
    { key: 'crm.enabled', label: 'CRM/Paydaslar modulunu etkinlestir', defaultEnabled: true },
    { key: 'crm.stakeholders', label: 'Paydaslar sayfasini etkinlestir', defaultEnabled: true },
    { key: 'crm.masterDataLookup', label: 'Master data lookup etkinlestir', defaultEnabled: true },
    { key: 'crm.interactions', label: 'Etkilesim timeline etkinlestir', defaultEnabled: true },
    { key: 'crm.leads', label: 'Lead hazirligini etkinlestir', defaultEnabled: true },
    { key: 'crm.cariIntegration', label: 'Cari kart entegrasyonunu etkinlestir', defaultEnabled: true },
    { key: 'crm.taskIntegration', label: 'Project task entegrasyonunu etkinlestir', defaultEnabled: true },
    { key: 'crm.afterSalesIntegration', label: 'Satis sonrasi entegrasyonunu etkinlestir', defaultEnabled: true },
  ],
}
