import { PERMISSIONS } from '@/packages/shared/src/permissions'
import type { ModuleContract } from '../moduleContract.types'

export const crmModule: ModuleContract = {
  key: 'crm',
  name: 'CRM / Paydaslar',
  description: 'Master kisi/kurum, musteri, tedarikci, lead, etkilesim ve iliskili rol yonetimi.',
  domain: 'crm',
  category: 'business',
  version: '2026-05-29.2360',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: false,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Paydas iliskisi kendi sirketimizle kurulur.' },
    { moduleKey: 'accounting', required: false, reason: 'Musteri/tedarikci icin cari kart baglantisi onerilir.' },
    { moduleKey: 'project_management', required: false, reason: 'Follow-up gorevleri Project/Task domaininde olusturulur.' },
    { moduleKey: 'after_sales', required: false, reason: 'Musteri kurulu urun ve servis kayitlari CRM paydasina baglanabilir.' },
    { moduleKey: 'hr', required: false, reason: 'Calisan/personel rolu iliskili kayit panelinde gosterilir.' },
  ],
  entities: [
    { key: 'master_person', tableName: 'master_persons', displayName: 'Master Kisi', lifecycle: false, draftSupported: false },
    { key: 'master_organization', tableName: 'master_organizations', displayName: 'Master Kurum', lifecycle: false, draftSupported: false },
    { key: 'crm_stakeholder', tableName: 'crm_stakeholders', displayName: 'Paydas', lifecycle: true, draftSupported: true },
    { key: 'crm_lead', tableName: 'crm_leads', displayName: 'Lead', lifecycle: true, draftSupported: true },
    { key: 'crm_opportunity', tableName: 'crm_opportunities', displayName: 'Firsat', lifecycle: true, draftSupported: true },
    { key: 'crm_pipeline', tableName: 'crm_pipelines', displayName: 'Pipeline', lifecycle: false, draftSupported: false },
    { key: 'crm_pipeline_stage', tableName: 'crm_pipeline_stages', displayName: 'Pipeline Asamasi', lifecycle: false, draftSupported: false },
    { key: 'crm_interaction', tableName: 'crm_interactions', displayName: 'Etkilesim', lifecycle: false, draftSupported: false },
  ],
  routes: [
    { path: '/app/crm/paydaslar', type: 'page', permission: PERMISSIONS.crm.view },
    { path: '/app/crm/leadler', type: 'page', permission: PERMISSIONS.crm.leadsView },
    { path: '/app/crm/firsatlar', type: 'page', permission: PERMISSIONS.crm.opportunitiesView },
    { path: '/app/crm/pipeline', type: 'page', permission: PERMISSIONS.crm.opportunitiesView },
    { path: '/app/crm/takipler', type: 'page', permission: PERMISSIONS.crm.followupManage },
    { path: '/app/crm/pipeline-ayarlari', type: 'page', permission: PERMISSIONS.crm.pipelineManage },
    { path: '/app/sirket/paydaslar', type: 'page', permission: PERMISSIONS.crm.view },
  ],
  menus: [
    { label: 'CRM / Paydaslar', path: '/app/crm/paydaslar', icon: 'Handshake', order: 145, permission: PERMISSIONS.crm.view },
    { label: 'CRM / Leadler', path: '/app/crm/leadler', icon: 'UserRoundPlus', order: 146, permission: PERMISSIONS.crm.leadsView },
    { label: 'CRM / Firsatlar', path: '/app/crm/firsatlar', icon: 'ChartNoAxesCombined', order: 147, permission: PERMISSIONS.crm.opportunitiesView },
    { label: 'CRM / Pipeline', path: '/app/crm/pipeline', icon: 'KanbanSquare', order: 148, permission: PERMISSIONS.crm.opportunitiesView },
    { label: 'CRM / Takipler', path: '/app/crm/takipler', icon: 'CalendarClock', order: 149, permission: PERMISSIONS.crm.followupManage },
  ],
  permissions: [
    { key: PERMISSIONS.crm.view, label: 'CRM/Paydas goruntuleme' },
    { key: PERMISSIONS.crm.create, label: 'CRM/Paydas olusturma' },
    { key: PERMISSIONS.crm.edit, label: 'CRM/Paydas duzenleme' },
    { key: PERMISSIONS.crm.delete, label: 'CRM/Paydas arsivleme' },
    { key: PERMISSIONS.crm.interactionsManage, label: 'CRM etkilesim yonetimi' },
    { key: PERMISSIONS.crm.leadsManage, label: 'Lead yonetimi' },
    { key: PERMISSIONS.crm.leadsView, label: 'Lead goruntuleme' },
    { key: PERMISSIONS.crm.leadsEdit, label: 'Lead duzenleme' },
    { key: PERMISSIONS.crm.leadsConvert, label: 'Lead donusumu' },
    { key: PERMISSIONS.crm.opportunitiesView, label: 'Firsat goruntuleme' },
    { key: PERMISSIONS.crm.opportunitiesEdit, label: 'Firsat duzenleme' },
    { key: PERMISSIONS.crm.opportunityStageChange, label: 'Firsat asamasi degistirme' },
    { key: PERMISSIONS.crm.opportunityWinLoss, label: 'Firsat kazan/kaybet islemi' },
    { key: PERMISSIONS.crm.pipelineManage, label: 'Pipeline yonetimi' },
    { key: PERMISSIONS.crm.followupManage, label: 'Takip yonetimi' },
    { key: PERMISSIONS.crm.proposalManage, label: 'Teklif baglantisi yonetimi' },
    { key: PERMISSIONS.crm.createCariAccount, label: 'Paydastan cari kart olusturma' },
    { key: PERMISSIONS.crm.createTask, label: 'Paydas takip gorevi olusturma' },
  ],
  actions: [
    { key: 'create_stakeholder', label: 'Paydas olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'update_stakeholder', label: 'Paydas guncelle', actionType: 'edit', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.edit },
    { key: 'create_customer', label: 'Musteri olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'create_supplier', label: 'Tedarikci olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
    { key: 'create_lead', label: 'Lead olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.leadsManage },
    { key: 'convert_lead', label: 'Lead donustur', actionType: 'operation', targetPage: '/app/crm/leadler', permission: PERMISSIONS.crm.leadsConvert },
    { key: 'create_opportunity', label: 'Firsat olustur', actionType: 'operation', targetPage: '/app/crm/firsatlar', permission: PERMISSIONS.crm.opportunitiesEdit },
    { key: 'change_opportunity_stage', label: 'Firsat asamasini degistir', actionType: 'operation', targetPage: '/app/crm/pipeline', permission: PERMISSIONS.crm.opportunityStageChange },
    { key: 'complete_followup', label: 'Takip tamamla', actionType: 'operation', targetPage: '/app/crm/takipler', permission: PERMISSIONS.crm.followupManage },
    { key: 'create_interaction', label: 'Etkilesim ekle', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.interactionsManage },
    { key: 'create_cari_from_stakeholder', label: 'Cari kart olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.createCariAccount },
    { key: 'create_followup_task', label: 'Takip gorevi olustur', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.createTask },
    { key: 'link_existing_master_record', label: 'Mevcut master kayda bagla', actionType: 'operation', targetPage: '/app/crm/paydaslar', permission: PERMISSIONS.crm.create },
  ],
  projections: [],
  events: [
    { eventType: 'crm.stakeholder_created', version: '1', aggregateType: 'crm_stakeholder' },
    { eventType: 'crm.interaction_created', version: '1', aggregateType: 'crm_interaction' },
    { eventType: 'crm.followup_task_created', version: '1', aggregateType: 'crm_stakeholder' },
    { eventType: 'crm.lead_created', version: '1', aggregateType: 'crm_lead' },
    { eventType: 'crm.lead_converted', version: '1', aggregateType: 'crm_lead' },
    { eventType: 'crm.opportunity_stage_changed', version: '1', aggregateType: 'crm_opportunity' },
  ],
  featureFlags: [
    { key: 'crm.enabled', label: 'CRM/Paydaslar modulunu etkinlestir', defaultEnabled: true },
    { key: 'crm.stakeholders', label: 'Paydaslar sayfasini etkinlestir', defaultEnabled: true },
    { key: 'crm.masterDataLookup', label: 'Master data lookup etkinlestir', defaultEnabled: true },
    { key: 'crm.interactions', label: 'Etkilesim timeline etkinlestir', defaultEnabled: true },
    { key: 'crm.leads', label: 'Lead hazirligini etkinlestir', defaultEnabled: true },
    { key: 'crm.opportunities', label: 'Firsat yonetimini etkinlestir', defaultEnabled: true },
    { key: 'crm.pipeline', label: 'Pipeline yonetimini etkinlestir', defaultEnabled: true },
    { key: 'crm.followups', label: 'Takip otomasyonunu etkinlestir', defaultEnabled: true },
    { key: 'crm.proposals', label: 'Teklif baglantilarini etkinlestir', defaultEnabled: true },
    { key: 'crm.leadConversion', label: 'Lead donusum akislarini etkinlestir', defaultEnabled: true },
    { key: 'crm.opportunityKanban', label: 'Firsat kanban gorunumunu etkinlestir', defaultEnabled: true },
    { key: 'crm.crmNotifications', label: 'CRM bildirimlerini etkinlestir', defaultEnabled: true },
    { key: 'crm.cariIntegration', label: 'Cari kart entegrasyonunu etkinlestir', defaultEnabled: true },
    { key: 'crm.taskIntegration', label: 'Project task entegrasyonunu etkinlestir', defaultEnabled: true },
    { key: 'crm.afterSalesIntegration', label: 'Satis sonrasi entegrasyonunu etkinlestir', defaultEnabled: true },
  ],
}
