import type { ModuleContract } from '../moduleContract.types'
import { HR_PERMISSIONS } from '../hr/shared/hr.permissions'

export const hrModule: ModuleContract = {
  key: 'hr',
  name: 'Insan Kaynaklari',
  description: 'Calisan kartlari, istihdam lifecycle, SGK manuel takip ve ozluk dosyasi.',
  domain: 'hr',
  category: 'operations',
  version: '2026-05-28.1',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: true,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Calisan ve istihdam kayitlari sirket kapsaminda tutulur.' },
    { moduleKey: 'organization', required: false, reason: 'Organizasyon birimi ve pozisyon atamalari icin onerilir.' },
    { moduleKey: 'branches', required: false, reason: 'Sube bazli calisan listesi ve atama icin onerilir.' },
    { moduleKey: 'facilities', required: false, reason: 'Lokasyon bazli calisma yeri baglantisi ileride kullanilir.' },
    { moduleKey: 'accounting', required: false, reason: 'Ucret ve odeme mutabakati ileride muhasebe ile kurulur.' },
  ],
  entities: [
    { key: 'hr_employee', tableName: 'hr_employees', displayName: 'Calisan', lifecycle: true, draftSupported: true, hardDeleteDraftOnly: true },
    { key: 'hr_employment_record', tableName: 'hr_employment_records', displayName: 'Istihdam Kaydi', lifecycle: true },
    { key: 'hr_employment_transaction', tableName: 'hr_employment_transactions', displayName: 'Istihdam Islemi' },
    { key: 'hr_employee_document', tableName: 'hr_employee_documents', displayName: 'Ozluk Belgesi' },
  ],
  routes: [
    { path: '/app/ik/calisanlar', type: 'page', permission: HR_PERMISSIONS.view },
    { path: '/app/ik/employees', type: 'page', permission: HR_PERMISSIONS.view },
    { path: '/api/hr/employees', type: 'api', permission: HR_PERMISSIONS.view },
  ],
  menus: [
    { label: 'Calisanlar', path: '/app/ik/calisanlar', icon: 'Users', order: 120, permission: HR_PERMISSIONS.view },
    { label: 'Istihdam Islemleri', path: '/app/ik/istihdam-islemleri', icon: 'BriefcaseBusiness', order: 121, permission: HR_PERMISSIONS.view, featureFlag: 'hr.employmentLifecycle' },
    { label: 'Ozluk Belgeleri', path: '/app/ik/ozluk-belgeleri', icon: 'FileText', order: 122, permission: HR_PERMISSIONS.view, featureFlag: 'hr.employeeDocuments' },
    { label: 'SGK Islemleri', path: '/app/ik/sgk-islemleri', icon: 'ShieldCheck', order: 123, permission: HR_PERMISSIONS.view, featureFlag: 'hr.sgkManualTracking' },
  ],
  permissions: [
    { key: HR_PERMISSIONS.view, label: 'Calisanlari goruntuleme', fallback: ['companies.view'] },
    { key: HR_PERMISSIONS.edit, label: 'Calisan kartlarini duzenleme', fallback: ['companies.edit'] },
    { key: HR_PERMISSIONS.employeeCreate, label: 'Calisan karti taslagi olusturma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.employmentStart, label: 'Ise giris baslatma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.employmentTerminate, label: 'Isten cikis baslatma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.assignmentChange, label: 'Organizasyon ve pozisyon degisikligi', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.documentsManage, label: 'Ozluk belgelerini yonetme', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.sensitiveView, label: 'Hassas calisan bilgilerini goruntuleme', fallback: [HR_PERMISSIONS.view] },
  ],
  actions: [
    { key: 'create_employee_draft', label: 'Calisan Karti Taslagi Olustur', actionType: 'create_draft', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employeeCreate },
    { key: 'start_employment', label: 'Ise Giris Baslat', actionType: 'open_wizard', targetPage: '/app/ik/calisanlar', wizardKey: 'hr.startEmployment', permission: HR_PERMISSIONS.employmentStart, requiredRecordType: 'hr_employee', requiredRecordStatus: ['draft'] },
    { key: 'terminate_employment', label: 'Isten Cikis', actionType: 'open_wizard', targetPage: '/app/ik/calisanlar', wizardKey: 'hr.terminateEmployment', permission: HR_PERMISSIONS.employmentTerminate, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'change_assignment', label: 'Pozisyon / Organizasyon Degisikligi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.assignmentChange, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'mark_sgk_entry_completed', label: 'SGK Girisi Yapildi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employmentStart, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'mark_sgk_exit_completed', label: 'SGK Cikisi Yapildi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employmentTerminate, requiredRecordType: 'hr_employee', requiredRecordStatus: ['terminated', 'passive'] },
    { key: 'manage_employee_documents', label: 'Ozluk Belgelerini Yonet', actionType: 'edit', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.documentsManage, requiredRecordType: 'hr_employee' },
  ],
  projections: [],
  events: [
    { eventType: 'hr.employee.created', version: 'v1', aggregateType: 'hr_employee' },
    { eventType: 'hr.employment.started', version: 'v1', aggregateType: 'hr_employment_record' },
    { eventType: 'hr.employment.terminated', version: 'v1', aggregateType: 'hr_employment_record' },
  ],
  featureFlags: [
    { key: 'hr.enabled', label: 'IK modulu', defaultEnabled: true },
    { key: 'hr.employees', label: 'Calisan kartlari', defaultEnabled: true },
    { key: 'hr.employmentLifecycle', label: 'Istihdam lifecycle', defaultEnabled: true },
    { key: 'hr.sgkManualTracking', label: 'SGK manuel takip', defaultEnabled: true },
    { key: 'hr.employeeDocuments', label: 'Ozluk belgeleri', defaultEnabled: true },
    { key: 'hr.positionAssignment', label: 'Pozisyon atamasi', defaultEnabled: true },
    { key: 'hr.salaryBasicInfo', label: 'Temel ucret bilgisi', defaultEnabled: false },
  ],
}
