import type { ModuleContract } from '../moduleContract.types'
import { HR_PERMISSIONS } from '../hr/shared/hr.permissions'

export const hrModule: ModuleContract = {
  key: 'hr',
  name: 'Insan Kaynaklari',
  description: 'Calisan, istihdam lifecycle, izin, devam-devamsizlik, puantaj ve bordro hazirligi.',
  domain: 'hr',
  category: 'operations',
  version: '2026-05-29.2',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: true,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Calisan ve istihdam kayitlari sirket kapsaminda tutulur.' },
    { moduleKey: 'organization', required: false, reason: 'Organizasyon birimi ve pozisyon atamalari icin onerilir.' },
    { moduleKey: 'branches', required: false, reason: 'Sube bazli calisan listesi ve atama icin onerilir.' },
    { moduleKey: 'facilities', required: false, reason: 'Lokasyon bazli calisma yeri baglantisi ileride kullanilir.' },
    { moduleKey: 'accounting', required: false, reason: 'Ucret ve odeme mutabakati ileride muhasebe ile kurulur.' },
  ],
  entities: [
    { key: 'hr_employee', tableName: 'hr_employees', displayName: 'Calisan', lifecycle: true, draftSupported: true, hardDeleteDraftOnly: true },
    { key: 'hr_employment_record', tableName: 'hr_employment_records', displayName: 'Istihdam Kaydi', lifecycle: true },
    { key: 'hr_employment_transaction', tableName: 'hr_employment_transactions', displayName: 'Istihdam Islemi' },
    { key: 'hr_employee_document', tableName: 'hr_employee_documents', displayName: 'Ozluk Belgesi' },
    { key: 'hr_leave_type', tableName: 'hr_leave_types', displayName: 'Izin Turu' },
    { key: 'hr_leave_balance', tableName: 'hr_leave_balances', displayName: 'Izin Bakiyesi' },
    { key: 'hr_leave_request', tableName: 'hr_leave_requests', displayName: 'Izin Talebi', lifecycle: true },
    { key: 'hr_attendance_record', tableName: 'hr_attendance_records', displayName: 'Devam Kaydi' },
    { key: 'hr_work_schedule', tableName: 'hr_work_schedules', displayName: 'Calisma Plani' },
    { key: 'hr_timesheet_period', tableName: 'hr_timesheet_periods', displayName: 'Puantaj Donemi', lifecycle: true },
    { key: 'hr_payroll_preparation_row', tableName: 'hr_payroll_preparation_rows', displayName: 'Bordro Hazirlik Satiri' },
  ],
  routes: [
    { path: '/app/ik/calisanlar', type: 'page', permission: HR_PERMISSIONS.view },
    { path: '/app/ik/employees', type: 'page', permission: HR_PERMISSIONS.view },
    { path: '/app/ik/izinler', type: 'page', permission: HR_PERMISSIONS.leaveView },
    { path: '/app/ik/izin-turleri', type: 'page', permission: HR_PERMISSIONS.leaveAdmin },
    { path: '/app/ik/izin-bakiyeleri', type: 'page', permission: HR_PERMISSIONS.leaveView },
    { path: '/app/ik/devam-devamsizlik', type: 'page', permission: HR_PERMISSIONS.attendanceView },
    { path: '/app/ik/puantaj', type: 'page', permission: HR_PERMISSIONS.timesheetView },
    { path: '/app/ik/calisma-planlari', type: 'page', permission: HR_PERMISSIONS.attendanceView },
    { path: '/api/hr/employees', type: 'api', permission: HR_PERMISSIONS.view },
    { path: '/api/hr/leave-requests', type: 'api', permission: HR_PERMISSIONS.leaveView },
    { path: '/api/hr/attendance', type: 'api', permission: HR_PERMISSIONS.attendanceView },
    { path: '/api/hr/timesheets', type: 'api', permission: HR_PERMISSIONS.timesheetView },
    { path: '/api/hr/payroll-prep', type: 'api', permission: HR_PERMISSIONS.payrollPrepView },
  ],
  menus: [
    { label: 'Calisanlar', path: '/app/ik/calisanlar', icon: 'Users', order: 120, permission: HR_PERMISSIONS.view },
    { label: 'Istihdam Islemleri', path: '/app/ik/istihdam-islemleri', icon: 'BriefcaseBusiness', order: 121, permission: HR_PERMISSIONS.view, featureFlag: 'hr.employmentLifecycle' },
    { label: 'Ozluk Belgeleri', path: '/app/ik/ozluk-belgeleri', icon: 'FileText', order: 122, permission: HR_PERMISSIONS.view, featureFlag: 'hr.employeeDocuments' },
    { label: 'SGK Islemleri', path: '/app/ik/sgk-islemleri', icon: 'ShieldCheck', order: 123, permission: HR_PERMISSIONS.view, featureFlag: 'hr.sgkManualTracking' },
    { label: 'Izinler', path: '/app/ik/izinler', icon: 'CalendarCheck', order: 124, permission: HR_PERMISSIONS.leaveView, featureFlag: 'hr.leaveManagement' },
    { label: 'Izin Turleri', path: '/app/ik/izin-turleri', icon: 'ClipboardList', order: 125, permission: HR_PERMISSIONS.leaveAdmin, featureFlag: 'hr.leaveManagement' },
    { label: 'Izin Bakiyeleri', path: '/app/ik/izin-bakiyeleri', icon: 'FileWarning', order: 126, permission: HR_PERMISSIONS.leaveView, featureFlag: 'hr.leaveManagement' },
    { label: 'Devam Devamsizlik', path: '/app/ik/devam-devamsizlik', icon: 'TimerReset', order: 127, permission: HR_PERMISSIONS.attendanceView, featureFlag: 'hr.attendance' },
    { label: 'Puantaj', path: '/app/ik/puantaj', icon: 'CalendarClock', order: 128, permission: HR_PERMISSIONS.timesheetView, featureFlag: 'hr.timesheets' },
    { label: 'Calisma Planlari', path: '/app/ik/calisma-planlari', icon: 'ClipboardList', order: 129, permission: HR_PERMISSIONS.attendanceView, featureFlag: 'hr.workSchedules' },
  ],
  permissions: [
    { key: HR_PERMISSIONS.view, label: 'Calisanlari goruntuleme', fallback: ['companies.view'] },
    { key: HR_PERMISSIONS.edit, label: 'Calisan kartlarini duzenleme', fallback: ['companies.edit'] },
    { key: HR_PERMISSIONS.employeeCreate, label: 'Calisan karti taslagi olusturma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.employmentStart, label: 'Ise giris baslatma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.employmentTerminate, label: 'Isten cikis baslatma', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.assignmentChange, label: 'Organizasyon ve pozisyon degisikligi', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.documentsManage, label: 'Ozluk belgelerini yonetme', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.leaveView, label: 'Izinleri goruntuleme', fallback: [HR_PERMISSIONS.view] },
    { key: HR_PERMISSIONS.leaveRequestCreate, label: 'Izin talebi olusturma', fallback: [HR_PERMISSIONS.leaveView] },
    { key: HR_PERMISSIONS.leaveApprove, label: 'Izin onaylama', fallback: [HR_PERMISSIONS.leaveAdmin] },
    { key: HR_PERMISSIONS.leaveAdmin, label: 'Izin politikasi yonetimi', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.attendanceView, label: 'Devam-devamsizlik goruntuleme', fallback: [HR_PERMISSIONS.view] },
    { key: HR_PERMISSIONS.attendanceEdit, label: 'Devam-devamsizlik duzenleme', fallback: [HR_PERMISSIONS.edit] },
    { key: HR_PERMISSIONS.timesheetView, label: 'Puantaj goruntuleme', fallback: [HR_PERMISSIONS.attendanceView] },
    { key: HR_PERMISSIONS.timesheetManage, label: 'Puantaj yonetimi', fallback: [HR_PERMISSIONS.attendanceEdit] },
    { key: HR_PERMISSIONS.timesheetApprove, label: 'Puantaj onaylama', fallback: [HR_PERMISSIONS.timesheetManage] },
    { key: HR_PERMISSIONS.payrollPrepView, label: 'Bordro hazirligi goruntuleme', fallback: [HR_PERMISSIONS.timesheetView] },
    { key: HR_PERMISSIONS.payrollPrepManage, label: 'Bordro hazirligi yonetimi', fallback: [HR_PERMISSIONS.timesheetApprove] },
    { key: HR_PERMISSIONS.sensitiveView, label: 'Hassas calisan bilgilerini goruntuleme', fallback: [HR_PERMISSIONS.view] },
  ],
  actions: [
    { key: 'create_employee_draft', label: 'Calisan Karti Taslagi Olustur', actionType: 'create_draft', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employeeCreate },
    { key: 'start_employment', label: 'Ise Giris Baslat', actionType: 'open_wizard', targetPage: '/app/ik/calisanlar', wizardKey: 'hr.startEmployment', permission: HR_PERMISSIONS.employmentStart, requiredRecordType: 'hr_employee', requiredRecordStatus: ['draft'] },
    { key: 'terminate_employment', label: 'Isten Cikis', actionType: 'open_wizard', targetPage: '/app/ik/calisanlar', wizardKey: 'hr.terminateEmployment', permission: HR_PERMISSIONS.employmentTerminate, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'change_assignment', label: 'Pozisyon / Organizasyon Degisikligi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.assignmentChange, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'mark_sgk_entry_completed', label: 'SGK Girisi Yapildi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employmentStart, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'] },
    { key: 'mark_sgk_exit_completed', label: 'SGK Cikisi Yapildi', actionType: 'operation', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.employmentTerminate, requiredRecordType: 'hr_employee', requiredRecordStatus: ['terminated', 'passive'] },
    { key: 'manage_employee_documents', label: 'Ozluk Belgelerini Yonet', actionType: 'edit', targetPage: '/app/ik/calisanlar', permission: HR_PERMISSIONS.documentsManage, requiredRecordType: 'hr_employee' },
    { key: 'create_leave_request', label: 'Izin Talebi Olustur', actionType: 'operation', targetPage: '/app/ik/izinler', permission: HR_PERMISSIONS.leaveRequestCreate, requiredRecordType: 'hr_employee', requiredRecordStatus: ['active'], featureFlag: 'hr.leaveManagement' },
    { key: 'approve_leave_request', label: 'Izin Talebini Onayla', actionType: 'operation', targetPage: '/app/ik/izinler', permission: HR_PERMISSIONS.leaveApprove, requiredRecordType: 'hr_leave_request', requiredRecordStatus: ['pending_approval'], featureFlag: 'hr.leaveApprovals' },
    { key: 'calculate_timesheet', label: 'Puantaj Hesapla', actionType: 'operation', targetPage: '/app/ik/puantaj', permission: HR_PERMISSIONS.timesheetManage, requiredRecordType: 'hr_timesheet_period' },
    { key: 'mark_payroll_ready', label: 'Bordro Hazirligina Gonder', actionType: 'operation', targetPage: '/app/ik/puantaj', permission: HR_PERMISSIONS.payrollPrepManage, requiredRecordType: 'hr_timesheet_period', requiredRecordStatus: ['approved', 'locked'] },
  ],
  projections: [],
  events: [
    { eventType: 'hr.employee.created', version: 'v1', aggregateType: 'hr_employee' },
    { eventType: 'hr.employment.started', version: 'v1', aggregateType: 'hr_employment_record' },
    { eventType: 'hr.employment.terminated', version: 'v1', aggregateType: 'hr_employment_record' },
    { eventType: 'hr.leave.requested', version: 'v1', aggregateType: 'hr_leave_request' },
    { eventType: 'hr.leave.approved', version: 'v1', aggregateType: 'hr_leave_request' },
    { eventType: 'hr.timesheet.locked', version: 'v1', aggregateType: 'hr_timesheet_period' },
  ],
  featureFlags: [
    { key: 'hr.enabled', label: 'IK modulu', defaultEnabled: true },
    { key: 'hr.employees', label: 'Calisan kartlari', defaultEnabled: true },
    { key: 'hr.employmentLifecycle', label: 'Istihdam lifecycle', defaultEnabled: true },
    { key: 'hr.sgkManualTracking', label: 'SGK manuel takip', defaultEnabled: true },
    { key: 'hr.employeeDocuments', label: 'Ozluk belgeleri', defaultEnabled: true },
    { key: 'hr.positionAssignment', label: 'Pozisyon atamasi', defaultEnabled: true },
    { key: 'hr.salaryBasicInfo', label: 'Temel ucret bilgisi', defaultEnabled: false },
    { key: 'hr.leaveManagement', label: 'Izin yonetimi', defaultEnabled: true },
    { key: 'hr.attendance', label: 'Devam-devamsizlik', defaultEnabled: true },
    { key: 'hr.workSchedules', label: 'Calisma planlari', defaultEnabled: true },
    { key: 'hr.timesheets', label: 'Puantaj', defaultEnabled: true },
    { key: 'hr.payrollPreparation', label: 'Bordro hazirligi', defaultEnabled: true },
    { key: 'hr.leaveApprovals', label: 'Izin onaylari', defaultEnabled: true },
    { key: 'hr.overtime', label: 'Fazla mesai', defaultEnabled: true },
    { key: 'hr.attendanceImport', label: 'Devam kaydi import', defaultEnabled: false },
  ],
}
