import type { ModuleContract } from '../moduleContract.types'
import { PROJECT_MANAGEMENT_PERMISSIONS } from '../project-management/projectManagement.permissions'

export const projectManagementModule: ModuleContract = {
  key: 'project_management',
  name: 'Proje ve Gorevler',
  description: 'Jira benzeri proje, issue ve ekip gorevi takibi.',
  domain: 'work',
  category: 'operations',
  version: '2026-05-28.1',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: true,
  setupRequired: true,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Projeler ve gorevler sirket scope ile acilir.' },
    { moduleKey: 'hr', required: false, reason: 'Gorev atamalarinda calisan baglantisi onerilir.' },
    { moduleKey: 'organization', required: false, reason: 'Birim ve pozisyon bazli takip icin onerilir.' },
    { moduleKey: 'branches', required: false, reason: 'Sube kapsamli gorevler icin onerilir.' },
    { moduleKey: 'facilities', required: false, reason: 'Tesis/lokasyon kapsamli gorevler icin onerilir.' },
  ],
  entities: [
    { key: 'project_project', tableName: 'project_projects', displayName: 'Proje', draftSupported: true },
    { key: 'project_task', tableName: 'project_tasks', displayName: 'Proje Gorevi', draftSupported: true },
    { key: 'project_task_comment', tableName: 'project_task_comments', displayName: 'Gorev Yorumu' },
    { key: 'project_task_attachment', tableName: 'project_task_attachments', displayName: 'Gorev Eki' },
  ],
  routes: [
    { path: '/app/gorev-ve-proje-yonetimi', type: 'page', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsView },
    { path: '/app/gorev-ve-proje-yonetimi/projeler', type: 'page', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsView },
    { path: '/app/gorev-ve-proje-yonetimi/gorevler', type: 'page', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView },
    { path: '/app/gorev-ve-proje-yonetimi/kanban-board', type: 'page', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView },
    { path: '/api/projects', type: 'api', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsView },
    { path: '/api/project-tasks', type: 'api', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView },
  ],
  menus: [
    { label: 'Proje ve Gorevler', path: '/app/gorev-ve-proje-yonetimi', icon: 'ListChecks', order: 130, permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsView },
    { label: 'Projeler', path: '/app/gorev-ve-proje-yonetimi/projeler', icon: 'FolderOpen', order: 131, parent: 'project_management', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsView, featureFlag: 'projectManagement.projects' },
    { label: 'Gorevler', path: '/app/gorev-ve-proje-yonetimi/gorevler', icon: 'CheckCircle2', order: 132, parent: 'project_management', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView, featureFlag: 'projectManagement.tasks' },
    { label: 'Bana Atananlar', path: '/app/gorev-ve-proje-yonetimi/gorevler?mine=1', icon: 'UserCheck', order: 133, parent: 'project_management', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView, featureFlag: 'projectManagement.tasks' },
    { label: 'Kanban', path: '/app/gorev-ve-proje-yonetimi/kanban-board', icon: 'Columns3', order: 134, parent: 'project_management', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksView, featureFlag: 'projectManagement.kanban' },
  ],
  permissions: [
    { key: PROJECT_MANAGEMENT_PERMISSIONS.projectsView, label: 'Projeleri goruntuleme', fallback: ['companies.view'] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit, label: 'Projeleri duzenleme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsView] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.projectsCreate, label: 'Proje olusturma', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.projectsDelete, label: 'Proje silme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksView, label: 'Proje gorevlerini goruntuleme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsView] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksCreate, label: 'Proje gorevi olusturma', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsView] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksEdit, label: 'Proje gorevlerini duzenleme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksAssign, label: 'Proje gorevi atama', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.tasksEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksTransition, label: 'Gorev durumu degistirme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.tasksEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksComment, label: 'Gorev yorumu ekleme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.tasksView] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksAttachmentsManage, label: 'Gorev eklerini yonetme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.tasksEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.tasksDelete, label: 'Proje gorevi silme', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.tasksEdit] },
    { key: PROJECT_MANAGEMENT_PERMISSIONS.admin, label: 'Proje ve gorev yoneticisi', fallback: [PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit] },
  ],
  actions: [
    { key: 'create_project', label: 'Proje Olustur', actionType: 'create_draft', targetPage: '/app/gorev-ve-proje-yonetimi/projeler', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsCreate },
    { key: 'update_project', label: 'Projeyi Guncelle', actionType: 'edit', targetPage: '/app/gorev-ve-proje-yonetimi/projeler', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit, requiredRecordType: 'project_project' },
    { key: 'complete_project', label: 'Projeyi Tamamla', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/projeler', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit, requiredRecordType: 'project_project', requiredRecordStatus: ['active', 'on_hold'] },
    { key: 'cancel_project', label: 'Projeyi Iptal Et', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/projeler', permission: PROJECT_MANAGEMENT_PERMISSIONS.projectsEdit, requiredRecordType: 'project_project' },
    { key: 'create_project_task', label: 'Proje Gorevi Olustur', actionType: 'create_draft', targetPage: '/app/gorev-ve-proje-yonetimi/gorevler', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksCreate },
    { key: 'assign_project_task', label: 'Gorev Ata', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/gorevler', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksAssign, requiredRecordType: 'project_task' },
    { key: 'transition_project_task', label: 'Gorev Durumu Degistir', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/kanban-board', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksTransition, requiredRecordType: 'project_task' },
    { key: 'comment_project_task', label: 'Goreve Yorum Ekle', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/gorevler', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksComment, requiredRecordType: 'project_task' },
    { key: 'attach_project_task', label: 'Goreve Dosya Ekle', actionType: 'operation', targetPage: '/app/gorev-ve-proje-yonetimi/gorevler', permission: PROJECT_MANAGEMENT_PERMISSIONS.tasksAttachmentsManage, requiredRecordType: 'project_task' },
  ],
  projections: [],
  events: [
    { eventType: 'task.created', version: '1', aggregateType: 'project_task' },
    { eventType: 'task.updated', version: '1', aggregateType: 'project_task' },
    { eventType: 'task.transitioned', version: '1', aggregateType: 'project_task' },
    { eventType: 'task.assigned', version: '1', aggregateType: 'project_task' },
    { eventType: 'task.commented', version: '1', aggregateType: 'project_task' },
    { eventType: 'task.attachment_added', version: '1', aggregateType: 'project_task' },
  ],
  featureFlags: [
    { key: 'projectManagement.enabled', label: 'Proje ve Gorevler', defaultEnabled: true },
    { key: 'projectManagement.projects', label: 'Projeler', defaultEnabled: true },
    { key: 'projectManagement.tasks', label: 'Gorevler', defaultEnabled: true },
    { key: 'projectManagement.kanban', label: 'Kanban', defaultEnabled: true },
    { key: 'projectManagement.comments', label: 'Yorumlar', defaultEnabled: true },
    { key: 'projectManagement.attachments', label: 'Ekler', defaultEnabled: true },
    { key: 'projectManagement.timeTracking', label: 'Zaman Takibi', defaultEnabled: false },
    { key: 'projectManagement.sprints', label: 'Sprintler', defaultEnabled: false },
  ],
}
