import { PERMISSIONS } from '@/packages/shared/src/permissions'
import type { ModuleContract } from '../moduleContract.types'

export const reportingModule: ModuleContract = {
  key: 'reporting',
  name: 'Raporlama',
  description: 'Kayitli gorunumler, ozel raporlar, zamanlanmis raporlar ve guvenli export joblari.',
  domain: 'reporting',
  category: 'business',
  version: '2026-05-29.2370',
  status: 'active',
  defaultEnabled: true,
  licenseRequired: false,
  setupRequired: false,
  dependencies: [
    { moduleKey: 'companies', required: true, reason: 'Raporlar sirket scope uzerinden filtrelenir.' },
    { moduleKey: 'accounting', required: false, reason: 'Finansal KPI kartlari icin Accounting summary kaynaklari kullanilir.' },
    { moduleKey: 'hr', required: false, reason: 'IK KPI kartlari icin HR summary kaynaklari kullanilir.' },
    { moduleKey: 'project_management', required: false, reason: 'Gorev ve proje KPI kartlari icin Project/Task read modelleri kullanilir.' },
    { moduleKey: 'after_sales', required: false, reason: 'Servis ve bakim KPI kartlari icin After-Sales summary kaynaklari kullanilir.' },
    { moduleKey: 'crm', required: false, reason: 'Musteri, tedarikci ve lead KPI kartlari icin CRM read-side kaynaklari kullanilir.' },
  ],
  entities: [
    { key: 'report_definition', displayName: 'Rapor Tanimi', lifecycle: false, draftSupported: false },
    { key: 'dashboard_kpi', displayName: 'Dashboard KPI', lifecycle: false, draftSupported: false },
    { key: 'report_export_request', displayName: 'Rapor Export Istegi', lifecycle: false, draftSupported: false },
    { key: 'reporting_saved_view', displayName: 'Kayitli Gorunum', lifecycle: false, draftSupported: false },
    { key: 'reporting_custom_report', displayName: 'Ozel Rapor', lifecycle: false, draftSupported: false },
    { key: 'reporting_scheduled_report', displayName: 'Zamanlanmis Rapor', lifecycle: false, draftSupported: false },
    { key: 'reporting_export_job', displayName: 'Export Job', lifecycle: false, draftSupported: false },
  ],
  routes: [
    { path: '/app/raporlama/ozel-raporlar', type: 'page', permission: PERMISSIONS.reporting.customReportsManage },
    { path: '/app/raporlama/zamanlanmis-raporlar', type: 'page', permission: PERMISSIONS.reporting.scheduledReportsManage },
    { path: '/api/reporting/dashboard', type: 'api', permission: PERMISSIONS.reporting.dashboardView },
    { path: '/api/reporting/reports', type: 'api', permission: PERMISSIONS.reporting.view },
    { path: '/api/reporting/saved-views', type: 'api', permission: PERMISSIONS.reporting.view },
    { path: '/api/reporting/custom-reports', type: 'api', permission: PERMISSIONS.reporting.customReportsManage },
    { path: '/api/reporting/scheduled-reports', type: 'api', permission: PERMISSIONS.reporting.scheduledReportsManage },
    { path: '/api/reporting/exports', type: 'api', permission: PERMISSIONS.reporting.export },
  ],
  menus: [
    { label: 'Ozel Raporlar', path: '/app/raporlama/ozel-raporlar', icon: 'FileSpreadsheet', order: 21, permission: PERMISSIONS.reporting.customReportsManage },
    { label: 'Zamanlanmis Raporlar', path: '/app/raporlama/zamanlanmis-raporlar', icon: 'CalendarClock', order: 22, permission: PERMISSIONS.reporting.scheduledReportsManage },
  ],
  permissions: [
    { key: PERMISSIONS.reporting.view, label: 'Raporlari goruntule' },
    { key: PERMISSIONS.reporting.dashboardView, label: 'Raporlama ozetlerini goruntule' },
    { key: PERMISSIONS.reporting.export, label: 'Rapor export al' },
    { key: PERMISSIONS.reporting.admin, label: 'Raporlama yoneticisi' },
    { key: PERMISSIONS.reporting.viewFinancial, label: 'Finansal KPI goruntule' },
    { key: PERMISSIONS.reporting.viewAuditSummary, label: 'Audit ozet KPI goruntule' },
    { key: PERMISSIONS.reporting.viewHR, label: 'IK KPI goruntule' },
    { key: PERMISSIONS.reporting.viewSystem, label: 'Sistem KPI goruntule' },
    { key: PERMISSIONS.reporting.savedViewsManage, label: 'Kayitli gorunumleri yonet/paylas' },
    { key: PERMISSIONS.reporting.customReportsManage, label: 'Ozel rapor tanimlarini yonet' },
    { key: PERMISSIONS.reporting.scheduledReportsManage, label: 'Zamanlanmis raporlari yonet' },
    { key: PERMISSIONS.reporting.exportManage, label: 'Export joblarini yonet' },
    { key: PERMISSIONS.reporting.dashboardCustomize, label: 'Raporlama gorunumlerini kisisellestir' },
  ],
  actions: [
    { key: 'query_report', label: 'Rapor sorgula', actionType: 'view', targetPage: '/app/raporlama/ozel-raporlar', permission: PERMISSIONS.reporting.view },
    { key: 'export_report', label: 'Rapor export hazirla', actionType: 'operation', targetPage: '/app/raporlama/ozel-raporlar', permission: PERMISSIONS.reporting.export },
    { key: 'create_saved_view', label: 'Gorunum kaydet', actionType: 'operation', targetPage: '/app/raporlama/ozel-raporlar', permission: PERMISSIONS.reporting.view },
    { key: 'create_scheduled_report', label: 'Rapor zamanla', actionType: 'operation', targetPage: '/app/raporlama/zamanlanmis-raporlar', permission: PERMISSIONS.reporting.scheduledReportsManage },
  ],
  projections: [
    { key: 'company_summary', projectionKey: 'companyList', required: false },
    { key: 'current_ownership', projectionKey: 'currentOwnership', required: false },
    { key: 'branch_summary', projectionKey: 'branchSummary', required: false },
    { key: 'pending_actions', projectionKey: 'pendingActions', required: false },
  ],
  events: [
    { eventType: 'report.query_executed', version: '1', aggregateType: 'report' },
    { eventType: 'report.export_requested', version: '1', aggregateType: 'report' },
    { eventType: 'report.saved_view_created', version: '1', aggregateType: 'saved_view' },
    { eventType: 'report.scheduled_run_completed', version: '1', aggregateType: 'scheduled_report' },
  ],
  featureFlags: [
    { key: 'reporting.enabled', label: 'Raporlama modulunu etkinlestir', defaultEnabled: true },
    { key: 'reporting.exports', label: 'Rapor export hazirligini etkinlestir', defaultEnabled: false },
    { key: 'reporting.savedViews', label: 'Kayitli gorunumleri etkinlestir', defaultEnabled: true },
    { key: 'reporting.customReports', label: 'Ozel raporlari etkinlestir', defaultEnabled: true },
    { key: 'reporting.scheduledReports', label: 'Zamanlanmis raporlari etkinlestir', defaultEnabled: true },
    { key: 'reporting.exportJobs', label: 'Export job yonetimini etkinlestir', defaultEnabled: true },
    { key: 'reporting.crossModuleReports', label: 'Moduller arasi yonetim raporlarini etkinlestir', defaultEnabled: true },
    { key: 'reporting.financialKpis', label: 'Finansal KPI kartlarini etkinlestir', defaultEnabled: true },
    { key: 'reporting.auditKpis', label: 'Audit KPI kartlarini etkinlestir', defaultEnabled: true },
    { key: 'reporting.hrKpis', label: 'IK KPI kartlarini etkinlestir', defaultEnabled: true },
    { key: 'reporting.systemKpis', label: 'Sistem KPI kartlarini etkinlestir', defaultEnabled: true },
  ],
}
