import { z } from 'zod'
import type { EdenApiContract } from '../../core/api.contract'
import { safeApiErrorSchema, successResponseSchema, uuidString } from '../../core/validation.contract'
import { employeeCreateFormSchema, employeeDocumentFormSchema } from '../../forms/hr/employee.form.contract'
import { assignmentChangePayloadSchema } from '../../wizards/hr/assignment-change.wizard.contract'
import { employmentStartPayloadSchema } from '../../wizards/hr/employment-start.wizard.contract'
import { employmentTerminationPayloadSchema } from '../../wizards/hr/employment-termination.wizard.contract'
import { sgkCompletedPayloadSchema } from '../../wizards/hr/sgk-entry.wizard.contract'

const emptyRequestSchema = z.object({}).passthrough()
const employeeIdPathSchema = z.object({ employee_id: uuidString })

export const employeeApiContracts = [
  {
    id: 'employees-list',
    endpointPath: '/api/v1/hr/employees',
    frontendPath: '/api/hr/employees',
    bffPath: '/api/hr/employees',
    fastApiPath: '/api/v1/hr/employees',
    method: 'GET',
    requestSchema: emptyRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employee.read'],
    backendAuthorization: ['hr.view'],
    backendResponseSchema: 'EmployeeListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id', 'organization_unit_id', 'position_id'], dateFields: [], datetimeFields: [], enumFields: ['employment_status', 'sgk_status'] },
    serviceFunction: 'employeesService.list',
  },
  {
    id: 'employee-reference-companies',
    endpointPath: '/api/v1/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: emptyRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['company.read'],
    backendAuthorization: ['companies.read'],
    backendResponseSchema: 'CompanyListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: ['status'] },
    serviceFunction: 'companyService.list',
  },
  {
    id: 'employee-reference-branches',
    endpointPath: '/api/v1/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: emptyRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['company.branch.read'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: ['status'] },
    serviceFunction: 'companyService.branchesList',
  },
  {
    id: 'employee-reference-organization-units',
    endpointPath: '/api/v1/organization/units',
    frontendPath: '/api/organization',
    bffPath: '/api/organization',
    fastApiPath: '/api/v1/organization/units',
    method: 'GET',
    requestSchema: emptyRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['organization.read'],
    backendAuthorization: ['organization.read'],
    backendResponseSchema: 'OrganizationListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: ['status'] },
    serviceFunction: 'organizationService.list',
  },
  {
    id: 'employees-summary',
    endpointPath: '/api/v1/hr/employees/summary',
    frontendPath: '/api/hr/employees/summary',
    bffPath: '/api/hr/employees/summary',
    fastApiPath: '/api/v1/hr/employees/summary',
    method: 'GET',
    requestSchema: emptyRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employee.read'],
    backendAuthorization: ['hr.view'],
    backendResponseSchema: 'EmployeeSummary',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'employeesService.summary',
  },
  {
    id: 'employees-detail',
    endpointPath: '/api/v1/hr/employees/{employee_id}',
    frontendPath: '/api/hr/employees/{employee_id}',
    bffPath: '/api/hr/employees/{employee_id}',
    fastApiPath: '/api/v1/hr/employees/{employee_id}',
    method: 'GET',
    requestSchema: employeeIdPathSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employee.read'],
    backendAuthorization: ['hr.view'],
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'employeesService.detail',
  },
  {
    id: 'employees-documents',
    endpointPath: '/api/v1/hr/employees/{employee_id}/documents',
    frontendPath: '/api/hr/employees/{employee_id}/documents',
    bffPath: '/api/hr/employees/{employee_id}/documents',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/documents',
    method: 'GET',
    requestSchema: employeeIdPathSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.documents.read'],
    backendAuthorization: ['hr.view'],
    backendResponseSchema: 'EmployeeDocumentResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'employeesService.documents',
  },
  {
    id: 'employees-create',
    endpointPath: '/api/v1/hr/employees',
    frontendPath: '/api/hr/employees',
    bffPath: '/api/hr/employees',
    fastApiPath: '/api/v1/hr/employees',
    method: 'POST',
    requestSchema: employeeCreateFormSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employee.create'],
    backendAuthorization: ['hr.employeeCreate'],
    backendRequestSchema: 'EmployeeCreateRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: ['gender'] },
    serviceFunction: 'employeesService.create',
  },
  {
    id: 'employees-update',
    endpointPath: '/api/v1/hr/employees/{employee_id}',
    frontendPath: '/api/hr/employees/{employee_id}',
    bffPath: '/api/hr/employees/{employee_id}',
    fastApiPath: '/api/v1/hr/employees/{employee_id}',
    method: 'PATCH',
    requestSchema: employeeCreateFormSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employee.update'],
    backendAuthorization: ['hr.edit'],
    backendRequestSchema: 'EmployeeUpdateRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: ['gender'] },
    serviceFunction: 'employeesService.update',
  },
  {
    id: 'employment-start',
    endpointPath: '/api/v1/hr/employees/{employee_id}/employment/start',
    frontendPath: '/api/hr/employees/{employee_id}/employment/start',
    bffPath: '/api/hr/employees/{employee_id}/employment/start',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/employment/start',
    method: 'POST',
    requestSchema: employmentStartPayloadSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employment.start'],
    backendAuthorization: ['hr.employmentStart'],
    backendRequestSchema: 'EmploymentStartRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id', 'company_id', 'branch_id', 'organization_unit_id', 'position_id', 'manager_employee_id'], dateFields: ['start_date', 'trial_period_end_date'], datetimeFields: ['base_updated_at'], enumFields: ['employment_type', 'sgk_status'] },
    serviceFunction: 'employmentService.start',
  },
  {
    id: 'employment-terminate',
    endpointPath: '/api/v1/hr/employees/{employee_id}/employment/terminate',
    frontendPath: '/api/hr/employees/{employee_id}/employment/terminate',
    bffPath: '/api/hr/employees/{employee_id}/employment/terminate',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/employment/terminate',
    method: 'POST',
    requestSchema: employmentTerminationPayloadSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.employment.terminate'],
    backendAuthorization: ['hr.employmentTerminate'],
    backendRequestSchema: 'EmploymentTerminateRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: ['end_date'], datetimeFields: ['base_updated_at'], enumFields: ['sgk_status'] },
    serviceFunction: 'employmentService.terminate',
  },
  {
    id: 'employment-assignment-change',
    endpointPath: '/api/v1/hr/employees/{employee_id}/employment/assignment-change',
    frontendPath: '/api/hr/employees/{employee_id}/employment/assignment-change',
    bffPath: '/api/hr/employees/{employee_id}/employment/assignment-change',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/employment/assignment-change',
    method: 'POST',
    requestSchema: assignmentChangePayloadSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.assignment.change'],
    backendAuthorization: ['hr.assignmentChange'],
    backendRequestSchema: 'AssignmentChangeRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id', 'branch_id', 'organization_unit_id', 'position_id'], dateFields: ['effective_date'], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'employmentService.assignmentChange',
  },
  {
    id: 'employment-sgk-entry-completed',
    endpointPath: '/api/v1/hr/employees/{employee_id}/sgk/entry-completed',
    frontendPath: '/api/hr/employees/{employee_id}/sgk/entry-completed',
    bffPath: '/api/hr/employees/{employee_id}/sgk/entry-completed',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/sgk/entry-completed',
    method: 'POST',
    requestSchema: sgkCompletedPayloadSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.sgk.manage'],
    backendAuthorization: ['hr.employmentStart'],
    backendRequestSchema: 'SgkCompletedRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: ['completed_date'], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'employmentService.sgkEntryCompleted',
  },
  {
    id: 'employment-sgk-exit-completed',
    endpointPath: '/api/v1/hr/employees/{employee_id}/sgk/exit-completed',
    frontendPath: '/api/hr/employees/{employee_id}/sgk/exit-completed',
    bffPath: '/api/hr/employees/{employee_id}/sgk/exit-completed',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/sgk/exit-completed',
    method: 'POST',
    requestSchema: sgkCompletedPayloadSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.sgk.manage'],
    backendAuthorization: ['hr.employmentTerminate'],
    backendRequestSchema: 'SgkCompletedRequest',
    backendResponseSchema: 'EmployeeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: ['completed_date'], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'employmentService.sgkExitCompleted',
  },
  {
    id: 'employee-document-create',
    endpointPath: '/api/v1/hr/employees/{employee_id}/documents',
    frontendPath: '/api/hr/employees/{employee_id}/documents',
    bffPath: '/api/hr/employees/{employee_id}/documents',
    fastApiPath: '/api/v1/hr/employees/{employee_id}/documents',
    method: 'POST',
    requestSchema: employeeDocumentFormSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['hr.documents.manage'],
    backendAuthorization: ['hr.documentsManage'],
    backendRequestSchema: 'EmployeeDocumentCreateRequest',
    backendResponseSchema: 'EmployeeDocumentResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'employee_id'], dateFields: ['issue_date', 'expiry_date'], datetimeFields: ['base_updated_at'], enumFields: ['document_type', 'status'] },
    serviceFunction: 'employeesService.createDocument',
  },
] as const satisfies readonly EdenApiContract[]

export const employeeApiServiceFunctions = employeeApiContracts.map(contract => contract.serviceFunction)
