export const HR_PERMISSIONS = {
  view: 'hr.view',
  edit: 'hr.edit',
  employeeCreate: 'hr.employeeCreate',
  employmentStart: 'hr.employmentStart',
  employmentTerminate: 'hr.employmentTerminate',
  assignmentChange: 'hr.assignmentChange',
  documentsManage: 'hr.documentsManage',
  leaveView: 'hr.leaveView',
  leaveRequestCreate: 'hr.leaveRequestCreate',
  leaveApprove: 'hr.leaveApprove',
  leaveAdmin: 'hr.leaveAdmin',
  attendanceView: 'hr.attendanceView',
  attendanceEdit: 'hr.attendanceEdit',
  timesheetView: 'hr.timesheetView',
  timesheetManage: 'hr.timesheetManage',
  timesheetApprove: 'hr.timesheetApprove',
  payrollPrepView: 'hr.payrollPrepView',
  payrollPrepManage: 'hr.payrollPrepManage',
  sensitiveView: 'hr.sensitiveView',
}
