export const CRM_PERMISSIONS = {
  view: 'crm.view',
  create: 'crm.create',
  edit: 'crm.edit',
  delete: 'crm.delete',
  interactionsManage: 'crm.interactionsManage',
  leadsManage: 'crm.leadsManage',
  leadsView: 'crm.leadsView',
  leadsEdit: 'crm.leadsEdit',
  leadsConvert: 'crm.leadsConvert',
  opportunitiesView: 'crm.opportunitiesView',
  opportunitiesEdit: 'crm.opportunitiesEdit',
  opportunityStageChange: 'crm.opportunityStageChange',
  opportunityWinLoss: 'crm.opportunityWinLoss',
  pipelineManage: 'crm.pipelineManage',
  followupManage: 'crm.followupManage',
  proposalManage: 'crm.proposalManage',
  createCariAccount: 'crm.createCariAccount',
  createTask: 'crm.createTask',
} as const
