import type { UserUiPreferences } from './types'

export const DEFAULT_UI_PREFERENCES: UserUiPreferences = {
  appearanceMode: 'system',
  theme: 'system',
  visualTheme: 'classic',
  accentColor: 'emerald',
  sidebarCollapsed: false,
  density: 'comfortable',
  language: 'tr',
  dateFormat: 'dd.MM.yyyy',
  timeFormat: '24h',
  defaultLandingPage: '/app',
  tablePreferences: {},
  dismissedHints: [],
  hasSeenGlobalTour: false,
  hasSeenFirstRunWelcome: false,
  completedTourSteps: [],
  completedPageTours: [],
  dismissedPageTours: [],
  dismissedOperationHints: [],
  preferredHelpMode: 'both',
  lastTourVersion: null,
  lastOnboardingVersion: null,
  helpLevel: 'guided',
  actionGuideIntroSeen: false,
  actionCenterIntroSeen: false,
  actionGuideDismissed: false,
  dismissedFieldHelpers: [],
  lockedFieldHintsDismissed: [],
}
