export const ACCOUNTING_PERMISSIONS = {
  accountingView: 'accounting.view',
  accountCardsView: 'account_cards.view',
  accountCardsViewMovements: 'account_cards.view_movements',
  accountCardsEditFinancialSettings: 'account_cards.edit_financial_settings',
  accountCardsReconcile: 'account_cards.reconcile',
  preAccountingView: 'preaccounting.view',
  preAccountingInsert: 'preaccounting.insert',
  preAccountingEdit: 'preaccounting.edit',
  preAccountingApprove: 'preaccounting.approve',
  preAccountingMatch: 'preaccounting.match',
  preAccountingCancel: 'preaccounting.cancel',
  bankConnectionsView: 'bank_connections.view',
  bankConnectionsEdit: 'bank_connections.edit',
  bankTransactionsView: 'bank_transactions.view',
  bankTransactionsEdit: 'bank_transactions.edit',
}
