import { PERMISSIONS } from '@/packages/shared/src'
import type { ProcessDefinition } from '../process.types'

export const companyBranchOpeningProcess: ProcessDefinition = {
  key: 'company_branch_opening_process',
  version: '1.0.0',
  moduleKey: 'branches',
  name: 'Sube Acilisi Sureci',
  description: 'Sube acilisi talebini, belge kontrolunu ve kritik sube acilisi operasyonunu yonetir.',
  entityType: 'company_branch',
  operationKey: 'branch_opening',
  startPermission: PERMISSIONS.branches.openingStart,
  fallbackPermission: PERMISSIONS.companies.edit,
  requiredModules: ['companies', 'branches'],
  steps: [
    {
      key: 'draft_request',
      name: 'Sube acilisi taslagi',
      description: 'Kullanici wizard ile sube acilisi bilgisini hazirlar.',
      type: 'form',
      required: true,
      order: 10,
      assigneeStrategy: 'initiator',
      nextOnComplete: 'document_check',
    },
    {
      key: 'document_check',
      name: 'Belge kontrolu',
      description: 'Resmi sube acilis belgeleri kontrol edilir.',
      type: 'review',
      required: false,
      order: 20,
      assigneeStrategy: 'permission',
      assigneePermission: PERMISSIONS.branches.documentsUpdate,
      dueInHours: 48,
      nextOnComplete: 'approval',
    },
    {
      key: 'approval',
      name: 'Sube acilisi onayi',
      description: 'Onay politikasi varsa surec onay bekler; yoksa otomatik ilerleyebilir.',
      type: 'approval',
      required: false,
      order: 30,
      assigneeStrategy: 'permission',
      assigneePermission: PERMISSIONS.branches.openingStart,
      nextOnComplete: 'execute_operation',
    },
    {
      key: 'execute_operation',
      name: 'Sube acilisini uygula',
      description: 'Company Branch Opening orchestrator kritik mutation islemini yapar.',
      type: 'operation',
      required: true,
      order: 40,
      assigneeStrategy: 'system',
      operationKey: 'branch_opening',
      nextOnComplete: 'completed',
    },
    {
      key: 'completed',
      name: 'Surec tamamlandi',
      type: 'system',
      required: true,
      order: 50,
      assigneeStrategy: 'system',
    },
  ],
  transitions: [
    { from: 'draft_request', to: 'document_check', action: 'complete', label: 'Taslagi tamamla' },
    { from: 'document_check', to: 'approval', action: 'complete', label: 'Belge kontrolunu tamamla' },
    { from: 'approval', to: 'execute_operation', action: 'approve', label: 'Onayla' },
    { from: 'execute_operation', to: 'completed', action: 'complete', label: 'Operasyonu tamamla' },
  ],
  cancelPolicy: {
    allowedStatuses: ['draft', 'active', 'waiting_approval'],
    permission: PERMISSIONS.branches.openingStart,
    fallbackPermission: PERMISSIONS.companies.edit,
  },
}

export const companyBranchClosingProcess: ProcessDefinition = {
  key: 'company_branch_closing_process',
  version: '1.0.0',
  moduleKey: 'branches',
  name: 'Sube Kapanisi Sureci',
  description: 'Sube kapanisi talebini, etki incelemesini, onayi ve kritik kapanis operasyonunu yonetir.',
  entityType: 'company_branch',
  operationKey: 'branch_closing',
  startPermission: PERMISSIONS.branches.closingStart,
  fallbackPermission: PERMISSIONS.companies.edit,
  requiredModules: ['companies', 'branches'],
  steps: [
    {
      key: 'draft_request',
      name: 'Sube kapanisi taslagi',
      description: 'Kullanici wizard ile kapanis gerekcesi ve aksiyonlarini hazirlar.',
      type: 'form',
      required: true,
      order: 10,
      assigneeStrategy: 'initiator',
      nextOnComplete: 'impact_review',
    },
    {
      key: 'impact_review',
      name: 'Etki incelemesi',
      description: 'Organizasyon, tesis, personel ve acik iliskiler kapanis etkisi acisindan incelenir.',
      type: 'review',
      required: true,
      order: 20,
      assigneeStrategy: 'permission',
      assigneePermission: PERMISSIONS.branches.closingStart,
      dueInHours: 48,
      nextOnComplete: 'approval',
    },
    {
      key: 'approval',
      name: 'Sube kapanisi onayi',
      description: 'Onay politikasi varsa surec onay bekler; yoksa otomatik ilerleyebilir.',
      type: 'approval',
      required: false,
      order: 30,
      assigneeStrategy: 'permission',
      assigneePermission: PERMISSIONS.branches.closingStart,
      nextOnComplete: 'execute_operation',
    },
    {
      key: 'execute_operation',
      name: 'Sube kapanisini uygula',
      description: 'Company Branch Closing orchestrator kritik mutation islemini yapar.',
      type: 'operation',
      required: true,
      order: 40,
      assigneeStrategy: 'system',
      operationKey: 'branch_closing',
      nextOnComplete: 'completed',
    },
    {
      key: 'completed',
      name: 'Surec tamamlandi',
      type: 'system',
      required: true,
      order: 50,
      assigneeStrategy: 'system',
    },
  ],
  transitions: [
    { from: 'draft_request', to: 'impact_review', action: 'complete', label: 'Taslagi tamamla' },
    { from: 'impact_review', to: 'approval', action: 'complete', label: 'Etki incelemesini tamamla' },
    { from: 'approval', to: 'execute_operation', action: 'approve', label: 'Onayla' },
    { from: 'execute_operation', to: 'completed', action: 'complete', label: 'Operasyonu tamamla' },
  ],
  cancelPolicy: {
    allowedStatuses: ['draft', 'active', 'waiting_approval'],
    permission: PERMISSIONS.branches.closingStart,
    fallbackPermission: PERMISSIONS.companies.edit,
  },
}

export const branchProcessDefinitions = [
  companyBranchOpeningProcess,
  companyBranchClosingProcess,
] satisfies ProcessDefinition[]
