import { projectManagementAreas } from './projectManagement.config'
import {
  getProjectHealth,
  isTaskOpen,
  isTaskOverdue,
} from './projectManagement.config'
import type {
  ProjectManagementCalendarEvent,
  ProjectManagementDashboardSummary,
  ProjectManagementEditableAreaKey,
  ProjectManagementEditableRecord,
  ProjectManagementProject,
  ProjectManagementSprint,
  ProjectManagementTask,
  ProjectManagementTimeLog,
  ProjectManagementWorkflow,
} from './projectManagement.types'

const now = '2026-05-19T09:00:00.000Z'

export const projectManagementProjectsMock: ProjectManagementProject[] = [
  {
    id: 'pm-project-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    customer_id: 'mock-customer-kuzey',
    customer_display_name: 'Kuzey Holding',
    code: 'PRJ-2026-001',
    name: 'Kuzey Holding ERP Kurulum Projesi',
    description: 'Çok şirketli Eden ERP kurulum, veri aktarımı ve eğitim projesi.',
    project_type: 'musteri_projesi',
    project_manager_id: 'mock-emp-001',
    project_manager_name: 'Ayşe Demir',
    team_names: ['Ayşe Demir', 'Mert Kaya', 'Can Özkan'],
    status: 'devam_ediyor',
    priority: 'yuksek',
    start_date: '2026-04-15',
    target_end_date: '2026-06-28',
    budget: 720000,
    currency: 'TRY',
    estimated_hours: 420,
    spent_hours: 168,
    completion_rate: 42,
    open_task_count: 5,
    overdue_task_count: 1,
    goals: 'İlk faz canlıya geçiş, satış sonrası varlık ve lisans takibi entegrasyonu.',
    scope: 'Şirket, muhasebe, ürün/hizmet, satış sonrası ve görev yönetimi süreçleri.',
    risks: 'Müşteri veri temizlik süreci gecikirse eğitim takvimi riskli hale gelir.',
    notes: 'Haftalık durum raporu müşteri proje sponsoruna iletilecek.',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-project-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'PRJ-2026-002',
    name: 'Ürün ve Hizmetler Katalog Genişletmesi',
    description: 'Lisans, garanti, bakım paketi ve müşterideki ürün takip modelini genişletme.',
    project_type: 'urun_gelistirme',
    project_manager_name: 'Can Özkan',
    team_names: ['Can Özkan', 'Selin Arslan'],
    status: 'riskli',
    priority: 'kritik',
    start_date: '2026-05-01',
    target_end_date: '2026-05-31',
    estimated_hours: 180,
    spent_hours: 112,
    completion_rate: 58,
    open_task_count: 4,
    overdue_task_count: 2,
    goals: 'Satış sonrası hizmetlerin katalog kayıtlarıyla daha sıkı bağlanması.',
    scope: 'Ürün kartları, lisans ürünleri, garanti şablonları ve bakım paketleri.',
    risks: 'Satış sonrası servis alanlarıyla veri eşleme kararları tamamlanmalı.',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-project-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    customer_id: 'mock-customer-mavi-deniz',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    code: 'PRJ-2026-003',
    name: 'POS Bakım ve Lisans Yenileme Dönemi',
    description: 'Müşterideki POS cihazlarının garanti, lisans ve bakım döneminin planlanması.',
    project_type: 'satis_sonrasi_hizmet',
    project_manager_name: 'Mert Kaya',
    team_names: ['Mert Kaya', 'Ece Yılmaz'],
    status: 'planlandi',
    priority: 'normal',
    start_date: '2026-05-27',
    target_end_date: '2026-06-14',
    estimated_hours: 72,
    spent_hours: 8,
    completion_rate: 12,
    open_task_count: 3,
    overdue_task_count: 0,
    goals: 'Garanti bitişleri ve bakım randevularını tek planda toplamak.',
    scope: 'Müşterideki ürünler, servis kayıtları, lisans yenileme ve saha bakım.',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const projectManagementSprintsMock: ProjectManagementSprint[] = [
  {
    id: 'pm-sprint-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    name: 'Kuzey Canlıya Geçiş Hazırlığı',
    goal: 'Veri aktarımı, teklif takip ve eğitim görevlerini aynı dönem içinde kapatmak.',
    start_date: '2026-05-13',
    end_date: '2026-05-26',
    status: 'aktif',
    total_task_count: 5,
    completed_task_count: 1,
    open_task_count: 4,
    overdue_task_count: 1,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-sprint-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-002',
    project_name: 'Ürün ve Hizmetler Katalog Genişletmesi',
    name: 'Katalog İlişki Modeli Sprinti',
    goal: 'Ürün kartı, müşterideki ürün ve servis kaydı bağını sadeleştirmek.',
    start_date: '2026-05-20',
    end_date: '2026-06-02',
    status: 'planlandi',
    total_task_count: 4,
    completed_task_count: 0,
    open_task_count: 4,
    overdue_task_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-sprint-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-003',
    project_name: 'POS Bakım ve Lisans Yenileme Dönemi',
    name: 'POS Saha Hazırlığı',
    goal: 'Bakım randevuları ve lisans yenileme listelerini oluşturmak.',
    start_date: '2026-05-01',
    end_date: '2026-05-12',
    status: 'tamamlandi',
    total_task_count: 3,
    completed_task_count: 3,
    open_task_count: 0,
    overdue_task_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const projectManagementTasksMock: ProjectManagementTask[] = [
  {
    id: 'pm-task-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-001',
    project_code: 'PRJ-2026-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    epic_name: 'Canlıya Geçiş',
    task_no: 'GV-2026-001',
    title: 'Kuzey Holding teklif kapsamını son kez gözden geçir',
    description: 'Satış fırsatından doğan teklif hazırlama görevinin kapsam ve fiyat uyumunu kontrol et.',
    task_type: 'satis_takip_gorevi',
    status: 'devam_ediyor',
    priority: 'kritik',
    assignee_id: 'mock-emp-001',
    assignee_name: 'Ayşe Demir',
    helper_names: ['Can Özkan'],
    reporter_id: 'mock-emp-010',
    reporter_name: 'İsmail ILGAR',
    customer_id: 'mock-customer-kuzey',
    customer_display_name: 'Kuzey Holding',
    related_entity_type: 'sales_quote',
    related_entity_id: 'quote-kuzey-2026-014',
    related_entity_label: 'Teklif TKL-2026-014',
    start_date: '2026-05-14',
    due_date: '2026-05-19',
    estimated_hours: 6,
    spent_hours: 3.5,
    sprint_id: 'pm-sprint-001',
    sprint_name: 'Kuzey Canlıya Geçiş Hazırlığı',
    backlog_order: null,
    board_order: 1,
    tags: ['teklif', 'musteri-projesi', 'kritik'],
    comment_count: 4,
    attachment_count: 2,
    subtask_count: 2,
    blocker_count: 0,
    internal_notes: 'Fiyat revizyonu finans onayından sonra müşteriye iletilecek.',
    customer_visible_notes: 'Teklif kapsamı güncelleniyor.',
    links: [
      {
        id: 'pm-link-001',
        source_task_id: 'pm-task-001',
        target_task_id: 'pm-task-004',
        target_task_no: 'GV-2026-004',
        target_title: 'Veri aktarımı örnek dosyalarını iste',
        link_type: 'same_customer_work',
        created_at: now,
      },
    ],
    history: [
      {
        id: 'pm-history-001',
        task_id: 'pm-task-001',
        event_type: 'status_changed',
        from_value: 'Yapılacak',
        to_value: 'Devam Ediyor',
        actor_name: 'Ayşe Demir',
        note: 'Görev Devam Ediyor durumuna taşındı.',
        created_at: '2026-05-18T10:10:00.000Z',
      },
    ],
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-13T09:40:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-001',
    project_code: 'PRJ-2026-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    epic_name: 'Eğitim',
    task_no: 'GV-2026-002',
    title: 'Muhasebe ekibi eğitim takvimini netleştir',
    description: 'Müşteri proje ekibiyle muhasebe eğitim günlerini kesinleştir.',
    task_type: 'toplanti_aksiyonu',
    status: 'yapilacak',
    priority: 'yuksek',
    assignee_name: 'Mert Kaya',
    helper_names: ['Ayşe Demir'],
    reporter_name: 'İsmail ILGAR',
    customer_id: 'mock-customer-kuzey',
    customer_display_name: 'Kuzey Holding',
    related_entity_type: 'customer',
    related_entity_id: 'mock-customer-kuzey',
    related_entity_label: 'Kuzey Holding müşteri kartı',
    start_date: '2026-05-20',
    due_date: '2026-05-23',
    estimated_hours: 2,
    spent_hours: 0,
    sprint_id: 'pm-sprint-001',
    sprint_name: 'Kuzey Canlıya Geçiş Hazırlığı',
    board_order: 2,
    tags: ['egitim', 'musteri'],
    comment_count: 1,
    attachment_count: 0,
    subtask_count: 0,
    blocker_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-15T08:30:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-002',
    project_code: 'PRJ-2026-002',
    project_name: 'Ürün ve Hizmetler Katalog Genişletmesi',
    epic_name: 'Satış Sonrası Entegrasyon',
    task_no: 'GV-2026-003',
    title: 'Garanti şablonlarını müşterideki ürün kayıtlarıyla eşle',
    description: 'Ürün ve Hizmetler modülündeki garanti şablonları ile müşteri varlıklarını bağlayan alanları doğrula.',
    task_type: 'is_paketi',
    status: 'incelemede',
    priority: 'kritik',
    assignee_name: 'Can Özkan',
    helper_names: ['Selin Arslan'],
    reporter_name: 'İsmail ILGAR',
    related_entity_type: 'product_service_item',
    related_entity_id: 'psi-product-001',
    related_entity_label: 'PlaneGuard Kamera Sistemi',
    start_date: '2026-05-08',
    due_date: '2026-05-17',
    estimated_hours: 12,
    spent_hours: 9,
    sprint_id: 'pm-sprint-002',
    sprint_name: 'Katalog İlişki Modeli Sprinti',
    board_order: 1,
    tags: ['urun', 'garanti', 'entegrasyon'],
    comment_count: 5,
    attachment_count: 1,
    subtask_count: 3,
    blocker_count: 1,
    internal_notes: 'Satış sonrası tablo alanlarıyla isimlendirme uyumu kontrol edilmeli.',
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-07T12:00:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-004',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-001',
    project_code: 'PRJ-2026-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    epic_name: 'Veri Aktarımı',
    task_no: 'GV-2026-004',
    title: 'Veri aktarımı örnek dosyalarını iste',
    description: 'Cari, şirket ve personel örnek dosyalarını müşteri ekiplerinden talep et.',
    task_type: 'dokuman_takip_gorevi',
    status: 'beklemede',
    priority: 'normal',
    assignee_name: 'Ece Yılmaz',
    reporter_name: 'Ayşe Demir',
    customer_id: 'mock-customer-kuzey',
    customer_display_name: 'Kuzey Holding',
    related_entity_type: 'document',
    related_entity_id: 'doc-kuzey-import-template',
    related_entity_label: 'Kuzey veri aktarım şablonları',
    start_date: '2026-05-13',
    due_date: '2026-05-18',
    estimated_hours: 3,
    spent_hours: 1,
    sprint_id: 'pm-sprint-001',
    sprint_name: 'Kuzey Canlıya Geçiş Hazırlığı',
    board_order: 1,
    tags: ['dokuman', 'veri-aktarimi'],
    comment_count: 2,
    attachment_count: 3,
    subtask_count: 0,
    blocker_count: 0,
    internal_notes: 'Müşteri dosyayı Cuma gününe kadar ileteceğini belirtti.',
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-12T15:20:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-005',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-003',
    project_code: 'PRJ-2026-003',
    project_name: 'POS Bakım ve Lisans Yenileme Dönemi',
    task_no: 'GV-2026-005',
    title: 'Mavi Deniz POS garanti bitiş kontrolü',
    description: 'Müşterideki ürün kaydında garanti bitişi yaklaşan POS cihazını kontrol et.',
    task_type: 'servis_gorevi',
    status: 'yeni',
    priority: 'acil',
    assignee_name: 'Mert Kaya',
    reporter_name: 'Ece Yılmaz',
    customer_id: 'mock-customer-mavi-deniz',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    related_entity_type: 'customer_asset',
    related_entity_id: 'asset-002',
    related_entity_label: 'MUR-2026-002 - EdenPOS X200',
    start_date: '2026-05-19',
    due_date: '2026-05-19',
    estimated_hours: 2,
    spent_hours: 0,
    sprint_id: null,
    sprint_name: null,
    backlog_order: 1,
    board_order: 1,
    tags: ['garanti', 'pos', 'servis'],
    comment_count: 0,
    attachment_count: 0,
    subtask_count: 0,
    blocker_count: 0,
    customer_visible_notes: 'Garanti bitişi için kontrol planlandı.',
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-19T07:45:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-006',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-002',
    project_code: 'PRJ-2026-002',
    project_name: 'Ürün ve Hizmetler Katalog Genişletmesi',
    task_no: 'GV-2026-006',
    title: 'Lisans yenileme görev tipini backlog’a ekle',
    description: 'Lisans takip kayıtlarından otomatik görev üretimine uygun alanları belirle.',
    task_type: 'talep',
    status: 'yeni',
    priority: 'normal',
    assignee_name: 'Selin Arslan',
    reporter_name: 'Can Özkan',
    related_entity_type: 'product_service_item',
    related_entity_label: 'Eden ERP Enterprise',
    start_date: '2026-05-21',
    due_date: '2026-05-28',
    estimated_hours: 5,
    spent_hours: 0,
    sprint_id: null,
    sprint_name: null,
    backlog_order: 2,
    board_order: 2,
    tags: ['lisans', 'backlog'],
    comment_count: 1,
    attachment_count: 0,
    subtask_count: 0,
    blocker_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-16T11:10:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-007',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    task_no: 'GV-2026-007',
    title: 'KOSGEB proje başvuru evraklarını kontrol et',
    description: 'Şirket ve doküman yönetimi kayıtlarıyla ilişkili başvuru evraklarının son halini doğrula.',
    task_type: 'onay_gorevi',
    status: 'yapilacak',
    priority: 'yuksek',
    assignee_name: 'Ayşe Demir',
    reporter_name: 'İsmail ILGAR',
    related_entity_type: 'document',
    related_entity_id: 'doc-kosgeb-2026',
    related_entity_label: 'KOSGEB 2026 başvuru klasörü',
    start_date: '2026-05-20',
    due_date: '2026-05-24',
    estimated_hours: 4,
    spent_hours: 0,
    sprint_id: null,
    sprint_name: null,
    backlog_order: 3,
    board_order: 3,
    tags: ['kosgeb', 'dokuman', 'onay'],
    comment_count: 2,
    attachment_count: 4,
    subtask_count: 1,
    blocker_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-18T13:30:00.000Z',
    updated_at: now,
  },
  {
    id: 'pm-task-008',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    project_id: 'pm-project-001',
    project_code: 'PRJ-2026-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    task_no: 'GV-2026-008',
    title: 'Kurulum sonrası ilk kontrol listesini kapat',
    description: 'Canlıya geçiş öncesi kontrol listesini tamamla.',
    task_type: 'gorev',
    status: 'tamamlandi',
    priority: 'normal',
    assignee_name: 'Can Özkan',
    reporter_name: 'Ayşe Demir',
    customer_display_name: 'Kuzey Holding',
    related_entity_type: 'after_sales_record',
    related_entity_label: 'Servis kontrol SRV-2026-091',
    start_date: '2026-05-10',
    due_date: '2026-05-16',
    completed_at: '2026-05-16',
    estimated_hours: 3,
    spent_hours: 2.5,
    sprint_id: 'pm-sprint-001',
    sprint_name: 'Kuzey Canlıya Geçiş Hazırlığı',
    board_order: 10,
    tags: ['kontrol', 'kurulum'],
    comment_count: 1,
    attachment_count: 1,
    subtask_count: 0,
    blocker_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: '2026-05-09T10:00:00.000Z',
    updated_at: now,
  },
]

export const projectManagementTimeLogsMock: ProjectManagementTimeLog[] = [
  {
    id: 'pm-log-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    task_id: 'pm-task-001',
    task_no: 'GV-2026-001',
    task_title: 'Kuzey Holding teklif kapsamını son kez gözden geçir',
    project_id: 'pm-project-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    user_id: 'mock-emp-001',
    user_name: 'Ayşe Demir',
    work_date: '2026-05-19',
    start_time: '09:00',
    end_time: '11:30',
    duration_minutes: 150,
    description: 'Teklif kapsam ve fiyat kalemleri kontrol edildi.',
    is_billable: true,
    is_customer_visible: true,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-log-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    task_id: 'pm-task-003',
    task_no: 'GV-2026-003',
    task_title: 'Garanti şablonlarını müşterideki ürün kayıtlarıyla eşle',
    project_id: 'pm-project-002',
    project_name: 'Ürün ve Hizmetler Katalog Genişletmesi',
    user_id: 'mock-emp-003',
    user_name: 'Can Özkan',
    work_date: '2026-05-18',
    start_time: '14:00',
    end_time: '17:00',
    duration_minutes: 180,
    description: 'Veri modeli ve tablo ilişkileri incelendi.',
    is_billable: false,
    is_customer_visible: false,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-log-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    task_id: 'pm-task-004',
    task_no: 'GV-2026-004',
    task_title: 'Veri aktarımı örnek dosyalarını iste',
    project_id: 'pm-project-001',
    project_name: 'Kuzey Holding ERP Kurulum Projesi',
    user_id: 'mock-emp-004',
    user_name: 'Ece Yılmaz',
    work_date: '2026-05-17',
    duration_minutes: 60,
    description: 'Müşteri ekiplerine doküman listesi iletildi.',
    is_billable: true,
    is_customer_visible: true,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const projectManagementWorkflowsMock: ProjectManagementWorkflow[] = [
  {
    id: 'pm-workflow-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    name: 'Eden Varsayılan Görev Workflow',
    description: 'İlk faz için basit görev yaşam döngüsü.',
    applicable_project_type: 'all',
    statuses: ['yeni', 'yapilacak', 'devam_ediyor', 'beklemede', 'incelemede', 'tamamlandi', 'iptal_edildi'],
    transitions: [
      { id: 'tr-001', from_status: 'yeni', to_status: 'yapilacak', allowed_roles: ['Görev sahibi', 'Proje yöneticisi'] },
      { id: 'tr-002', from_status: 'yapilacak', to_status: 'devam_ediyor', allowed_roles: ['Sorumlu', 'Proje yöneticisi'] },
      { id: 'tr-003', from_status: 'devam_ediyor', to_status: 'incelemede', allowed_roles: ['Sorumlu'], require_description: true },
      { id: 'tr-004', from_status: 'incelemede', to_status: 'tamamlandi', allowed_roles: ['Proje yöneticisi'], require_closing_note: true },
      { id: 'tr-005', from_status: 'devam_ediyor', to_status: 'beklemede', allowed_roles: ['Sorumlu', 'Proje yöneticisi'], require_description: true },
      { id: 'tr-006', from_status: 'beklemede', to_status: 'devam_ediyor', allowed_roles: ['Sorumlu', 'Proje yöneticisi'] },
    ],
    initial_status: 'yeni',
    closing_status: 'tamamlandi',
    is_active: true,
    requires_approval_count: 1,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'pm-workflow-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    name: 'Servis Görevi Workflow',
    description: 'Satış sonrası servis ve garanti kontrol görevleri için hafif workflow.',
    applicable_project_type: 'satis_sonrasi_hizmet',
    statuses: ['yeni', 'yapilacak', 'devam_ediyor', 'beklemede', 'tamamlandi', 'iptal_edildi'],
    transitions: [
      { id: 'tr-srv-001', from_status: 'yeni', to_status: 'yapilacak', allowed_roles: ['Servis sorumlusu'] },
      { id: 'tr-srv-002', from_status: 'yapilacak', to_status: 'devam_ediyor', allowed_roles: ['Servis sorumlusu'] },
      { id: 'tr-srv-003', from_status: 'devam_ediyor', to_status: 'tamamlandi', allowed_roles: ['Servis yöneticisi'], require_attachment: true, require_closing_note: true },
    ],
    initial_status: 'yeni',
    closing_status: 'tamamlandi',
    is_active: true,
    requires_approval_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export function getProjectManagementRecordsByArea(areaKey: ProjectManagementEditableAreaKey): ProjectManagementEditableRecord[] {
  if (areaKey === 'gorevler') return projectManagementTasksMock
  if (areaKey === 'projeler') return projectManagementProjectsMock
  if (areaKey === 'sprintler') return projectManagementSprintsMock
  if (areaKey === 'zaman-takibi') return projectManagementTimeLogsMock
  return projectManagementWorkflowsMock
}

export function createProjectManagementRecordSeed(areaKey: ProjectManagementEditableAreaKey): ProjectManagementEditableRecord {
  if (areaKey === 'gorevler') {
    return {
      id: `draft-task-${Date.now()}`,
      company_name: 'Eden Teknoloji',
      task_no: 'GV-YENI',
      title: '',
      description: '',
      task_type: 'gorev',
      status: 'yeni',
      priority: 'normal',
      assignee_name: '',
      helper_names: [],
      reporter_name: 'İsmail ILGAR',
      customer_display_name: '',
      related_entity_type: 'company',
      related_entity_label: '',
      start_date: '',
      due_date: '',
      estimated_hours: 0,
      spent_hours: 0,
      sprint_id: null,
      sprint_name: null,
      backlog_order: 999,
      board_order: 999,
      tags: [],
      comment_count: 0,
      attachment_count: 0,
      subtask_count: 0,
      blocker_count: 0,
      record_status: 'active',
      is_deleted: false,
      created_at: now,
      updated_at: now,
    }
  }

  if (areaKey === 'projeler') {
    return {
      id: `draft-project-${Date.now()}`,
      company_name: 'Eden Teknoloji',
      code: 'PRJ-YENI',
      name: '',
      description: '',
      project_type: 'sirket_ici',
      project_manager_name: '',
      team_names: [],
      status: 'taslak',
      priority: 'normal',
      start_date: '',
      target_end_date: '',
      budget: 0,
      currency: 'TRY',
      estimated_hours: 0,
      spent_hours: 0,
      completion_rate: 0,
      open_task_count: 0,
      overdue_task_count: 0,
      goals: '',
      scope: '',
      risks: '',
      notes: '',
      record_status: 'active',
      is_deleted: false,
      created_at: now,
      updated_at: now,
    }
  }

  if (areaKey === 'sprintler') {
    return {
      id: `draft-sprint-${Date.now()}`,
      company_name: 'Eden Teknoloji',
      project_name: '',
      name: '',
      goal: '',
      start_date: '',
      end_date: '',
      status: 'planlandi',
      total_task_count: 0,
      completed_task_count: 0,
      open_task_count: 0,
      overdue_task_count: 0,
      record_status: 'active',
      is_deleted: false,
      created_at: now,
      updated_at: now,
    }
  }

  if (areaKey === 'zaman-takibi') {
    return {
      id: `draft-time-log-${Date.now()}`,
      company_name: 'Eden Teknoloji',
      task_id: '',
      task_no: '',
      task_title: '',
      project_name: '',
      user_id: 'mock-current-user',
      user_name: 'İsmail ILGAR',
      work_date: '2026-05-19',
      start_time: '',
      end_time: '',
      duration_minutes: 0,
      description: '',
      is_billable: false,
      is_customer_visible: false,
      record_status: 'active',
      is_deleted: false,
      created_at: now,
      updated_at: now,
    }
  }

  return {
    id: `draft-workflow-${Date.now()}`,
    company_name: 'Eden Teknoloji',
    name: '',
    description: '',
    applicable_project_type: 'all',
    statuses: ['yeni', 'yapilacak', 'devam_ediyor', 'incelemede', 'tamamlandi'],
    transitions: [],
    initial_status: 'yeni',
    closing_status: 'tamamlandi',
    is_active: true,
    requires_approval_count: 0,
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  }
}

export function getProjectManagementDashboardSummaries(): ProjectManagementDashboardSummary[] {
  const tasks = projectManagementTasksMock.filter(task => !task.is_deleted)
  const projects = projectManagementProjectsMock.filter(project => !project.is_deleted)
  const backlogTasks = tasks.filter(task => !task.sprint_id && isTaskOpen(task))
  const activeSprints = projectManagementSprintsMock.filter(sprint => sprint.status === 'aktif' && !sprint.is_deleted)
  const warningTasks = tasks.filter(task => isTaskOverdue(task) || ['kritik', 'acil'].includes(task.priority))
  const riskProjects = projects.filter(project => getProjectHealth(project) === 'warning')
  const totalMinutes = projectManagementTimeLogsMock
    .filter(log => !log.is_deleted)
    .reduce((sum, log) => sum + log.duration_minutes, 0)

  return projectManagementAreas.map(area => {
    if (area.key === 'gorevler') return { area, totalCount: tasks.length, openCount: tasks.filter(isTaskOpen).length, warningCount: warningTasks.length }
    if (area.key === 'projeler') return { area, totalCount: projects.length, openCount: projects.filter(project => !['tamamlandi', 'iptal_edildi', 'arsivlendi'].includes(project.status)).length, warningCount: riskProjects.length }
    if (area.key === 'kanban-board') return { area, totalCount: tasks.length, openCount: tasks.filter(isTaskOpen).length, warningCount: warningTasks.length }
    if (area.key === 'backlog') return { area, totalCount: backlogTasks.length, openCount: backlogTasks.length, warningCount: backlogTasks.filter(task => ['kritik', 'acil'].includes(task.priority)).length }
    if (area.key === 'sprintler') return { area, totalCount: projectManagementSprintsMock.length, openCount: activeSprints.length, warningCount: activeSprints.reduce((sum, sprint) => sum + sprint.overdue_task_count, 0) }
    if (area.key === 'takvim') return { area, totalCount: getProjectManagementCalendarEvents().length, openCount: tasks.filter(task => task.due_date).length, warningCount: tasks.filter(task => isTaskOverdue(task)).length }
    if (area.key === 'zaman-takibi') return { area, totalCount: projectManagementTimeLogsMock.length, openCount: Math.round(totalMinutes / 60), warningCount: projectManagementTimeLogsMock.filter(log => log.is_billable).length }
    if (area.key === 'is-akislari') return { area, totalCount: projectManagementWorkflowsMock.length, openCount: projectManagementWorkflowsMock.filter(workflow => workflow.is_active).length, warningCount: projectManagementWorkflowsMock.reduce((sum, workflow) => sum + workflow.requires_approval_count, 0) }
    return { area, totalCount: tasks.length + projects.length, openCount: tasks.filter(isTaskOpen).length, warningCount: warningTasks.length + riskProjects.length }
  })
}

export function getProjectManagementCalendarEvents(): ProjectManagementCalendarEvent[] {
  const taskEvents = projectManagementTasksMock
    .filter(task => task.due_date && !task.is_deleted)
    .map(task => ({
      id: `task-due-${task.id}`,
      title: task.title,
      date: task.due_date || '',
      kind: 'task_due' as const,
      priority: task.priority,
      status: task.status,
      project_name: task.project_name,
      company_name: task.company_name,
      customer_display_name: task.customer_display_name,
      assignee_name: task.assignee_name,
    }))

  const projectEvents = projectManagementProjectsMock.flatMap(project => {
    const events: ProjectManagementCalendarEvent[] = []
    if (project.start_date) {
      events.push({
        id: `project-start-${project.id}`,
        title: `${project.name} başlangıç`,
        date: project.start_date,
        kind: 'project_start',
        priority: project.priority,
        status: project.status,
        project_name: project.name,
        company_name: project.company_name,
        customer_display_name: project.customer_display_name,
        assignee_name: project.project_manager_name,
      })
    }
    if (project.target_end_date) {
      events.push({
        id: `project-end-${project.id}`,
        title: `${project.name} hedef bitiş`,
        date: project.target_end_date,
        kind: 'project_end',
        priority: project.priority,
        status: project.status,
        project_name: project.name,
        company_name: project.company_name,
        customer_display_name: project.customer_display_name,
        assignee_name: project.project_manager_name,
      })
    }
    return events
  })

  const sprintEvents = projectManagementSprintsMock.flatMap(sprint => [
    {
      id: `sprint-start-${sprint.id}`,
      title: `${sprint.name} başlangıç`,
      date: sprint.start_date,
      kind: 'sprint_start' as const,
      status: sprint.status,
      project_name: sprint.project_name,
      company_name: sprint.company_name,
    },
    {
      id: `sprint-end-${sprint.id}`,
      title: `${sprint.name} bitiş`,
      date: sprint.end_date,
      kind: 'sprint_end' as const,
      status: sprint.status,
      project_name: sprint.project_name,
      company_name: sprint.company_name,
    },
  ])

  return [...taskEvents, ...projectEvents, ...sprintEvents].sort((a, b) => a.date.localeCompare(b.date))
}

export function buildTaskNo(rows: ProjectManagementTask[]) {
  const year = new Date().getFullYear()
  const count = rows.filter(row => row.task_no.startsWith(`GV-${year}`)).length + 1
  return `GV-${year}-${String(count).padStart(3, '0')}`
}

export function buildProjectCode(rows: ProjectManagementProject[]) {
  const year = new Date().getFullYear()
  const count = rows.filter(row => row.code.startsWith(`PRJ-${year}`)).length + 1
  return `PRJ-${year}-${String(count).padStart(3, '0')}`
}
