import type { EdenPageContract } from '../core/page.contract'
import { branchEntityContract } from '../entities/branch.contract'

export const branchPageContract = {
  route: '/app/sirket/companies/branches',
  pageKind: 'list',
  owningEntity: branchEntityContract.entityName,
  allowedActions: ['open_lifecycle_wizard', 'edit_master_data'],
  requiredComponents: ['PageBanner', 'SmartDataTable', 'EntityForm', 'CompanyBranchOpeningWizard', 'CompanyBranchClosingWizard'],
  requiredStates: { empty: true, loading: true, error: true },
  releaseStatus: 'preview',
  visibleInProduction: false,
  visibleInStaging: true,
  visibleInDevelopment: true,
  debugStatusBadgeAllowed: false,
  list: {
    primaryActionLabel: 'Yeni Şube Aç',
    primaryActionBehavior: 'open_lifecycle_wizard',
    emptyState: { title: 'Henuz sube kaydi yok', message: 'Sube acmak icin aktif bir sirket kartindan lifecycle wizard baslatin.' },
    columns: [
      { key: 'record_status', label: 'Durum' },
      { key: 'branch_name', label: 'Sube Adi', searchable: true },
      { key: 'branch_short_name', label: 'Sube Kisa Adi', searchable: true },
      { key: 'company_name', label: 'Bagli Sirket', searchable: true },
      { key: 'branch_type', label: 'Sube Turu', filterable: true },
      { key: 'is_official_branch', label: 'Resmi Sube mi?' },
      { key: 'city', label: 'Il', filterable: true },
      { key: 'district', label: 'Ilce' },
      { key: 'address_summary', label: 'Adres Ozeti' },
      { key: 'phone', label: 'Telefon' },
      { key: 'email', label: 'E-posta' },
      { key: 'responsible_person_id', label: 'Sube Sorumlusu / Muduru' },
      { key: 'opening_registration_date', label: 'Acilis Tarihi', sortable: true },
      { key: 'closing_registration_date', label: 'Kapanis Tarihi', sortable: true },
      { key: 'trade_registry_number', label: 'Ticaret Sicil No' },
      { key: 'tax_office', label: 'Vergi Dairesi' },
      { key: 'sgk_workplace_registry_no', label: 'SGK Isyeri Sicil No' },
      { key: 'organization_unit_name', label: 'Bagli Organizasyon Birimi' },
      { key: 'facility_name', label: 'Bagli Lokasyon/Tesis' },
      { key: 'active_authority_count', label: 'Aktif Yetkili' },
      { key: 'last_operation', label: 'Son Islem' },
      { key: 'warnings_summary', label: 'Uyarilar' },
      { key: 'actions', label: 'Islemler' },
    ],
    sortableFields: ['branch_name', 'company_name', 'opening_registration_date', 'closing_registration_date'],
    filterableFields: ['record_status', 'branch_type', 'city', 'is_official_branch'],
    searchableFields: ['branch_name', 'company_name', 'city', 'district'],
    rowActions: ['view', 'edit', 'branch_closing', 'branch_documents_update'],
    bulkActions: [],
  },
  form: {
    fields: [
      { name: 'company_id', kind: 'string', label: 'Bagli Sirket', required: true },
      { name: 'branch_name', kind: 'string', label: 'Sube Adi', required: true },
      { name: 'branch_short_name', kind: 'string', label: 'Sube Kisa Adi', optional: true },
      { name: 'branch_type', kind: 'string', label: 'Sube Turu', required: true },
      { name: 'is_official_branch', kind: 'boolean', label: 'Resmi Sube mi?', optional: true },
      { name: 'city', kind: 'string', label: 'Il', required: true },
      { name: 'district', kind: 'string', label: 'Ilce', optional: true },
      { name: 'address_summary', kind: 'string', label: 'Adres Ozeti', optional: true },
      { name: 'phone', kind: 'string', label: 'Telefon', optional: true },
      { name: 'email', kind: 'string', label: 'E-posta', optional: true },
      { name: 'opening_registration_date', kind: 'date', label: 'Acilis Tarihi', optional: true },
    ],
    fieldOrder: ['company_id', 'branch_name', 'branch_short_name', 'branch_type', 'is_official_branch', 'city', 'district', 'address_summary', 'phone', 'email', 'opening_registration_date'],
    defaultValues: {},
    readonlyFields: [],
    hiddenFields: [],
    submitBehavior: 'update_master_data',
    cancelBehavior: 'return_to_list',
    draftSaveBehavior: 'update_draft',
    forbiddenBehaviors: ['lifecycle_transaction'],
  },
} as const satisfies EdenPageContract
