import type { EdenPageContract } from '../core/page.contract'
import { companyEntityContract } from '../entities/company.contract'

export const companyPageContract = {
  route: '/app/sirket/companies',
  pageKind: 'list',
  owningEntity: companyEntityContract.entityName,
  allowedActions: ['create_draft', 'edit_master_data', 'open_lifecycle_wizard'],
  requiredComponents: ['PageBanner', 'SmartDataTable', 'EntityForm', 'CompanyLifecycleWizard'],
  requiredStates: { empty: true, loading: true, error: true },
  releaseStatus: 'live',
  visibleInProduction: true,
  visibleInStaging: true,
  visibleInDevelopment: true,
  debugStatusBadgeAllowed: false,
  list: {
    primaryActionLabel: 'Ekle',
    primaryActionBehavior: 'open_draft_form',
    emptyState: {
      title: 'Henuz sirket kaydi yok',
      message: 'Sirket kaydi olusturmak icin Ekle aksiyonunu kullanin.',
    },
    columns: [
      { key: 'lifecycle_status', label: 'Durum' },
      { key: 'logo_url', label: 'Logo' },
      { key: 'short_name', label: 'Kisa Unvan', sortable: true, searchable: true },
      { key: 'trade_name', label: 'Ticari Unvan', sortable: true, searchable: true },
      { key: 'tax_number', label: 'VKN', sortable: true, searchable: true },
      { key: 'tax_office', label: 'Vergi Dairesi', sortable: true, filterable: true },
      { key: 'company_type', label: 'Sirket Turu', sortable: true, filterable: true },
      { key: 'adres_ozet', label: 'Adres', searchable: true },
      { key: 'phone', label: 'Telefon', searchable: true },
      { key: 'email', label: 'E-posta', searchable: true },
      { key: 'mersis_number', label: 'MERSIS No', sortable: true, visible: false },
      { key: 'trade_registry_number', label: 'Ticaret Sicil No', sortable: true, visible: false },
      { key: 'foundation_date', label: 'Kurulus Tarihi', sortable: true, visible: false },
      { key: 'electronic_notification_address', label: 'Elektronik Tebligat Adresi', visible: false },
      { key: 'trade_registry_office', label: 'Ticaret Sicili Mudurlugu', visible: false },
      { key: 'company_code', label: 'Sirket Kodu', sortable: true, visible: false },
      { key: 'country', label: 'Ulke', sortable: true, visible: false },
      { key: 'city', label: 'Il', sortable: true, visible: false },
      { key: 'district', label: 'Ilce', sortable: true, visible: false },
      { key: 'address', label: 'Adres', visible: false },
      { key: 'website', label: 'Web Sitesi', visible: false },
      { key: 'e_invoice_taxpayer', label: 'E-Fatura Mukellefi', sortable: true, visible: false },
      { key: 'e_archive_taxpayer', label: 'E-Arsiv Mukellefi', sortable: true, visible: false },
      { key: 'e_waybill_taxpayer', label: 'E-Irsaliye Mukellefi', sortable: true, visible: false },
      { key: 'sgk_workplace_registry_no', label: 'SGK Isyeri Sicil No', sortable: true, visible: false },
      { key: 'sgk_province', label: 'SGK Il', sortable: true, visible: false },
      { key: 'sgk_branch', label: 'SGK Sube', sortable: true, visible: false },
      { key: 'risk_class', label: 'Tehlike Sinifi', sortable: true, visible: false },
      { key: 'default_currency', label: 'Varsayilan Para Birimi', sortable: true, visible: false },
      { key: 'default_language', label: 'Varsayilan Dil', sortable: true, visible: false },
      { key: 'time_zone', label: 'Zaman Dilimi', sortable: true, visible: false },
      { key: 'fiscal_year_start', label: 'Mali Yil Baslangici', sortable: true, visible: false },
    ],
    sortableFields: ['short_name', 'trade_name', 'tax_number', 'tax_office', 'company_type'],
    filterableFields: ['record_status', 'company_type', 'tax_office'],
    searchableFields: ['short_name', 'trade_name', 'tax_number', 'email', 'phone'],
    rowActions: ['view', 'edit', 'lifecycle'],
    bulkActions: [],
  },
} as const satisfies EdenPageContract
