import type { EdenPageContract } from '../core/page.contract'
import { partnerEntityContract } from '../entities/partner.contract'

export const partnerPageContract = {
  route: '/app/sirket/companies/partners',
  pageKind: 'list',
  owningEntity: partnerEntityContract.entityName,
  allowedActions: ['create_draft', 'edit_master_data', 'open_lifecycle_wizard'],
  requiredComponents: ['PageBanner', 'SmartDataTable', 'EntityForm', 'RecordLifecycleWizard'],
  requiredStates: { empty: true, loading: true, error: true },
  releaseStatus: 'live',
  visibleInProduction: true,
  visibleInStaging: true,
  visibleInDevelopment: true,
  debugStatusBadgeAllowed: false,
  list: {
    primaryActionLabel: 'Ekle',
    primaryActionBehavior: 'open_draft_form',
    emptyState: { title: 'Henuz ortak yok', message: 'Ortak karti olusturmak icin Ekle aksiyonunu kullanin.' },
    columns: [
      { key: 'record_status', label: 'Durum' },
      { key: 'avatar', label: 'Avatar' },
      { key: 'display_name', label: 'Adi / Unvani', searchable: true },
      { key: 'partner_type_label', label: 'Turu', filterable: true },
      { key: 'company_name', label: 'Sirket', searchable: true },
      { key: 'current_share_ratio', label: 'Hisse %', sortable: true },
      { key: 'current_voting_ratio', label: 'Oy %', sortable: true },
      { key: 'current_profit_ratio', label: 'Kar Payi %', sortable: true },
      { key: 'current_capital_amount', label: 'Taahhut Edilen Sermaye', sortable: true },
      { key: 'current_share_units', label: 'Pay Adedi', sortable: true },
      { key: 'ownership_flags', label: 'Imtiyaz / Kontrol' },
      { key: 'last_ownership_transaction', label: 'Son Islem' },
      { key: 'start_date', label: 'Baslangic', sortable: true },
      { key: 'end_date', label: 'Bitis', sortable: true },
    ],
    sortableFields: ['display_name', 'current_share_ratio', 'current_capital_amount', 'start_date', 'end_date'],
    filterableFields: ['record_status', 'partner_type_label', 'company_id'],
    searchableFields: ['display_name', 'company_name', 'identity_number'],
    rowActions: ['view', 'edit', 'lifecycle'],
    bulkActions: [],
  },
  form: {
    fields: [
      { name: 'company_id', kind: 'string', label: 'Sirket', required: true },
      { name: 'partner_type', kind: 'string', label: 'Ortak Turu', required: true },
      { name: 'display_name', kind: 'string', label: 'Adi / Unvani', required: true },
      { name: 'identity_number', kind: 'string', label: 'TCKN / VKN', optional: true },
      { name: 'current_share_ratio', kind: 'number', label: 'Hisse Orani', optional: true },
      { name: 'current_voting_ratio', kind: 'number', label: 'Oy Orani', optional: true },
      { name: 'current_profit_ratio', kind: 'number', label: 'Kar Payi Orani', optional: true },
      { name: 'current_capital_amount', kind: 'number', label: 'Sermaye Tutari', optional: true },
      { name: 'start_date', kind: 'date', label: 'Baslangic Tarihi', optional: true },
      { name: 'end_date', kind: 'date', label: 'Bitis Tarihi', optional: true },
    ],
    fieldOrder: ['company_id', 'partner_type', 'display_name', 'identity_number', 'current_share_ratio', 'current_voting_ratio', 'current_profit_ratio', 'current_capital_amount', 'start_date', 'end_date'],
    defaultValues: {},
    readonlyFields: [],
    hiddenFields: [],
    submitBehavior: 'update_master_data',
    cancelBehavior: 'return_to_list',
    draftSaveBehavior: 'update_draft',
    forbiddenBehaviors: ['lifecycle_transaction'],
  },
} as const satisfies EdenPageContract
