import type { EdenPageContract } from '../core/page.contract'
import { representativeEntityContract } from '../entities/representative.contract'

export const representativePageContract = {
  route: '/app/sirket/companies/representatives',
  pageKind: 'list',
  owningEntity: representativeEntityContract.entityName,
  allowedActions: ['create_draft', 'edit_master_data', 'open_lifecycle_wizard'],
  requiredComponents: ['PageBanner', 'SmartDataTable', 'EntityForm', 'RecordLifecycleWizard'],
  requiredStates: { empty: true, loading: true, error: true },
  releaseStatus: 'live',
  visibleInProduction: true,
  visibleInStaging: true,
  visibleInDevelopment: true,
  debugStatusBadgeAllowed: false,
  list: {
    primaryActionLabel: 'Ekle',
    primaryActionBehavior: 'open_draft_form',
    emptyState: { title: 'Henuz temsilci yok', message: 'Temsilci karti olusturmak icin Ekle aksiyonunu kullanin.' },
    columns: [
      { key: 'record_status', label: 'Durum' },
      { key: 'avatar', label: 'Avatar' },
      { key: 'display_name', label: 'Ad Soyad / Unvan', searchable: true },
      { key: 'company_name', label: 'Temsil Ettigi Sirket', searchable: true },
      { key: 'representative_type_label', label: 'Temsilci Tipi', filterable: true },
      { key: 'person_kind_label', label: 'Kisi / Kurum Tipi', filterable: true },
      { key: 'source_type_label', label: 'Kaynak Turu', filterable: true },
      { key: 'primary_authority_type', label: 'Ana Yetki Tipi', filterable: true },
      { key: 'authority_types_summary', label: 'Yetki Turleri' },
      { key: 'signature_type_label', label: 'Imza Turu' },
      { key: 'signature_rule_summary', label: 'Imza Kurali' },
      { key: 'authority_status_label', label: 'Yetki Durumu', filterable: true },
      { key: 'scope_label', label: 'Yetki Kapsami' },
      { key: 'branch_name', label: 'Sube' },
      { key: 'organization_unit_name', label: 'Organizasyon Birimi' },
      { key: 'facility_name', label: 'Tesis/Lokasyon' },
      { key: 'authority_start_date', label: 'Yururluk Baslangici', sortable: true },
      { key: 'authority_end_date', label: 'Yururluk Bitisi', sortable: true },
      { key: 'limit_summary', label: 'Limit Ozeti' },
      { key: 'currency', label: 'Para Birimi' },
      { key: 'last_operation_label', label: 'Son Islem' },
      { key: 'warnings_summary', label: 'Uyarilar' },
    ],
    sortableFields: ['display_name', 'company_name', 'authority_start_date', 'authority_end_date'],
    filterableFields: ['record_status', 'authority_status_label', 'scope_label'],
    searchableFields: ['display_name', 'company_name', 'primary_authority_type'],
    rowActions: ['view', 'edit', 'lifecycle'],
    bulkActions: [],
  },
} as const satisfies EdenPageContract
