import { productServicesAreas } from './productServices.config'
import type {
  CustomerAsset,
  ProductCatalogDashboardSummary,
  ProductCatalogRecord,
  ProductServicesAreaKey,
  ProductServiceItem,
  ProductSerial,
  WarrantyTemplate,
  MaintenancePackage,
} from './productServices.types'

const now = '2026-05-18T09:00:00.000Z'

export const productServiceItemsMock: ProductServiceItem[] = [
  {
    id: 'psi-product-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'URN-2026-001',
    name: 'PlaneGuard Kamera Sistemi',
    description: 'Saha güvenliği için satılabilir ve servis verilebilir kamera sistemi.',
    item_kind: 'product',
    item_type: 'device',
    category_id: 'cat-security',
    category_name: 'Güvenlik Sistemleri',
    brand_id: 'brand-planeguard',
    brand_name: 'PlaneGuard',
    model: 'PG-4K',
    unit: 'adet',
    vat_rate: 20,
    purchase_price: 18500,
    sale_price: 27500,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: true,
    is_stock_tracked: true,
    is_manufacturable: false,
    requires_serial_number: true,
    has_warranty_tracking: true,
    has_license_tracking: false,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    minimum_stock_level: 5,
    default_warranty_duration: 24,
    default_warranty_unit: 'month',
    status: 'active',
    is_active: true,
    is_deleted: false,
    notes: 'Satış sonrası garanti ve bakım süreçleri müşteri varlığı üzerinden takip edilir.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-product-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'URN-2026-002',
    name: 'EdenPOS X200',
    description: 'Perakende noktaları için POS cihazı.',
    item_kind: 'product',
    item_type: 'device',
    category_name: 'POS ve Perakende Donanımı',
    brand_name: 'EdenPOS',
    model: 'X200',
    unit: 'adet',
    vat_rate: 20,
    purchase_price: 8200,
    sale_price: 12900,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: true,
    is_stock_tracked: true,
    is_manufacturable: false,
    requires_serial_number: true,
    has_warranty_tracking: true,
    has_license_tracking: false,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    minimum_stock_level: 10,
    default_warranty_duration: 12,
    default_warranty_unit: 'month',
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-product-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'URN-2026-003',
    name: 'Barkod Okuyucu B-10',
    description: 'Depo ve mağaza operasyonlarında kullanılan yedek parça uyumlu okuyucu.',
    item_kind: 'product',
    item_type: 'equipment',
    category_name: 'Depo Ekipmanları',
    brand_name: 'ScanPro',
    model: 'B-10',
    unit: 'adet',
    vat_rate: 20,
    purchase_price: 2100,
    sale_price: 3450,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: true,
    is_stock_tracked: true,
    is_manufacturable: false,
    requires_serial_number: true,
    has_warranty_tracking: true,
    has_license_tracking: false,
    is_serviceable: true,
    is_maintenance_contract_eligible: false,
    minimum_stock_level: 20,
    default_warranty_duration: 12,
    default_warranty_unit: 'month',
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-service-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'HZM-2026-001',
    name: 'Yerinde Kurulum Hizmeti',
    description: 'Cihaz ve yazılım kurulumları için tek seferlik hizmet.',
    item_kind: 'service',
    item_type: 'installation',
    category_name: 'Kurulum Hizmetleri',
    unit: 'saat',
    vat_rate: 20,
    sale_price: 1850,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: false,
    is_stock_tracked: false,
    is_manufacturable: false,
    requires_serial_number: false,
    has_warranty_tracking: false,
    has_license_tracking: false,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    is_periodic_service: false,
    can_attach_to_contract: true,
    can_attach_to_service_request: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-service-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'HZM-2026-002',
    name: 'Aylık Teknik Destek Hizmeti',
    description: 'Periyodik destek ve uzaktan müdahale hizmeti.',
    item_kind: 'service',
    item_type: 'technical_support',
    category_name: 'Destek Hizmetleri',
    unit: 'ay',
    vat_rate: 20,
    sale_price: 9500,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: false,
    is_stock_tracked: false,
    is_manufacturable: false,
    requires_serial_number: false,
    has_warranty_tracking: false,
    has_license_tracking: false,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    is_periodic_service: true,
    can_attach_to_contract: true,
    can_attach_to_service_request: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-license-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'LIS-2026-001',
    name: 'Eden ERP Enterprise',
    description: 'Çok şirketli yapı ve gelişmiş yetki yönetimi için kurumsal lisans.',
    item_kind: 'license_subscription',
    item_type: 'enterprise',
    category_name: 'ERP Lisansları',
    unit: 'lisans',
    vat_rate: 20,
    sale_price: 450000,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: false,
    is_stock_tracked: false,
    is_manufacturable: false,
    requires_serial_number: false,
    has_warranty_tracking: false,
    has_license_tracking: true,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    default_user_count: 300,
    default_license_duration: 12,
    default_license_unit: 'month',
    is_time_limited_license: true,
    is_renewable: true,
    is_auto_renewal_eligible: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'psi-license-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'LIS-2026-002',
    name: 'Banka Native Pro',
    description: 'Banka hareketleri ve hesap entegrasyonları için abonelik ürünü.',
    item_kind: 'license_subscription',
    item_type: 'subscription',
    category_name: 'Finans Entegrasyonları',
    unit: 'ay',
    vat_rate: 20,
    sale_price: 12500,
    currency: 'TRY',
    is_sellable: true,
    is_purchasable: false,
    is_stock_tracked: false,
    is_manufacturable: false,
    requires_serial_number: false,
    has_warranty_tracking: false,
    has_license_tracking: true,
    is_serviceable: true,
    is_maintenance_contract_eligible: true,
    default_user_count: 25,
    default_license_duration: 12,
    default_license_unit: 'month',
    is_time_limited_license: true,
    is_renewable: true,
    is_auto_renewal_eligible: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const productSerialsMock: ProductSerial[] = [
  {
    id: 'serial-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'SRN-2026-001',
    name: 'PG-2026-001',
    product_service_item_id: 'psi-product-001',
    product_service_item_name: 'PlaneGuard Kamera Sistemi',
    product_code: 'URN-2026-001',
    serial_number: 'PG-2026-001',
    lot_number: 'LOT-PG-05',
    brand_name: 'PlaneGuard',
    model: 'PG-4K',
    supplier_name: 'PlaneGuard Global',
    purchase_date: '2026-01-12',
    sale_date: '2026-03-01',
    delivery_date: '2026-03-05',
    customer_display_name: 'ABC Ltd.',
    warranty_start_date: '2026-03-05',
    warranty_end_date: '2028-03-05',
    warranty_status: 'Garanti kapsamında',
    status: 'at_customer',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'serial-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'SRN-2026-002',
    name: 'X200-TR-88921',
    product_service_item_id: 'psi-product-002',
    product_service_item_name: 'EdenPOS X200',
    product_code: 'URN-2026-002',
    serial_number: 'X200-TR-88921',
    brand_name: 'EdenPOS',
    model: 'X200',
    sale_date: '2025-05-29',
    delivery_date: '2025-05-29',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    warranty_start_date: '2025-05-29',
    warranty_end_date: '2026-05-29',
    warranty_status: 'Bitiş yaklaşıyor',
    status: 'at_customer',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'serial-003',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'SRN-2026-003',
    name: 'B10-4219',
    product_service_item_id: 'psi-product-003',
    product_service_item_name: 'Barkod Okuyucu B-10',
    product_code: 'URN-2026-003',
    serial_number: 'B10-4219',
    brand_name: 'ScanPro',
    model: 'B-10',
    customer_display_name: 'Atlas Depo Lojistik',
    warranty_start_date: '2025-09-10',
    warranty_end_date: '2026-09-10',
    warranty_status: 'Garanti kapsamında',
    status: 'in_service',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const warrantyTemplatesMock: WarrantyTemplate[] = [
  {
    id: 'warranty-template-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'GRT-2026-001',
    name: 'Standart Cihaz Garantisi',
    description: 'Cihazlar için parça ve işçilik dahil standart garanti.',
    warranty_duration: 24,
    duration_unit: 'month',
    warranty_type: 'standard',
    category_name: 'Cihazlar',
    coverage: 'Üretim kaynaklı arızalar, parça değişimi ve servis işçiliği dahildir.',
    exclusions: 'Kullanıcı hatası, sıvı teması ve yetkisiz müdahale kapsam dışıdır.',
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'warranty-template-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'GRT-2026-002',
    name: 'POS Cihazı 12 Ay Garanti',
    description: 'POS cihazları için satış sonrası garanti şablonu.',
    warranty_duration: 12,
    duration_unit: 'month',
    warranty_type: 'seller',
    product_service_item_id: 'psi-product-002',
    product_service_item_name: 'EdenPOS X200',
    coverage: 'Donanım arızaları ve yazılım güncellemeleri dahildir.',
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const maintenancePackagesMock: MaintenancePackage[] = [
  {
    id: 'maintenance-package-001',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'BAK-2026-001',
    name: 'Kurumsal Destek Paketi',
    description: 'Çok şirketli yapılarda merkezi destek ve raporlama takibi.',
    package_type: 'enterprise_support',
    period: 'Yıllık',
    sla_enabled: true,
    sla_level: 'Gold',
    response_time: '4 saat',
    resolution_time: '2 iş günü',
    sale_price: 180000,
    currency: 'TRY',
    vat_rate: 20,
    related_category_name: 'ERP Lisansları',
    is_sellable: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'maintenance-package-002',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    code: 'BAK-2026-002',
    name: 'Periyodik Cihaz Bakımı',
    description: 'Sahadaki cihazlar için periyodik bakım planı.',
    package_type: 'periodic_maintenance',
    period: '3 ayda bir',
    sla_enabled: false,
    response_time: '1 iş günü',
    resolution_time: '5 iş günü',
    sale_price: 24000,
    currency: 'TRY',
    vat_rate: 20,
    related_category_name: 'Cihazlar',
    is_sellable: true,
    status: 'active',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export const customerAssetsMockRecords: CustomerAsset[] = [
  {
    id: 'asset-001',
    customer_asset_no: 'MUR-2026-001',
    customer_id: 'mock-org-abc',
    customer_display_name: 'ABC Ltd.',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    product_service_item_id: 'psi-product-001',
    product_service_item_name: 'PlaneGuard Kamera Sistemi',
    product_serial_id: 'serial-001',
    serial_number: 'PG-2026-001',
    sales_record_id: 'mock-sale-001',
    sales_record_ref: 'SAT-2026-041',
    delivery_date: '2026-03-05',
    installation_date: '2026-03-07',
    warranty_start_date: '2026-03-05',
    warranty_end_date: '2028-03-05',
    location: 'ABC Ltd. Merkez Depo',
    assigned_to: 'mock-emp-001',
    assigned_to_name: 'Ayşe Demir',
    status: 'under_warranty',
    warranty_status: 'Garanti kapsamında',
    license_status: 'Yok',
    service_status: 'Aktif',
    notes: 'Genel ürün kartından türetilmiş müşterideki gerçek ürün kaydı.',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asset-002',
    customer_asset_no: 'MUR-2026-002',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    product_service_item_id: 'psi-product-002',
    product_service_item_name: 'EdenPOS X200',
    product_serial_id: 'serial-002',
    serial_number: 'X200-TR-88921',
    sales_record_ref: 'SAT-2025-1842',
    delivery_date: '2025-05-29',
    installation_date: '2025-05-29',
    warranty_start_date: '2025-05-29',
    warranty_end_date: '2026-05-29',
    location: 'Mavi Deniz Market - Kadıköy Şube',
    assigned_to_name: 'Mert Kaya',
    status: 'under_warranty',
    warranty_status: 'Bitiş yaklaşıyor',
    license_status: 'Yok',
    service_status: 'Kritik açık talep',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asset-003',
    customer_asset_no: 'MUR-2026-003',
    customer_display_name: 'Kuzey Holding',
    company_id: 'mock-company-eden',
    company_name: 'Eden Teknoloji',
    product_service_item_id: 'psi-license-001',
    product_service_item_name: 'Eden ERP Enterprise',
    sales_record_ref: 'SOZ-2025-071',
    delivery_date: '2025-06-05',
    installation_date: '2025-06-20',
    license_id: 'license-eden-enterprise-301',
    license_end_date: '2026-06-05',
    contract_id: 'contract-kuzey-2025-071',
    location: 'Kuzey Holding Grup BT',
    assigned_to_name: 'Can Özkan',
    status: 'active',
    warranty_status: 'Yok',
    license_status: 'Yenileme yaklaşıyor',
    service_status: 'Aktif',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export function getProductCatalogRecordsByArea(areaKey: ProductServicesAreaKey): ProductCatalogRecord[] {
  if (areaKey === 'urun-kartlari') return productServiceItemsMock.filter(item => item.item_kind === 'product')
  if (areaKey === 'hizmet-kartlari') return productServiceItemsMock.filter(item => item.item_kind === 'service')
  if (areaKey === 'lisans-abonelik-urunleri') return productServiceItemsMock.filter(item => item.item_kind === 'license_subscription')
  if (areaKey === 'seri-numarali-urunler') return productSerialsMock
  if (areaKey === 'garanti-sablonlari') return warrantyTemplatesMock
  return maintenancePackagesMock
}

export function getProductCatalogDashboardSummaries(): ProductCatalogDashboardSummary[] {
  return productServicesAreas.map(area => {
    const records = getProductCatalogRecordsByArea(area.key)
    const visible = records.filter(record => !record.is_deleted)
    return {
      area,
      totalCount: visible.length,
      activeCount: visible.filter(record => record.is_active).length,
    }
  })
}

export function createProductCatalogRecordSeed(areaKey: ProductServicesAreaKey, prefix: string): ProductCatalogRecord {
  const base = {
    id: `draft-${areaKey}-${Date.now()}`,
    code: `${prefix}-YENI`,
    name: '',
    description: '',
    company_name: 'Eden Teknoloji',
    status: 'active',
    is_active: true,
    is_deleted: false,
    notes: '',
    created_at: now,
    updated_at: now,
  }

  if (areaKey === 'urun-kartlari') {
    return {
      ...base,
      item_kind: 'product',
      item_type: 'physical_product',
      category_name: '',
      brand_name: '',
      model: '',
      unit: 'adet',
      vat_rate: 20,
      purchase_price: 0,
      sale_price: 0,
      currency: 'TRY',
      is_sellable: true,
      is_purchasable: true,
      is_stock_tracked: true,
      is_manufacturable: false,
      requires_serial_number: false,
      has_warranty_tracking: false,
      has_license_tracking: false,
      is_serviceable: false,
      is_maintenance_contract_eligible: false,
      default_warranty_unit: 'month',
    }
  }

  if (areaKey === 'hizmet-kartlari') {
    return {
      ...base,
      item_kind: 'service',
      item_type: 'technical_support',
      unit: 'saat',
      vat_rate: 20,
      sale_price: 0,
      currency: 'TRY',
      is_sellable: true,
      is_purchasable: false,
      is_stock_tracked: false,
      is_manufacturable: false,
      requires_serial_number: false,
      has_warranty_tracking: false,
      has_license_tracking: false,
      is_serviceable: true,
      is_maintenance_contract_eligible: true,
      is_periodic_service: false,
      can_attach_to_contract: true,
      can_attach_to_service_request: true,
    }
  }

  if (areaKey === 'lisans-abonelik-urunleri') {
    return {
      ...base,
      item_kind: 'license_subscription',
      item_type: 'subscription',
      unit: 'lisans',
      vat_rate: 20,
      sale_price: 0,
      currency: 'TRY',
      is_sellable: true,
      is_purchasable: false,
      is_stock_tracked: false,
      is_manufacturable: false,
      requires_serial_number: false,
      has_warranty_tracking: false,
      has_license_tracking: true,
      is_serviceable: true,
      is_maintenance_contract_eligible: true,
      default_license_unit: 'month',
      is_time_limited_license: true,
      is_renewable: true,
      is_auto_renewal_eligible: false,
    }
  }

  if (areaKey === 'seri-numarali-urunler') {
    return {
      ...base,
      product_service_item_id: '',
      product_service_item_name: '',
      serial_number: '',
      lot_number: '',
      brand_name: '',
      model: '',
      supplier_name: '',
      status: 'in_stock',
      warranty_status: 'Yok',
    }
  }

  if (areaKey === 'garanti-sablonlari') {
    return {
      ...base,
      warranty_duration: 12,
      duration_unit: 'month',
      warranty_type: 'standard',
      product_service_item_name: '',
      category_name: '',
      coverage: '',
      exclusions: '',
    }
  }

  return {
    ...base,
    package_type: 'periodic_maintenance',
    period: '',
    sla_enabled: false,
    sla_level: '',
    response_time: '',
    resolution_time: '',
    sale_price: 0,
    currency: 'TRY',
    vat_rate: 20,
    related_category_name: '',
    is_sellable: true,
  }
}

export function createCustomerAssetSeed(): CustomerAsset {
  return {
    id: `draft-customer-asset-${Date.now()}`,
    customer_asset_no: 'MUR-YENI',
    customer_display_name: '',
    company_name: 'Eden Teknoloji',
    product_service_item_id: '',
    product_service_item_name: '',
    serial_number: '',
    sales_record_ref: '',
    status: 'active',
    warranty_status: '',
    license_status: '',
    service_status: '',
    location: '',
    assigned_to_name: '',
    notes: '',
    is_active: true,
    is_deleted: false,
    created_at: now,
    updated_at: now,
  }
}
