export const PERMISSION_ACTIONS = ['view', 'insert', 'create', 'edit', 'delete', 'manage', 'approve', 'confirm', 'cancel', 'download', 'upload', 'reject', 'admin', 'passivate', 'export', 'set_default', 'view_sensitive', 'verify', 'start', 'complete', 'update', 'manual_sgk'] as const

export type PermissionAction = typeof PERMISSION_ACTIONS[number]

export const MODULE_CODES = [
  'companies',
  'employees',
  'hr',
  'organization',
  'vehicles',
  'accounting',
  'crm',
  'workflow',
  'inventory',
  'documents',
  'notifications',
  'data_quality',
  'admin_console',
  'identity',
  'tenancy',
  'product_services',
  'after_sales',
  'project_management',
  'reporting',
  'security',
  'import_export',
] as const

export type ModuleCode = typeof MODULE_CODES[number]
export type PermissionKey = `${string}.${PermissionAction}`

export const PERMISSIONS = {
  companies: {
    view: 'companies.view',
    insert: 'companies.insert',
    edit: 'companies.edit',
    approve: 'companies.approve',
    passivate: 'companies.passivate',
    export: 'companies.export',
    openingStart: 'companies.opening.start',
    openingComplete: 'companies.opening.complete',
    liquidationStart: 'companies.liquidation.start',
    liquidationComplete: 'companies.liquidation.complete',
    liquidationUpdate: 'companies.liquidation.update',
    deregistrationStart: 'companies.deregistration.start',
    deregistrationComplete: 'companies.deregistration.complete',
    lifecycleView: 'companies.lifecycle.view',
  },
  branches: {
    view: 'branches.view',
    edit: 'branches.edit',
    openingStart: 'branches.opening.start',
    closingStart: 'branches.closing.start',
    documentsUpdate: 'branches.documents.update',
  },
  employees: {
    view: 'employees.view',
    insert: 'employees.insert',
    edit: 'employees.edit',
    approve: 'employees.approve',
    passivate: 'employees.passivate',
    export: 'employees.export',
    entryStart: 'employees.entry.start',
    entryComplete: 'employees.entry.complete',
    entryManualSgk: 'employees.entry.manual_sgk',
    exitStart: 'employees.exit.start',
    exitComplete: 'employees.exit.complete',
    exitManualSgk: 'employees.exit.manual_sgk',
    workRelationView: 'employees.work_relation.view',
    workRelationEdit: 'employees.work_relation.edit',
    lifecycleView: 'employees.lifecycle.view',
  },
  hr: {
    view: 'hr.view',
    edit: 'hr.edit',
    employeeCreate: 'hr.employeeCreate',
    employmentStart: 'hr.employmentStart',
    employmentTerminate: 'hr.employmentTerminate',
    assignmentChange: 'hr.assignmentChange',
    documentsManage: 'hr.documentsManage',
    leaveView: 'hr.leaveView',
    leaveRequestCreate: 'hr.leaveRequestCreate',
    leaveApprove: 'hr.leaveApprove',
    leaveAdmin: 'hr.leaveAdmin',
    attendanceView: 'hr.attendanceView',
    attendanceEdit: 'hr.attendanceEdit',
    timesheetView: 'hr.timesheetView',
    timesheetManage: 'hr.timesheetManage',
    timesheetApprove: 'hr.timesheetApprove',
    payrollPrepView: 'hr.payrollPrepView',
    payrollPrepManage: 'hr.payrollPrepManage',
    sensitiveView: 'hr.sensitiveView',
  },
  vehicles: {
    view: 'vehicles.view',
    insert: 'vehicles.insert',
    edit: 'vehicles.edit',
    approve: 'vehicles.approve',
    passivate: 'vehicles.passivate',
    export: 'vehicles.export',
  },
  workflow: {
    view: 'workflow.view',
    approve: 'workflow.approve',
  },
  documents: {
    view: 'documents.view',
    upload: 'documents.upload',
    download: 'documents.download',
    verify: 'documents.verify',
    reject: 'documents.reject',
    delete: 'documents.delete',
    admin: 'documents.admin',
    accessLogsView: 'documents.accessLogsView',
    export: 'documents.export',
  },
  notifications: {
    view: 'notifications.view',
    manage: 'notifications.manage',
    admin: 'notifications.admin',
    emailAdmin: 'email.admin',
    remindersManage: 'reminders.manage',
  },
  dataQuality: {
    view: 'dataQuality.view',
    runChecks: 'dataQuality.runChecks',
    reviewDuplicates: 'dataQuality.reviewDuplicates',
    merge: 'dataQuality.merge',
    dismissFinding: 'dataQuality.dismissFinding',
    admin: 'dataQuality.admin',
  },
  adminConsole: {
    view: 'adminConsole.view',
    manage: 'adminConsole.manage',
    technical: 'adminConsole.technical',
    outboxAdmin: 'adminConsole.outboxAdmin',
  },
  identity: {
    view: 'identity.view',
    insert: 'identity.insert',
    edit: 'identity.edit',
    approve: 'identity.approve',
    passivate: 'identity.passivate',
  },
  entityBankAccounts: {
    view: 'entity_bank_accounts.view',
    insert: 'entity_bank_accounts.insert',
    edit: 'entity_bank_accounts.edit',
    passivate: 'entity_bank_accounts.passivate',
    setDefault: 'entity_bank_accounts.set_default',
    viewSensitive: 'entity_bank_accounts.view_sensitive',
    verify: 'entity_bank_accounts.verify',
  },
  tenancy: {
    view: 'tenants.view',
    create: 'tenants.create',
    edit: 'tenants.edit',
    delete: 'tenants.delete',
    manage: 'tenants.manage',
  },
  productServices: {
    view: 'products.view',
    create: 'products.create',
    edit: 'products.edit',
    delete: 'products.delete',
    manage: 'products.edit',
    legacyView: 'product_services.view',
    legacyCreate: 'product_services.create',
    legacyEdit: 'product_services.edit',
    legacyDelete: 'product_services.delete',
    legacyManage: 'product_services.manage',
  },
  afterSales: {
    view: 'afterSales.view',
    create: 'afterSales.requestCreate',
    edit: 'afterSales.edit',
    delete: 'afterSales.admin',
    manage: 'afterSales.admin',
    assetCreate: 'afterSales.assetCreate',
    requestCreate: 'afterSales.requestCreate',
    requestAssign: 'afterSales.requestAssign',
    serviceRecordCreate: 'afterSales.serviceRecordCreate',
    serviceComplete: 'afterSales.serviceComplete',
    maintenanceView: 'afterSales.maintenanceView',
    maintenanceManage: 'afterSales.maintenanceManage',
    fieldServiceView: 'afterSales.fieldServiceView',
    fieldServiceAssign: 'afterSales.fieldServiceAssign',
    fieldServiceExecute: 'afterSales.fieldServiceExecute',
    checklistManage: 'afterSales.checklistManage',
    serviceReportView: 'afterSales.serviceReportView',
    serviceReportGenerate: 'afterSales.serviceReportGenerate',
    warrantyOverride: 'afterSales.warrantyOverride',
    legacyView: 'after_sales.view',
    legacyCreate: 'after_sales.create',
    legacyEdit: 'after_sales.edit',
    legacyDelete: 'after_sales.delete',
    legacyManage: 'after_sales.manage',
  },
  crm: {
    view: 'crm.view',
    create: 'crm.create',
    edit: 'crm.edit',
    delete: 'crm.delete',
    interactionsManage: 'crm.interactionsManage',
    leadsManage: 'crm.leadsManage',
    leadsView: 'crm.leadsView',
    leadsEdit: 'crm.leadsEdit',
    leadsConvert: 'crm.leadsConvert',
    opportunitiesView: 'crm.opportunitiesView',
    opportunitiesEdit: 'crm.opportunitiesEdit',
    opportunityStageChange: 'crm.opportunityStageChange',
    opportunityWinLoss: 'crm.opportunityWinLoss',
    pipelineManage: 'crm.pipelineManage',
    followupManage: 'crm.followupManage',
    proposalManage: 'crm.proposalManage',
    createCariAccount: 'crm.createCariAccount',
    createTask: 'crm.createTask',
    legacyStakeholderView: 'stakeholders.view',
    legacyStakeholderCreate: 'stakeholders.insert',
    legacyStakeholderEdit: 'stakeholders.edit',
    legacyStakeholderDelete: 'stakeholders.delete',
  },
  reporting: {
    view: 'reporting.view',
    dashboardView: 'reporting.dashboardView',
    export: 'reporting.export',
    admin: 'reporting.admin',
    viewFinancial: 'reporting.viewFinancial',
    viewAuditSummary: 'reporting.viewAuditSummary',
    viewHR: 'reporting.viewHR',
    viewSystem: 'reporting.viewSystem',
    savedViewsManage: 'reporting.savedViewsManage',
    customReportsManage: 'reporting.customReportsManage',
    scheduledReportsManage: 'reporting.scheduledReportsManage',
    exportManage: 'reporting.exportManage',
    dashboardCustomize: 'reporting.dashboardCustomize',
  },
  security: {
    view: 'security.view',
    usersManage: 'security.usersManage',
    rolesManage: 'security.rolesManage',
    scopesManage: 'security.scopesManage',
    policyTest: 'security.policyTest',
    legacyUsersManage: 'users.manage',
    legacyRolesManage: 'roles.manage',
  },
  importExport: {
    importView: 'import.view',
    importCreate: 'import.create',
    importConfirm: 'import.confirm',
    importCancel: 'import.cancel',
    exportCreate: 'export.create',
    exportDownload: 'export.download',
    bulkCreate: 'bulk.create',
    bulkConfirm: 'bulk.confirm',
    bulkAdmin: 'bulk.admin',
  },
  projectManagement: {
    view: 'projects.view',
    projectsView: 'projects.view',
    projectsEdit: 'projects.edit',
    projectsCreate: 'projects.create',
    projectsDelete: 'projects.delete',
    createTask: 'tasks.create',
    editTask: 'tasks.edit',
    deleteTask: 'tasks.delete',
    assignTask: 'tasks.assign',
    transitionTask: 'tasks.transition',
    commentTask: 'tasks.comment',
    attachmentsManage: 'tasks.attachmentsManage',
    manageProjects: 'projects.edit',
    manageBoards: 'tasks.transition',
    manageWorkflows: 'projects.admin',
    viewReports: 'projects.view',
    manageAll: 'projects.admin',
  },
} as const

export function buildPermission(resource: string, action: PermissionAction): PermissionKey {
  return `${resource}.${action}`
}
