from __future__ import annotations

from typing import Any

COMPANIES: list[dict[str, Any]] = [
    {
        "key": "eden_tech",
        "trade_name": "EDEN Teknoloji Uluslararasi Ticaret ve Gayrimenkul Ltd. Sti.",
        "short_name": "EDEN Teknoloji",
        "tax_number": "9990001001",
        "tax_office": "Cankaya",
        "company_type": "limited",
        "country": "Turkiye",
        "city": "Ankara",
        "district": "Cankaya",
        "address": "Mustafa Kemal Mah. Demo Cad. No: 25 Cankaya/Ankara",
        "phone": "+90 312 000 10 01",
        "email": "info@eden-demo.example.com",
        "website": "https://demo.eden.local",
        "record_status": "active",
        "company_status": "active",
        "default_currency": "TRY",
        "scenario_key": "active_main_company",
    },
    {
        "key": "glasstech",
        "trade_name": "GlassTech Uretim A.S.",
        "short_name": "GlassTech",
        "tax_number": "9990002002",
        "tax_office": "Ostim",
        "company_type": "anonim",
        "country": "Turkiye",
        "city": "Ankara",
        "district": "Yenimahalle",
        "address": "OSB Demo Sok. No: 8 Yenimahalle/Ankara",
        "phone": "+90 312 000 20 02",
        "email": "info@glasstech.example.com",
        "website": "https://glasstech.example.com",
        "record_status": "active",
        "company_status": "active",
        "default_currency": "TRY",
        "scenario_key": "second_active_company",
    },
    {
        "key": "quattro",
        "trade_name": "Quattro Pencere Sistemleri Ltd. Sti.",
        "short_name": "Quattro",
        "tax_number": "9990003003",
        "tax_office": "Kecioren",
        "company_type": "limited",
        "country": "Turkiye",
        "city": "Ankara",
        "district": "Kecioren",
        "address": "Pilot Mah. Taslak Sk. No: 4 Kecioren/Ankara",
        "phone": "+90 312 000 30 03",
        "email": "kurulus@quattro.example.com",
        "record_status": "draft",
        "company_status": "draft",
        "default_currency": "TRY",
        "scenario_key": "draft_company_opening",
    },
    {
        "key": "old_ops",
        "trade_name": "Eski Operasyon Ltd. Sti.",
        "short_name": "Eski Operasyon",
        "tax_number": "9990004004",
        "tax_office": "Ulus",
        "company_type": "limited",
        "country": "Turkiye",
        "city": "Ankara",
        "district": "Altindag",
        "address": "Eski Demo Cad. No: 12 Altindag/Ankara",
        "phone": "+90 312 000 40 04",
        "email": "tasfiye@oldops.example.com",
        "record_status": "liquidation",
        "company_status": "liquidation",
        "default_currency": "TRY",
        "scenario_key": "liquidation_company",
    },
]

