from __future__ import annotations

from typing import Any

DOCUMENTS: list[dict[str, Any]] = [
    {
        "key": "eden_opening_doc",
        "company_key": "eden_tech",
        "owner_entity_type": "company",
        "owner_key": "eden_tech",
        "document_type": "trade_registry_gazette",
        "document_category": "Company",
        "title": "EDEN ticaret sicil gazetesi",
        "file_name": "eden-ticaret-sicil-demo.pdf",
        "file_extension": "pdf",
        "mime_type": "application/pdf",
        "file_size": 245760,
        "status": "verified",
        "verification_status": "verified",
        "required": True,
        "scenario_key": "company_opening_document",
    },
    {
        "key": "branch_opening_doc",
        "company_key": "eden_tech",
        "branch_key": "ankara_branch",
        "owner_entity_type": "branch",
        "owner_key": "ankara_branch",
        "document_type": "branch_opening_decision",
        "document_category": "Branch",
        "title": "Ankara sube acilis karari",
        "file_name": "ankara-sube-acilis-demo.pdf",
        "file_extension": "pdf",
        "mime_type": "application/pdf",
        "file_size": 132120,
        "status": "uploaded",
        "verification_status": "pending",
        "required": True,
        "scenario_key": "branch_required_document",
    },
    {
        "key": "employee_expiring_doc",
        "company_key": "eden_tech",
        "owner_entity_type": "employee",
        "owner_key": "employee_technician",
        "document_type": "certificate",
        "document_category": "HR",
        "title": "Saha teknisyeni sertifikasi",
        "file_name": "teknisyen-sertifika-demo.pdf",
        "file_extension": "pdf",
        "mime_type": "application/pdf",
        "file_size": 98320,
        "status": "uploaded",
        "verification_status": "not_required",
        "required": False,
        "scenario_key": "expiring_employee_document",
    },
    {
        "key": "import_error_report",
        "company_key": "eden_tech",
        "owner_entity_type": "import_job",
        "owner_key": "import_customer_failed",
        "document_type": "import_error_report",
        "document_category": "Import/Export",
        "title": "Cari kart import hata raporu",
        "file_name": "cari-import-error-report-demo.csv",
        "file_extension": "csv",
        "mime_type": "text/csv",
        "file_size": 6120,
        "status": "uploaded",
        "verification_status": "not_required",
        "required": False,
        "scenario_key": "import_error_report_document",
    },
]

