import type { TourStep } from '@/lib/onboarding/types'

export const systemTourSteps: TourStep[] = [
  {
    id: 'header-user-info',
    target: "[data-tour-id='header-user-info']",
    title: 'Kim giriş yapmış, buradan anlarsınız',
    description: 'Kullanıcı bilginiz ve rolünüz burada görünür. Küçük ama faydalı bir kontrol noktası: direksiyonun sizde olduğunu hatırlatır.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'theme-toggle',
    target: "[data-tour-id='theme-toggle']",
    title: 'Işıkları ayarlayalım',
    description: 'Aydınlık veya koyu görünüm arasında buradan geçiş yapabilirsiniz. Ekranla gözleriniz arasında diplomasi kuran küçük düğme budur.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'notifications',
    target: "[data-tour-id='notifications']",
    title: 'Önemli gelişmeler burada',
    description: 'Onay bekleyen işler, size atanan görevler ve dikkat isteyen kayıtlar burada toplanır. Bildirime tıklayarak ilgili sayfaya gidebilirsiniz.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'workspace-switcher',
    target: "[data-tour-id='workspace-switcher']",
    title: 'Çalışma alanınız',
    description: 'Birden fazla şirket veya yapı yönetiyorsanız, hangi çalışma alanında olduğunuzu buradan kontrol edersiniz.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'sidebar-modules',
    target: "[data-tour-id='sidebar-modules']",
    title: 'Modüller sol tarafta',
    description: 'Şirket, muhasebe, insan kaynakları, satış sonrası ve diğer ana modüller burada yer alır. Eden ERP haritasının ana caddeleri gibi düşünebilirsiniz.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'sidebar-pages',
    target: "[data-tour-id='sidebar-pages']",
    title: 'Sayfalara buradan inersiniz',
    description: 'Modül başlıklarının altında ilgili sayfalar bulunur. Aradığınız ekran genelde burada sakince sizi bekler.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'sidebar-logout',
    target: "[data-tour-id='sidebar-logout']",
    title: 'Çıkış kapısı burada',
    description: 'İşiniz bittiğinde çıkış işlemini buradan yaparsınız. Dramatik bir final değil, sadece güvenli bir kapanış.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'page-template',
    target: "[data-tour-id='page-template']",
    title: 'Ana çalışma alanı burası',
    description: 'Sayfalardaki liste, form, kart ve işlem alanları burada açılır. Eden ERP ile günlük işlerinizi bu alanda yürütürsünüz.',
    placement: 'top',
    path: '/app',
  },
  {
    id: 'page-banner',
    target: "[data-tour-id='page-banner']",
    title: 'Sayfanın tabelası',
    description: 'Her sayfanın üstünde adını ve kısa açıklamasını gösteren bir banner bulunur. Kaybolursanız önce buraya bakın; genelde gayet sakin şekilde nerede olduğunuzu söyler.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'quick-actions',
    target: "[data-tour-id='quick-actions']",
    title: 'Ekle butonu ana işlem noktasıdır',
    description: 'Bütün sayfalarda yeni kayıt eklemek için bu buton kullanılır. Ana sayfada aynı yerden widget ekleyerek kontrol panelinizi şekillendirirsiniz.',
    placement: 'left',
    path: '/app',
  },
  {
    id: 'company-page-transition',
    target: "[data-tour-id='page-banner']",
    title: 'Şirketiniz sayfasına geçiyoruz',
    description: 'Sırada kayıtta yarattığımız Şirketiniz kaydı var. İleri dediğinizde Şirket Yönetimi altındaki Şirketlerimiz sayfasına geçeceğiz; sayfa yüklenince tanıtım SmartList üzerinden devam edecek.',
    placement: 'bottom',
    path: '/app',
    navigateOnNext: '/app/sirket/companies',
  },
  {
    id: 'smart-list',
    target: "[data-tour-id='smart-list']",
    title: 'Şirketleriniz SmartList ile listelenir',
    description: 'Burada kayıtları arar, filtreler ve sıralarsınız. Hızlı Bakış varsayılan kapalı gelir; ihtiyaç olursa göz simgesinden siz açarsınız.',
    placement: 'top',
    path: '/app/sirket/companies',
  },
  {
    id: 'view-preferences',
    target: "[data-tour-id='view-preferences']",
    title: 'Liste görünümü burada ayarlanır',
    description: 'Liste/kart görünümü, kolonlar, filtreler ve Hızlı Bakış düğmesi bu alandadır. Tercihleriniz kaydedilir; sistem de "tamam, böyle seviyor" diye hatırlar.',
    placement: 'bottom',
    path: '/app/sirket/companies',
  },
  {
    id: 'smart-list-row-open',
    target: "[data-tour-id='smart-list-first-row']",
    title: 'Detay formuna satırdan geçersiniz',
    description: 'Bir kaydın satırına tıkladığınızda detay formu açılır. Şimdi örnek şirket kaydına geçiyoruz; panik yok, sadece kapıyı aralıyoruz.',
    placement: 'bottom',
    path: '/app/sirket/companies',
  },
  {
    id: 'record-forms',
    target: "[data-tour-id='record-forms']",
    title: 'Kayıt detayları burada açılır',
    description: 'Satırdan geldiğinizde kayıt artık form düzeninde görünür. Bu alan, şirketin kimlik, iletişim, ilişki ve takip bilgilerini kontrollü şekilde toplar.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-fields',
    target: "[data-tour-id='record-form-fields']",
    title: 'Form alanları nesneye göre şekillenir',
    description: 'Şirket formunda unvan, vergi, iletişim ve adres alanları öne çıkar. Çalışan formunda aynı mantık korunur ama alanlar işe giriş ve kişi bilgilerine göre değişir.',
    placement: 'left',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-title-field',
    target: "[data-tour-field='trade_name']",
    fallbackTarget: "[data-tour-id='record-form-fields']",
    title: 'Ana kimlik bilgisi burada tutulur',
    description: 'Ticari unvan gibi temel alanlar kaydın resmi yüzüdür. Form önce bu omurgayı netleştirir; sonra diğer detayları daha rahat taşırsınız.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-address-field',
    target: "[data-tour-field='address']",
    fallbackTarget: "[data-tour-id='record-form-fields']",
    title: 'Detay alanları aynı formda izlenir',
    description: 'Adres, iletişim ve benzeri bilgiler aynı kaydın parçası olarak tutulur. Aradığınız bilgi bir yerlere saklanmaz; en fazla bir sekme ötede durur.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-tabs',
    target: "[data-tour-id='record-form-tabs']",
    title: 'Detaylar sekmelerle toparlanır',
    description: 'İlişkili bilgiler sekmelerde düzenlenir. Ortaklar, temsilciler, ek bilgiler ve yaşam döngüsü gibi bölümler burada parça parça izlenir.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-lifecycle-tab',
    target: "[data-tour-id='record-lifecycle-tab']",
    title: 'Yaşam döngüsü kartına geçelim',
    description: 'Form alanlarını gördük. Şimdi kaydın resmi yolculuğunu özetleyen Yaşam Döngüsü sekmesine geçiyoruz.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
    clickOnNext: "[data-tour-id='record-lifecycle-tab']",
  },
  {
    id: 'record-lifecycle-summary',
    target: "[data-tour-id='record-lifecycle-summary']",
    title: 'Yaşam döngüsü kartı burada',
    description: 'Açılış, tasfiye, terkin ve son olay bilgileri burada özetlenir. Bu kart doğrudan form alanı gibi düzenlenmez; ilgili wizardlardan gelen read-only bir özet olarak düşünün.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-lifecycle',
    target: "[data-tour-id='record-lifecycle']",
    title: 'Bu rozet kaydın yaşam durumudur',
    description: 'Taslak, kaydın henüz resmi akışa alınmadığını gösterir. Bu yüzden taslak kayıt silinebilir; akışa girdikten sonra geçmiş korunur ve adımlar yaşam döngüsünden ilerler.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-actions',
    target: "[data-tour-id='record-form-actions']",
    title: 'Fonksiyon tuşları kayıt işlemleridir',
    description: 'Bu alan kayda ne yapacağınızı toplar. Kayıt Taslak olduğu için silme tuşu görünür; Düzenle ile güncelleme yapılabilir. Yaşam Döngüsü ise Şirket Açılışı Yap tuşuyla başlar. İleri dediğinizde o wizardı açacağım.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
    clickOnNext: "[data-tour-id='company-opening-action']",
  },
  {
    id: 'record-lifecycle-wizard',
    target: "[data-tour-id='record-lifecycle-wizard']",
    title: 'Aşamalar wizardlarla yönetilir',
    description: 'Şirket Açılışı, tasfiye ve terkin gibi adımlar bu tür wizardlarla ilerler. Aynı mantık ileride çalışan tarafında işten çıkarma gibi süreçlerde de kullanılacak.',
    placement: 'left',
    path: '/app/sirket/companies?systemTour=lifecycle',
    clickOnNext: ["[data-tour-id='record-lifecycle-wizard-close']", "[data-tour-id='record-bank-tab']"],
  },
  {
    id: 'iban-automation-badge',
    target: "[data-tour-id='entity-bank-iban-automation']",
    title: 'Veri Bekliyor rozetini görünce durun',
    description: 'IBAN girildiğinde banka, şube, hesap ve para birimi gibi bazı bilgiler sistem tarafından otomatik çekilir. Bu rozeti gördüğünüzde önce IBAN alanını doldurmayı ihmal etmeyin.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'tour-finale',
    target: "[data-tour-id='record-forms']",
    title: 'Bu kadar kafa ütülediğimiz yeter',
    description: 'Artık seni sistemle baş başa bırakma vakti. Buradan sonra ekranları rahatça kurcalayabilir, ihtiyaç duydukça kayıtların içine girip çıkabilirsin.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
]
