import type { TourStep } from '@/lib/onboarding/types'

export const systemTourSteps: TourStep[] = [
  {
    id: 'header-user-info',
    target: "[data-tour-id='header-user-info']",
    title: 'Profil ve tercihler menüsü',
    description: 'Kullanıcı bilginiz, rolünüz, tema ve görünüm tercihleriniz bu profil menüsünde toplanır.',
    placement: 'bottom',
    path: '/app',
    allowCurrentRouteTarget: true,
    spotlightPadding: 0,
  },
  {
    id: 'visual-theme-selector',
    target: "[data-tour-id='visual-theme-selector']",
    title: 'Tema profil menüsünde',
    description: 'Tema, Eden ERP nin görsel karakterini belirler. Bu satıra tıkladığınızda tema seçenekleri menünün solunda açılır.',
    placement: 'left',
    path: '/app',
    openBeforeTarget: "[data-tour-id='header-user-info']",
    clickOnNext: "[data-tour-id='visual-theme-selector']",
    allowCurrentRouteTarget: true,
    skipIfUnavailable: true,
    spotlightPadding: 0,
  },
  {
    id: 'visual-theme-options',
    target: "[data-tour-id='visual-theme-options']",
    title: 'Tema seçenekleri',
    description: 'Klasik, Kurumsal Premium, Anadolu Modern ve Teknik Komuta seçeneklerinden biri kullanıcı tercihi olarak kaydedilir.',
    placement: 'left',
    path: '/app',
    openBeforeTarget: ["[data-tour-id='header-user-info']", "[data-tour-id='visual-theme-selector']"],
    allowCurrentRouteTarget: true,
    skipIfUnavailable: true,
    spotlightPadding: 0,
  },
  {
    id: 'theme-toggle',
    target: "[data-tour-id='theme-toggle']",
    title: 'Görünüm modu aynı menüde',
    description: 'Aydınlık, karanlık veya sistem görünümü buradan seçilir. Bu tercih temayı değiştirmez, sadece ışık modunu belirler.',
    placement: 'left',
    path: '/app',
    openBeforeTarget: "[data-tour-id='header-user-info']",
    clickOnNext: "[data-tour-id='theme-toggle']",
    allowCurrentRouteTarget: true,
    spotlightPadding: 0,
  },
  {
    id: 'appearance-mode-options',
    target: "[data-tour-id='appearance-mode-options']",
    title: 'Aydınlık ve karanlık seçimi',
    description: 'Seçiminiz kullanıcı tercihi olarak kaydedilir; tema ve görünüm birbirini ezmeden birlikte çalışır.',
    placement: 'left',
    path: '/app',
    openBeforeTarget: ["[data-tour-id='header-user-info']", "[data-tour-id='theme-toggle']"],
    allowCurrentRouteTarget: true,
    skipIfUnavailable: true,
    spotlightPadding: 0,
  },
  {
    id: 'guided-tour-button',
    target: "[data-tour-id='guided-tour-button']",
    title: 'Bu turu tekrar buradan çağırırsınız',
    description: 'Bir gün "ben bunu biliyordum ama hangi düğmeydi?" derseniz panik yok. Bu küçük harita düğmesi aynı sistem turunu baştan açar; hafızaya nazik bir servis molası gibi düşünün.',
    placement: 'bottom',
    path: '/app',
    allowCurrentRouteTarget: true,
    spotlightPadding: 0,
  },
  {
    id: 'action-center',
    target: "[data-tour-id='action-center-bell']",
    title: 'Önemli gelişmeler burada',
    description: 'Onay bekleyen işler, size atanan görevler ve dikkat isteyen kayıtlar burada toplanır. Bildirime tıklayarak ilgili sayfaya gidebilirsiniz.',
    placement: 'bottom',
    path: '/app',
    allowCurrentRouteTarget: true,
    spotlightPadding: 0,
  },
  {
    id: 'workspace-switcher',
    target: "[data-tour-id='workspace-switcher']",
    title: 'Farklı şirketlere kayıtlı çalışma alanları',
    description: 'Birden fazla şirkette yetkiniz varsa aktif çalışma alanını buradan değiştirirsiniz. Geçiş sonrası menüler ve izinler seçtiğiniz şirket için yenilenir.',
    placement: 'bottom',
    path: '/app',
    allowCurrentRouteTarget: true,
    spotlightPadding: 0,
  },
  {
    id: 'sidebar-modules',
    target: "[data-tour-id='sidebar-modules']",
    title: 'Modüller sol tarafta',
    description: 'Şirket, muhasebe, insan kaynakları, satış sonrası ve diğer ana modüller burada yer alır. Eden ERP haritasının ana caddeleri gibi düşünebilirsiniz.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'sidebar-pages',
    target: "[data-tour-id='sidebar-pages']",
    title: 'Sayfalara buradan inersiniz',
    description: 'Modül başlıklarının altında ilgili sayfalar bulunur. Aradığınız ekran genelde burada sakince sizi bekler.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'sidebar-logout',
    target: "[data-tour-id='sidebar-logout']",
    title: 'Çıkış kapısı burada',
    description: 'İşiniz bittiğinde çıkış işlemini buradan yaparsınız. Dramatik bir final değil, sadece güvenli bir kapanış.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'page-template',
    target: "[data-tour-id='page-template']",
    title: 'Ana çalışma alanı burası',
    description: 'Sayfalardaki liste, form, kart ve işlem alanları burada açılır. Eden ERP ile günlük işlerinizi bu alanda yürütürsünüz.',
    placement: 'top',
    path: '/app',
  },
  {
    id: 'page-banner',
    target: "[data-tour-id='page-banner']",
    title: 'Sayfanın tabelası',
    description: 'Her sayfanın üstünde adını ve kısa açıklamasını gösteren bir banner bulunur. Kaybolursanız önce buraya bakın; genelde gayet sakin şekilde nerede olduğunuzu söyler.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'quick-actions',
    target: "[data-tour-id='quick-actions']",
    title: 'Ekle butonu ana işlem noktasıdır',
    description: 'Bütün sayfalarda yeni kayıt eklemek için bu buton kullanılır. Ana sayfada aynı yerden widget ekleyerek kontrol panelinizi şekillendirirsiniz.',
    placement: 'left',
    path: '/app',
  },
  {
    id: 'company-page-transition',
    target: "[data-tour-id='page-banner']",
    title: 'Şirketiniz sayfasına geçiyoruz',
    description: 'Sırada kayıtta yarattığımız Şirketiniz kaydı var. İleri dediğinizde Şirket Yönetimi altındaki Şirketlerimiz sayfasına geçeceğiz; sayfa yüklenince tanıtım SmartList üzerinden devam edecek.',
    placement: 'bottom',
    path: '/app',
    navigateOnNext: '/app/sirket/companies',
  },
  {
    id: 'view-preferences',
    target: "[data-tour-id='view-preferences']",
    title: 'SmartList filtreleri burada ayarlanır',
    description: 'Liste/kart görünümü, kolonlar, filtreler ve Hızlı Bakış düğmesi bu alandadır. Tercihleriniz kaydedilir; sistem de "tamam, böyle seviyor" diye hatırlar.',
    placement: 'bottom',
    path: '/app/sirket/companies',
  },
  {
    id: 'smart-list-row-open',
    target: "[data-tour-id='smart-list-first-row']",
    fallbackTarget: "[data-tour-id='smart-list']",
    title: 'Detay formuna kayıt satırından geçersiniz',
    description: 'Listede herhangi bir kayıt satırına tıkladığınızda detay formu açılır. Şimdi seçili kaydın içine geçiyoruz; panik yok, sadece kapıyı aralıyoruz.',
    placement: 'bottom',
    path: '/app/sirket/companies',
  },
  {
    id: 'record-forms',
    target: "[data-tour-id='record-forms']",
    title: 'Kayıt detayları burada açılır',
    description: 'Satırdan geldiğinizde kayıt artık form düzeninde görünür. Bu alan, seçtiğiniz şirketin kimlik, iletişim, ilişki ve takip bilgilerini kontrollü şekilde toplar.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-fields',
    target: "[data-tour-id='record-form-fields']",
    title: 'Form alanları nesneye göre şekillenir',
    description: 'Şirket formunda unvan, vergi, iletişim ve adres alanları öne çıkar. Çalışan formunda aynı mantık korunur ama alanlar işe giriş ve kişi bilgilerine göre değişir.',
    placement: 'left',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-title-field',
    target: "[data-tour-id='record-master-identity']",
    fallbackTarget: "[data-tour-id='record-form-main']",
    title: 'Temel Kimlik kartı burada',
    description: 'Bu kart kaydın master kimliğini gösterir. Şirkette unvan ve vergi kimliği, çalışanda kişi kimliği bu bölümde netleşir; diğer alanlar bu ana kimliğin üzerine kurulur.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-form-tabs',
    target: "[data-tour-id='record-form-tabs']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'Detaylar sekmelerle toparlanır',
    description: 'İlişkili bilgiler sekmelerde düzenlenir. Ortaklar, temsilciler, ek bilgiler ve yaşam döngüsü gibi bölümler burada parça parça izlenir.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-lifecycle-tab',
    target: "[data-tour-id='record-lifecycle-tab']",
    fallbackTarget: "[data-tour-id='record-form-tabs']",
    title: 'Yaşam döngüsü kartına geçelim',
    description: 'Form alanlarını gördük. Şimdi kaydın resmi yolculuğunu özetleyen Yaşam Döngüsü sekmesine geçiyoruz.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
    clickOnNext: "[data-tour-id='record-lifecycle-tab']",
  },
  {
    id: 'record-lifecycle',
    target: "[data-tour-id='record-lifecycle']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'Bu rozet kaydın yaşam durumudur',
    description: 'Taslak, kaydın henüz resmi akışa alınmadığını gösterir. Bu yüzden taslak kayıt silinebilir; akışa girdikten sonra geçmiş korunur ve adımlar yaşam döngüsünden ilerler.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-operation-area',
    target: "[data-tour-id='record-operation-area']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'İşlemler burada',
    description: 'Kayda ne yapacaksanız buradan başlarsınız. Büyük yaşam dönemeçleri, resmi veri değişiklikleri ve günlük küçük düzeltmeler aynı sırada ama ayrı düğmelerde durur. Evrak masada, panik yok.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-operation-lifecycle',
    target: "[data-tour-id='record-operation-lifecycle']",
    fallbackTarget: "[data-tour-id='record-operation-area']",
    title: 'Yaşam Döngüsü',
    description: 'Kayıtlar hayatlarına resmi işlemle başlar ve resmi işlemle sonlanır. Şirkette bu açılış, tasfiye ve terkin; çalışanda işe giriş ve işten çıkış gibi akışlardır. Sistem kaydın durumuna göre sıradaki anlamlı işlemi gösterir.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-operation-official-updates',
    target: "[data-tour-id='record-operation-official-updates']",
    fallbackTarget: "[data-tour-id='record-operation-area']",
    title: 'Resmi Değişiklikler',
    description: 'Sermaye, unvan, adres ve tescil gibi "bunu sadece klavyeyle değiştiririm" denmeyecek bilgiler burada yürür. Biraz belge, biraz karar, biraz da devlet ciddiyeti.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-operation-basic-update',
    target: "[data-tour-id='record-operation-basic-update']",
    fallbackTarget: "[data-tour-id='record-operation-area']",
    title: 'Güncelle',
    description: 'Telefon, e-posta, logo, web sitesi ve notlar gibi günlük bilgiler için burası kullanılır. Küçük tornavida işleri diyebiliriz.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'eden-ai-help',
    target: "[data-tour-id='ai-copilot-button']",
    fallbackTarget: "[data-tour-id='action-guide-search']",
    title: 'Detayda Eden AI ile konuşun',
    description: 'Bu tur sistemin kavramsal haritasını verir. Detayda bir noktada takılırsanız Eden AI ile sohbet edebilirsiniz; o da size teknik kulis anlatmadan doğru sayfa, kayıt veya sihirbaz yolunu tarif eder.',
    placement: 'left',
    path: '/app/sirket/companies?systemTour=lifecycle',
    spotlightPadding: 0,
  },
  {
    id: 'tour-finale',
    target: "[data-tour-id='record-forms']",
    title: 'Bu kadar kafa ütülediğimiz yeter',
    description: 'Artık seni sistemle baş başa bırakma vakti. Buradan sonra ekranları rahatça kurcalayabilir, ihtiyaç duydukça kayıtların içine girip çıkabilirsin.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
]
