import type { TourStep } from '@/lib/onboarding/types'

export const systemTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: "[data-tour-id='page-template']",
    fallbackTarget: "[data-tour-id='app-header']",
    title: 'Hos geldiniz',
    description: 'Eden ERPde kayitlar once taslak olarak olusturulur, resmi sonuc doguran islemler ise sihirbazlarla tamamlanir.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'sidebar-modules',
    target: "[data-tour-id='sidebar-modules']",
    title: 'Sol menu',
    description: 'Modullere buradan ulasirsiniz. Sirketler, ortaklar, temsilciler ve subeler birbirine bagli calisir.',
    placement: 'right',
    path: '/app',
  },
  {
    id: 'smart-list',
    target: "[data-tour-id='smart-list']",
    fallbackTarget: "[data-tour-id='page-template']",
    title: 'Liste sayfalari',
    description: 'Kayitlari burada arayabilir, filtreleyebilir ve detaylarini acabilirsiniz.',
    placement: 'top',
    path: '/app/sirket/companies',
  },
  {
    id: 'quick-actions',
    target: "[data-tour-id='quick-actions']",
    fallbackTarget: "[data-tour-id='page-banner']",
    title: '+ Ekle taslak kayit olusturur',
    description: '+ Ekle yeni bir taslak kayit olusturur. Taslak kayit henuz resmi islem tamamlandi anlamina gelmez.',
    placement: 'left',
    path: '/app/sirket/companies',
  },
  {
    id: 'record-forms',
    target: "[data-tour-id='record-forms']",
    fallbackTarget: "[data-tour-id='smart-list']",
    title: 'Form detayi',
    description: 'Bir kaydi actiginizda kart bilgilerini, belgeleri ve gecmisi burada gorursunuz.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'record-operation-area',
    target: "[data-tour-id='record-operation-area']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'Islem sihirbazlari',
    description: 'Unvan degisikligi, sermaye artirimi, sube acilisi, ortaklik girisi ve yetki verme gibi resmi islemler sihirbazlarla yapilir.',
    placement: 'top',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'locked-fields',
    target: "[data-tour-field='trade_name']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'Kilitli alanlar',
    description: 'Bazi alanlar dogrudan degistirilemez. Yanindaki yardim ikonundan hangi islemle degisecegini gorebilirsiniz.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'action-guide-search',
    target: "[data-tour-id='action-guide-search']",
    fallbackTarget: "[data-tour-id='record-forms']",
    title: 'AI Islem Rehberi',
    description: 'Ne yapmak istediginizi yazin; Eden ERP sizi dogru sayfa ve dogru isleme yonlendirir.',
    placement: 'bottom',
    path: '/app/sirket/companies?systemTour=lifecycle',
  },
  {
    id: 'action-center',
    target: "[data-tour-id='action-center-bell']",
    fallbackTarget: "[data-tour-id='app-header']",
    title: 'Is merkezi',
    description: 'Bekleyen gorevler, onaylar ve tamamlanamayan islemler burada gorunur.',
    placement: 'bottom',
    path: '/app',
  },
  {
    id: 'setup-readiness',
    target: "[data-tour-id='setup-readiness']",
    fallbackTarget: "[data-tour-id='page-banner']",
    title: 'Kurulum kontrolu',
    description: 'Calisma alaninizin bazi modulleri kurulum gerektirebilir. Kurulum ekrani eksik adimlari sade bir dille gosterir.',
    placement: 'bottom',
    path: '/app/sistem/kurulum',
  },
]

export const pageTourSteps: Record<string, TourStep[]> = {
  companies: [
    {
      id: 'companies-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Sirket kartlari',
      description: 'Burasi tuzel kisilik, resmi acilis, sermaye, sube, NACE, ortaklik ve temsilci ozetlerinin merkezidir.',
      placement: 'bottom',
    },
    {
      id: 'companies-add',
      target: "[data-tour-id='quick-actions']",
      title: '+ Ekle sirket taslagi olusturur',
      description: '+ Ekle yeni sirket karti taslagi olusturur. Sirket resmi acilisi ayri wizard ile tamamlanir.',
      placement: 'left',
    },
    {
      id: 'companies-readiness',
      target: "[data-tour-id='companies-product-readiness']",
      fallbackTarget: "[data-tour-id='record-forms']",
      title: 'Urun hazirlik ozeti',
      description: 'Detay ekraninda lifecycle, resmi acilis, sermaye, ortaklik, temsilci, sube, kamu/tescil ve belge eksiklerini tek bakista gorursunuz.',
      placement: 'bottom',
    },
    {
      id: 'companies-opening',
      target: "[data-tour-id='record-operation-area']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Taslak sirket nasil aktif olur?',
      description: 'Taslak sirket, Sirket Acilisi sihirbaziyla aktif hale gelir.',
      placement: 'top',
    },
    {
      id: 'companies-official-fields',
      target: "[data-tour-id='record-operation-official-updates']",
      fallbackTarget: "[data-tour-id='record-operation-area']",
      title: 'Aktif sirketlerde resmi bilgiler',
      description: 'Aktif sirketlerde unvan, adres, sermaye, NACE ve kamu bilgileri dogrudan formdan degil, resmi islem sihirbazlariyla degistirilir.',
      placement: 'top',
    },
    {
      id: 'companies-branch-opening',
      target: "[data-tour-id='record-operation-official-updates']",
      fallbackTarget: "[data-tour-id='record-operation-area']",
      title: 'Sube acilisi',
      description: 'Sube acilisi aktif sirket kartindan baslatilir.',
      placement: 'top',
    },
    {
      id: 'companies-branches-page',
      target: "[data-tour-id='sidebar-pages']",
      fallbackTarget: "[data-tour-id='sidebar-modules']",
      title: 'Acilan subeler nerede?',
      description: 'Acilmis subeler Subelerimiz sayfasinda yonetilir.',
      placement: 'right',
    },
  ],
  partners: [
    {
      id: 'partners-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Ortak kartlari',
      description: 'Burasi yalnizca kisi/kurum kartlarini degil, sirketin pay, oy, kar payi, sermaye, imtiyaz ve kontrol haklarini transaction bazli izlediginiz alandir.',
      placement: 'bottom',
    },
    {
      id: 'partners-add',
      target: "[data-tour-id='quick-actions']",
      title: '+ Ekle ortak taslagi olusturur',
      description: '+ Ekle ortak karti taslagi olusturur. Taslak kart ortaklik hakki dogurmaz; haklar Ilk Ortaklik Girisi veya ilgili ownership islemiyle olusur.',
      placement: 'left',
    },
    {
      id: 'partners-rights',
      target: "[data-tour-id='record-operation-area']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Ortaklik haklari islemle olusur',
      description: 'Pay orani, oy hakki, kar payi ve sermaye bilgileri karttan degil, Ilk Ortaklik Girisi veya ortaklik islemleriyle olusur.',
      placement: 'top',
    },
    {
      id: 'partners-readiness',
      target: "[data-tour-id='partners-ownership-readiness']",
      fallbackTarget: "[data-tour-id='record-operation-area']",
      title: 'Current ownership ozeti',
      description: 'Detay ekraninda kart durumu, current ownership, toplam pay uyarisi, imtiyaz/kontrol haklari ve dogru ownership aksiyonlari tek panelde gorunur.',
      placement: 'top',
    },
    {
      id: 'partners-active-operations',
      target: "[data-tour-id='record-operation-area']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Aktif ortak islemleri',
      description: 'Aktif ortaklarda pay devri, ortakliktan cikis ve sermaye etkileri resmi ortaklik islemleriyle yapilir.',
      placement: 'top',
    },
  ],
  representatives: [
    {
      id: 'representatives-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Temsilci karti ve yetki ayridir',
      description: 'Bu sayfa temsilci kartini, current authority read modelini, kapsam/limit/imza kurallarini ve resmi yetki islemlerini birlikte gosterir.',
      placement: 'bottom',
    },
    {
      id: 'representatives-add',
      target: "[data-tour-id='quick-actions']",
      title: '+ Ekle temsilci taslagi olusturur',
      description: '+ Ekle yalnizca temsilci karti taslagi olusturur; yetki, imza turu, limit ve kapsam Temsilcilik Baslatma islemiyle dogar.',
      placement: 'left',
    },
    {
      id: 'representatives-authority',
      target: "[data-tour-id='record-operation-area']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Yetki bilgileri islemle verilir',
      description: 'Yetki, limit, imza turu ve kapsam bilgileri karttan degil, temsil yetkisi islemleriyle verilir.',
      placement: 'top',
    },
    {
      id: 'representatives-readiness',
      target: "[data-tour-id='representatives-authority-readiness']",
      fallbackTarget: "[data-tour-id='record-operation-area']",
      title: 'Yetki ozeti',
      description: 'Detay ekraninda kart durumu, yetki durumu, scope hedefi, imza kurali, limitler, silme davranisi ve blocking uyarilar tek panelde gorunur.',
      placement: 'top',
    },
    {
      id: 'representatives-scope',
      target: "[data-tour-id='representative-scope-filters']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Yetki kapsami',
      description: 'Temsil yetkisi sirket geneli, sube, organizasyon birimi veya tesis/lokasyon bazinda sinirlandirilabilir; sirket geneli yetkiler istege bagli listeye dahil edilir.',
      placement: 'bottom',
    },
    {
      id: 'representatives-status',
      target: "[data-tour-id='smart-list']",
      title: 'Kart durumu ve yetki durumu ayridir',
      description: 'Kart durumu temsilci rolunun lifecycle bilgisidir; authority status current authority projectionindan gelir.',
      placement: 'top',
    },
  ],
  branches: [
    {
      id: 'branches-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Subeler ve operasyon noktalari',
      description: 'Burasi serbest sube kaydi acma ekrani degil; Sube Acilisi islemiyle olusan resmi/operasyonel birimleri izlediginiz ve kart seviyesinde yonettiginiz alandir.',
      placement: 'bottom',
    },
    {
      id: 'branches-not-company',
      target: "[data-tour-id='smart-list']",
      title: 'Sube ayri sirket degildir',
      description: 'Sube ayri sirket degildir; bagli sirketin alt resmi veya operasyonel birimidir.',
      placement: 'top',
    },
    {
      id: 'branches-opening',
      target: "[data-tour-id='quick-actions']",
      title: 'Sube acilisi sihirbazla yapilir',
      description: 'Sube acilisi serbest kayitla degil, Sube Acilisi resmi islem sihirbaziyla yapilir.',
      placement: 'left',
    },
    {
      id: 'branches-filters',
      target: "[data-tour-id='branches-product-filters']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Yuksek hacimli sube listesi',
      description: 'Bagli sirket, sube turu, resmi/operasyonel ayrimi ve il filtreleri server-side liste davranisiyla calisir.',
      placement: 'bottom',
    },
    {
      id: 'branches-readiness',
      target: "[data-tour-id='branches-product-readiness']",
      fallbackTarget: "[data-tour-id='record-forms']",
      title: 'Sube baglanti ozeti',
      description: 'Detay ekraninda organizasyon birimi, tesis/lokasyon, aktif temsilci yetkisi ve kapanis etki uyarilarini tek bakista gorursunuz.',
      placement: 'bottom',
    },
    {
      id: 'branches-links',
      target: "[data-tour-id='smart-list']",
      title: 'Acilis sonrasi baglantilar',
      description: 'Sube acilinca sube kaydi, organizasyon birimi ve lokasyon/tesis baglantisi olusur.',
      placement: 'top',
    },
    {
      id: 'branches-related-modules',
      target: "[data-tour-id='smart-list']",
      title: 'Kadro ve lokasyon yonetimi',
      description: 'Subenin kadrosu Teskilat/Kadrodan, fiziksel lokasyonu Tesisler/Lokasyonlardan yonetilir.',
      placement: 'top',
    },
  ],
  organization: [
    {
      id: 'organization-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Teskilat ve kadro',
      description: 'Organizasyon birimleri kadro ve hiyerarsi icindir. Sube resmi/operasyonel birim, tesis ise fiziksel yerdir.',
      placement: 'bottom',
    },
    {
      id: 'organization-concepts',
      target: "[data-tour-id='organization-product-context']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Kavram sinirlari',
      description: 'Sube acilisi organizasyon birimi olusturabilir ama organizasyon birimi sube degildir; kadro burada, fiziksel lokasyon Tesisler/Lokasyonlarda yonetilir.',
      placement: 'bottom',
    },
    {
      id: 'organization-filters',
      target: "[data-tour-id='organization-product-filters']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Agac ve filtreler',
      description: 'Sirket, durum, birim tipi ve sube baglantisi filtreleriyle hiyerarsiyi hizli daraltabilirsiniz.',
      placement: 'bottom',
    },
    {
      id: 'organization-readiness',
      target: "[data-tour-id='organization-product-readiness']",
      fallbackTarget: "[data-tour-id='record-forms']",
      title: 'Etki ozeti',
      description: 'Birim detayinda kadro, sube baglantisi ve organization scope temsil yetkisi etkileri birlikte gorunur.',
      placement: 'top',
    },
  ],
  facilities: [
    {
      id: 'facilities-purpose',
      target: "[data-tour-id='page-banner']",
      title: 'Tesisler ve lokasyonlar',
      description: 'Bu ekran fiziksel yerleri yonetir. Tesis sube degildir; sube ile iliskilendirilebilir.',
      placement: 'bottom',
    },
    {
      id: 'facilities-concepts',
      target: "[data-tour-id='facilities-product-context']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Fiziksel yer ayrimi',
      description: 'Ofis, depo, fabrika veya saha noktasi gibi fiziksel lokasyonlar burada izlenir. Sube lifecycle islemleri Subelerimiz/Sirketlerimiz uzerinden yurur.',
      placement: 'bottom',
    },
    {
      id: 'facilities-filters',
      target: "[data-tour-id='facilities-product-filters']",
      fallbackTarget: "[data-tour-id='smart-list']",
      title: 'Lokasyon filtreleri',
      description: 'Sirket, sube, durum ve tesis turu filtreleriyle lokasyon portfoyunu daraltabilirsiniz.',
      placement: 'bottom',
    },
    {
      id: 'facilities-readiness',
      target: "[data-tour-id='facilities-product-readiness']",
      fallbackTarget: "[data-tour-id='record-forms']",
      title: 'Sube ve yetki etkisi',
      description: 'Lokasyon detayinda sube baglantisi, reusable durumu ve facility scope yetki yonlendirmeleri gorunur.',
      placement: 'top',
    },
  ],
  processCenter: [
    {
      id: 'process-center-header',
      target: "[data-tour-id='process-center-header']",
      title: 'Surec ve Is Merkezi',
      description: 'Acik surecler, gorevler, onaylar ve tamamlanamayan islemler tek urun ekraninda takip edilir.',
      placement: 'bottom',
    },
    {
      id: 'process-center-filters',
      target: "[data-tour-id='process-center-filters']",
      title: 'Gorev ve onay filtreleri',
      description: 'Durum, modul ve bana atananlar filtreleriyle gunluk is listenizi daraltabilirsiniz.',
      placement: 'bottom',
    },
    {
      id: 'process-center-tabs',
      target: "[data-tour-id='process-center-tabs']",
      title: 'Is turleri',
      description: 'Surecler, Gorevler, Onaylar ve Islem/Uyari sekmeleri teknik kaynaklari is diliyle ayirir.',
      placement: 'bottom',
    },
  ],
  processDetail: [
    {
      id: 'process-detail-header',
      target: "[data-tour-id='process-detail-header']",
      title: 'Surec detayi',
      description: 'Surecin mevcut adimi, kaynak kaydi, operation sonucu ve hizli aksiyonlari burada gorunur.',
      placement: 'bottom',
    },
    {
      id: 'process-detail-tabs',
      target: "[data-tour-id='process-detail-tabs']",
      title: 'Adim, gorev ve onay izleme',
      description: 'Gorev tamamlama, onay verme/reddetme, gecmis ve teknik destek bilgisi sekmelerden izlenir.',
      placement: 'bottom',
    },
  ],
  audit: [
    {
      id: 'audit-header',
      target: "[data-tour-id='audit-header']",
      title: 'Denetim izi',
      description: 'Bu ekran teknik log degil; kim, ne zaman, hangi kayit uzerinde ne yapti sorusunu compliance diliyle cevaplar.',
      placement: 'bottom',
    },
    {
      id: 'audit-reports',
      target: "[data-tour-id='audit-reports']",
      title: 'Hazir rapor gorunumleri',
      description: 'Kullanici islemleri, resmi islemler, yetki, ortaklik, engellenen islem ve sistem uyarisi raporlarini filtre presetleriyle baslatabilirsiniz.',
      placement: 'bottom',
    },
    {
      id: 'audit-filters',
      target: "[data-tour-id='audit-filters']",
      title: 'Yuksek hacimli audit filtreleri',
      description: 'Audit listesi varsayilan son 7 gunu getirir; kullanici, modul, islem, kayit, request ve process filtreleriyle daraltilir.',
      placement: 'bottom',
    },
    {
      id: 'audit-list',
      target: "[data-tour-id='audit-list']",
      title: 'Maskeli detay',
      description: 'Satira tiklayarak old/new degerleri, operation/process baglantilarini ve maskeli teknik detaylari inceleyebilirsiniz.',
      placement: 'top',
    },
  ],
  setup: [
    {
      id: 'setup-banner',
      target: "[data-tour-id='page-banner']",
      title: 'Kurulum Merkezi',
      description: 'Modul hazirlik, lisans ve bagimlilik durumlarini burada is diliyle gorursunuz.',
      placement: 'bottom',
    },
    {
      id: 'setup-readiness',
      target: "[data-tour-id='setup-readiness']",
      title: 'Hazirlik kartlari',
      description: 'Eksik moduller, uyarilar ve onerilen kurulum adimlari burada listelenir.',
      placement: 'bottom',
    },
    {
      id: 'setup-actions',
      target: "[data-tour-id='setup-readiness']",
      title: 'Engel varsa sonraki adim',
      description: 'Bir islem kapaliysa rehber ayni nedeni gosterir ve sizi ilgili kurulum veya modul ayarina yonlendirir.',
      placement: 'top',
    },
  ],
}
