import { z } from 'zod'
import type { EdenApiContract } from '../core/api.contract'
import { isoDateString, isoDateTimeString, safeApiErrorSchema, successResponseSchema, uuidString } from '../core/validation.contract'

export const branchCreateRequestSchema = z.object({
  tenant_id: uuidString.optional(),
  company_id: uuidString,
  branch_id: uuidString.optional(),
  name: z.string().min(1),
  branch_type: z.string().min(1),
  opening_date: isoDateString.optional(),
  closing_date: isoDateString.optional(),
  base_updated_at: isoDateTimeString.optional(),
})

export const branchApiContracts = [
  {
    id: 'branch-reference-companies',
    endpointPath: '/api/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    backendAuthorization: ['companies.read'],
    backendResponseSchema: 'CompanyListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.list',
  },
  {
    id: 'branch-list',
    endpointPath: '/api/companies/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.read'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.branchesList',
  },
  {
    id: 'branch-detail',
    endpointPath: '/api/companies/branches/{branch_id}',
    frontendPath: '/api/companies/branches/{branch_id}',
    bffPath: '/api/companies/branches/{branch_id}',
    fastApiPath: '/api/v1/branches/{branch_id}',
    method: 'GET',
    requestSchema: z.object({ branch_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.read'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.branchDetail',
  },
  {
    id: 'branch-opening',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-opening',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-opening',
    bffPath: '/api/companies/{company_id}/official-changes/branch-opening',
    fastApiPath: '/api/v1/companies/{company_id}/branch-openings',
    frontendRoute: '/api/companies/branches/opening',
    method: 'POST',
    requestSchema: branchCreateRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.create'],
    backendAuthorization: ['branches.lifecycle.manage'],
    backendRequestSchema: 'BranchOpeningRequest',
    backendResponseSchema: 'OperationResponse',
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'branch_id'],
      dateFields: ['opening_date', 'closing_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['branch_type', 'record_status'],
    },
    serviceFunction: 'companyService.completeBranchOpening',
  },
  {
    id: 'branch-opening-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/branch-openings/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    backendAuthorization: ['branches.lifecycle.manage'],
    backendResponseSchema: 'PrecheckResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.branchOpeningPrecheck',
  },
  {
    id: 'branch-closing-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/branch-closings/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    backendAuthorization: ['branches.lifecycle.manage'],
    backendResponseSchema: 'PrecheckResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.branchClosingPrecheck',
  },
  {
    id: 'branch-opening-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-opening',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-opening',
    bffPath: '/api/companies/{company_id}/official-changes/branch-opening',
    fastApiPath: '/api/v1/companies/{company_id}/branch-openings',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    backendAuthorization: ['branches.lifecycle.manage'],
    backendRequestSchema: 'BranchOpeningRequest',
    backendResponseSchema: 'OperationResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeBranchOpening',
  },
  {
    id: 'branch-closing-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-closing',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-closing',
    bffPath: '/api/companies/{company_id}/official-changes/branch-closing',
    fastApiPath: '/api/v1/companies/{company_id}/branch-closings',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    backendAuthorization: ['branches.lifecycle.manage'],
    backendRequestSchema: 'BranchClosingRequest',
    backendResponseSchema: 'OperationResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeBranchClosing',
  },
  {
    id: 'branch-documents-update',
    endpointPath: '/api/companies/branches/{branch_id}/documents',
    frontendPath: '/api/companies/branches/{branch_id}/documents',
    bffPath: '/api/companies/branches/{branch_id}/documents',
    fastApiPath: '/api/v1/branches/{branch_id}/documents',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.documents.manage'],
    backendAuthorization: ['branches.documents.manage'],
    backendRequestSchema: 'BranchCardUpdateRequest',
    backendResponseSchema: 'BranchRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'branch_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.updateBranchDocuments',
  },
  {
    id: 'branch-reference-representatives',
    endpointPath: '/api/companies/representatives',
    frontendPath: '/api/companies/representatives',
    bffPath: '/api/companies/representatives',
    fastApiPath: '/api/v1/representatives',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.read'],
    backendAuthorization: ['representatives.read'],
    backendResponseSchema: 'RepresentativeListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['authority_status'] },
    serviceFunction: 'companyService.representativesList',
  },
  {
    id: 'branch-cache-invalidate-list',
    endpointPath: '/api/companies/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchListResponse',
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateList',
  },
  {
    id: 'branch-cache-invalidate-relations',
    endpointPath: '/api/companies/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchListResponse',
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateRelations',
  },
] as const satisfies readonly EdenApiContract[]
