import { z } from 'zod'
import type { EdenApiContract } from '../core/api.contract'
import { isoDateString, isoDateTimeString, safeApiErrorSchema, successResponseSchema, uuidString } from '../core/validation.contract'

export const companyCreateRequestSchema = z.object({
  tenant_id: uuidString.optional(),
  short_name: z.string().min(1),
  legal_name: z.string().min(1).optional(),
  trade_name: z.string().min(1).optional(),
  tax_number: z.string().min(1).optional(),
  tax_office: z.string().min(1).optional(),
  company_type: z.string().min(1),
  establishment_date: isoDateString.optional(),
  base_updated_at: isoDateTimeString.optional(),
})

export const companyApiContracts = [
  {
    id: 'company-list',
    endpointPath: '/api/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.list',
  },
  {
    id: 'company-detail',
    endpointPath: '/api/companies/{company_id}',
    frontendPath: '/api/companies/{company_id}',
    bffPath: '/api/companies/{company_id}',
    fastApiPath: '/api/v1/companies/{company_id}',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.detail',
  },
  {
    id: 'company-detail-section',
    endpointPath: '/api/companies/{company_id}',
    frontendPath: '/api/companies/{company_id}',
    bffPath: '/api/companies/{company_id}',
    fastApiPath: '/api/v1/companies/{company_id}',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString, section: z.string() }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.detailSection',
  },
  {
    id: 'company-create',
    endpointPath: '/api/v1/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    frontendRoute: '/api/companies',
    method: 'POST',
    requestSchema: companyCreateRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.create'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id'],
      dateFields: ['establishment_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['company_type', 'record_status'],
    },
    serviceFunction: 'companyService.create',
  },
  {
    id: 'company-update',
    endpointPath: '/api/companies/{company_id}',
    frontendPath: '/api/companies/{company_id}',
    bffPath: '/api/companies/{company_id}',
    fastApiPath: '/api/v1/companies/{company_id}',
    method: 'PATCH',
    requestSchema: companyCreateRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.update'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: ['establishment_date'], datetimeFields: ['base_updated_at'], enumFields: ['company_type', 'record_status'] },
    serviceFunction: 'companyService.update',
  },
  {
    id: 'company-branches-list',
    endpointPath: '/api/companies/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.branchesList',
  },
  {
    id: 'company-official-capital-increase-precheck',
    endpointPath: '/api/companies/{company_id}/capital-increases/precheck',
    frontendPath: '/api/companies/{company_id}/capital-increases/precheck',
    bffPath: '/api/companies/{company_id}/capital-increases/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/capital-increases/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.capitalIncreasePrecheck',
  },
  {
    id: 'company-official-capital-increase-complete',
    endpointPath: '/api/companies/{company_id}/capital-increases',
    frontendPath: '/api/companies/{company_id}/capital-increases',
    bffPath: '/api/companies/{company_id}/capital-increases',
    fastApiPath: '/api/v1/companies/{company_id}/capital-increases',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeCapitalIncrease',
  },
  {
    id: 'company-official-capital-decrease-precheck',
    endpointPath: '/api/companies/{company_id}/capital-decreases/precheck',
    frontendPath: '/api/companies/{company_id}/capital-decreases/precheck',
    bffPath: '/api/companies/{company_id}/capital-decreases/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/capital-decreases/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.capitalDecreasePrecheck',
  },
  {
    id: 'company-official-change-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/{change_type}/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/{change_type}/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/{change_type}/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/{change_type}/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString, change_type: z.string() }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: ['change_type'] },
    serviceFunction: 'companyService.officialChangePrecheck',
  },
  {
    id: 'company-official-change-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/{change_type}',
    frontendPath: '/api/companies/{company_id}/official-changes/{change_type}',
    bffPath: '/api/companies/{company_id}/official-changes/{change_type}',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/{change_type}',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: ['change_type'] },
    serviceFunction: 'companyService.completeOfficialChange',
  },
  {
    id: 'company-branch-opening-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/branch-opening/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/branch-opening/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.branchOpeningPrecheck',
  },
  {
    id: 'company-branch-opening-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-opening',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-opening',
    bffPath: '/api/companies/{company_id}/official-changes/branch-opening',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/branch-opening',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeBranchOpening',
  },
  {
    id: 'company-branch-closing-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/branch-closing/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/branch-closing/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.branchClosingPrecheck',
  },
  {
    id: 'company-branch-closing-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/branch-closing',
    frontendPath: '/api/companies/{company_id}/official-changes/branch-closing',
    bffPath: '/api/companies/{company_id}/official-changes/branch-closing',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/branch-closing',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeBranchClosing',
  },
  {
    id: 'company-nace-change-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/nace-change/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/nace-change/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/nace-change/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/nace-change/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.naceChangePrecheck',
  },
  {
    id: 'company-nace-change-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/nace-change',
    frontendPath: '/api/companies/{company_id}/official-changes/nace-change',
    bffPath: '/api/companies/{company_id}/official-changes/nace-change',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/nace-change',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeNaceChange',
  },
  {
    id: 'company-activity-subject-change-precheck',
    endpointPath: '/api/companies/{company_id}/official-changes/activity-subject-change/precheck',
    frontendPath: '/api/companies/{company_id}/official-changes/activity-subject-change/precheck',
    bffPath: '/api/companies/{company_id}/official-changes/activity-subject-change/precheck',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/activity-subject-change/precheck',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.activitySubjectChangePrecheck',
  },
  {
    id: 'company-activity-subject-change-complete',
    endpointPath: '/api/companies/{company_id}/official-changes/activity-subject-change',
    frontendPath: '/api/companies/{company_id}/official-changes/activity-subject-change',
    bffPath: '/api/companies/{company_id}/official-changes/activity-subject-change',
    fastApiPath: '/api/v1/companies/{company_id}/official-changes/activity-subject-change',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: ['base_updated_at'], enumFields: [] },
    serviceFunction: 'companyService.completeActivitySubjectChange',
  },
  {
    id: 'company-cache-invalidate-list',
    endpointPath: '/api/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateList',
  },
  {
    id: 'company-cache-invalidate-relations',
    endpointPath: '/api/companies/relations',
    frontendPath: '/api/companies/relations',
    bffPath: '/api/companies/relations',
    fastApiPath: '/api/v1/companies/relations',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateRelations',
  },
] as const satisfies readonly EdenApiContract[]
