import { z } from 'zod'
import type { EdenApiContract } from '../core/api.contract'
import { safeApiErrorSchema, successResponseSchema, uuidString } from '../core/validation.contract'

export const facilityApiContracts = [
  {
    id: 'facility-list',
    endpointPath: '/api/facilities',
    frontendPath: '/api/facilities',
    bffPath: '/api/facilities',
    fastApiPath: '/api/v1/facilities',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: [],
    backendAuthorization: [],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'facility_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'facilityService.list',
  },
  {
    id: 'facility-detail',
    endpointPath: '/api/facilities/{facility_id}',
    frontendPath: '/api/facilities/{facility_id}',
    bffPath: '/api/facilities/{facility_id}',
    fastApiPath: '/api/v1/facilities/{facility_id}',
    method: 'GET',
    requestSchema: z.object({ facility_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: [],
    backendAuthorization: [],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'facility_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'facilityService.detail',
  },
  {
    id: 'facility-create',
    endpointPath: '/api/facilities',
    frontendPath: '/api/facilities',
    bffPath: '/api/facilities',
    fastApiPath: '/api/v1/facilities',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: [],
    backendAuthorization: [],
    backendRequestSchema: 'FacilityCreateRequest',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'facility_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'facilityService.create',
  },
  {
    id: 'facility-update',
    endpointPath: '/api/facilities/{facility_id}',
    frontendPath: '/api/facilities/{facility_id}',
    bffPath: '/api/facilities/{facility_id}',
    fastApiPath: '/api/v1/facilities/{facility_id}',
    method: 'PATCH',
    requestSchema: z.object({ facility_id: uuidString }).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: [],
    backendAuthorization: [],
    backendRequestSchema: 'FacilityUpdateRequest',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'facility_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'facilityService.update',
  },
] satisfies readonly EdenApiContract[]
