import { z } from 'zod'
import type { EdenApiContract } from '../core/api.contract'
import { isoDateString, isoDateTimeString, safeApiErrorSchema, successResponseSchema, uuidString } from '../core/validation.contract'

export const partnerCreateRequestSchema = z.object({
  tenant_id: uuidString.optional(),
  company_id: uuidString,
  partner_id: uuidString.optional(),
  partner_type: z.string().min(1),
  display_name: z.string().min(1).optional(),
  share_percentage: z.number().min(0).max(100).optional(),
  capital_amount: z.number().min(0).optional(),
  start_date: isoDateString.optional(),
  base_updated_at: isoDateTimeString.optional(),
})

export const partnerApiContracts = [
  {
    id: 'partner-reference-companies',
    endpointPath: '/api/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.list',
  },
  {
    id: 'partner-current-ownership',
    endpointPath: '/api/companies/{company_id}/current-ownership',
    frontendPath: '/api/companies/{company_id}/current-ownership',
    bffPath: '/api/companies/{company_id}/current-ownership',
    fastApiPath: '/api/v1/companies/{company_id}/current-ownership',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.currentOwnership',
  },
  {
    id: 'partner-list',
    endpointPath: '/api/companies/partners',
    frontendPath: '/api/companies/partners',
    bffPath: '/api/companies/partners',
    fastApiPath: '/api/v1/partners',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'partner_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.partnersList',
  },
  {
    id: 'partner-detail',
    endpointPath: '/api/companies/partners/{partner_id}',
    frontendPath: '/api/companies/partners/{partner_id}',
    bffPath: '/api/companies/partners/{partner_id}',
    fastApiPath: '/api/v1/partners/{partner_id}',
    method: 'GET',
    requestSchema: z.object({ partner_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'partner_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.partnerDetail',
  },
  {
    id: 'partner-detail-section',
    endpointPath: '/api/companies/partners/{partner_id}',
    frontendPath: '/api/companies/partners/{partner_id}',
    bffPath: '/api/companies/partners/{partner_id}',
    fastApiPath: '/api/v1/partners/{partner_id}',
    method: 'GET',
    requestSchema: z.object({ partner_id: uuidString, section: z.string() }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'partner_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.partnerDetailSection',
  },
  {
    id: 'partner-create',
    endpointPath: '/api/v1/partners',
    frontendPath: '/api/companies/partners',
    bffPath: '/api/companies/partners',
    fastApiPath: '/api/v1/partners',
    frontendRoute: '/api/companies/partners',
    method: 'POST',
    requestSchema: partnerCreateRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.create'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'partner_id'],
      dateFields: ['start_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['partner_type', 'record_status'],
    },
    serviceFunction: 'companyService.createPartner',
  },
  {
    id: 'ownership-transaction-get',
    endpointPath: '/api/ownership/transactions/{transaction_id}',
    frontendPath: '/api/ownership/transactions/{transaction_id}',
    bffPath: '/api/ownership/transactions/{transaction_id}',
    fastApiPath: '/api/v1/ownership/transactions/{transaction_id}',
    method: 'GET',
    requestSchema: z.object({ transaction_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.lifecycle.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'transaction_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'ownershipTransactionsService.get',
  },
  {
    id: 'ownership-transaction-create',
    endpointPath: '/api/ownership/transactions',
    frontendPath: '/api/ownership/transactions',
    bffPath: '/api/ownership/transactions',
    fastApiPath: '/api/v1/ownership/transactions',
    method: 'POST',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.lifecycle.manage'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'partner_id'], dateFields: ['effective_date'], datetimeFields: ['base_updated_at'], enumFields: ['transaction_type'] },
    serviceFunction: 'ownershipTransactionsService.create',
  },
  {
    id: 'ownership-transaction-approved-for-company',
    endpointPath: '/api/ownership/transactions/approved',
    frontendPath: '/api/ownership/transactions/approved',
    bffPath: '/api/ownership/transactions/approved',
    fastApiPath: '/api/v1/ownership/transactions/approved',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['partners.lifecycle.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'ownershipTransactionsService.approvedForCompany',
  },
  {
    id: 'partner-reference-company-detail',
    endpointPath: '/api/companies/{company_id}',
    frontendPath: '/api/companies/{company_id}',
    bffPath: '/api/companies/{company_id}',
    fastApiPath: '/api/v1/companies/{company_id}',
    method: 'GET',
    requestSchema: z.object({ company_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.detail',
  },
  {
    id: 'partner-cache-invalidate-relations',
    endpointPath: '/api/companies/relations',
    frontendPath: '/api/companies/relations',
    bffPath: '/api/companies/relations',
    fastApiPath: '/api/v1/companies/relations',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateRelations',
  },
  {
    id: 'ownership-cache-invalidate-list',
    endpointPath: '/api/ownership/transactions',
    frontendPath: '/api/ownership/transactions',
    bffPath: '/api/ownership/transactions',
    fastApiPath: '/api/v1/ownership/transactions',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'ownershipTransactionsService.invalidateList',
  },
] as const satisfies readonly EdenApiContract[]
