import { z } from 'zod'
import type { EdenApiContract } from '../core/api.contract'
import { isoDateString, isoDateTimeString, safeApiErrorSchema, successResponseSchema, uuidString } from '../core/validation.contract'
import { representativeAuthorityTransactionValues } from '../entities/representative.contract'

export const representativeCreateRequestSchema = z.object({
  tenant_id: uuidString.optional(),
  company_id: uuidString,
  representative_id: uuidString.optional(),
  person_id: uuidString.optional(),
  organization_id: uuidString.optional(),
  person_kind: z.enum(['person', 'organization']),
  display_name: z.string().min(1),
  base_updated_at: isoDateTimeString.optional(),
})

export const representativeAuthorityRequestSchema = z.object({
  tenant_id: uuidString.optional(),
  company_id: uuidString,
  representative_id: uuidString,
  transaction_type: z.enum(representativeAuthorityTransactionValues),
  effective_date: isoDateString,
  end_date: isoDateString.optional(),
  authority_types: z.array(z.string()).optional(),
  base_updated_at: isoDateTimeString.optional(),
})

export const representativeApiContracts = [
  {
    id: 'representative-reference-companies',
    endpointPath: '/api/companies',
    frontendPath: '/api/companies',
    bffPath: '/api/companies',
    fastApiPath: '/api/v1/companies',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['companies.read'],
    backendAuthorization: ['companies.read'],
    backendResponseSchema: 'CompanyListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.list',
  },
  {
    id: 'representative-reference-branches',
    endpointPath: '/api/companies/branches',
    frontendPath: '/api/companies/branches',
    bffPath: '/api/companies/branches',
    fastApiPath: '/api/v1/branches',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['branches.read'],
    backendAuthorization: ['branches.read'],
    backendResponseSchema: 'BranchListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'branch_id'], dateFields: [], datetimeFields: [], enumFields: ['record_status'] },
    serviceFunction: 'companyService.branchesList',
  },
  {
    id: 'representative-list',
    endpointPath: '/api/companies/representatives',
    frontendPath: '/api/companies/representatives',
    bffPath: '/api/companies/representatives',
    fastApiPath: '/api/v1/representatives',
    method: 'GET',
    requestSchema: z.object({}).passthrough(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.read'],
    backendAuthorization: ['representatives.read'],
    backendResponseSchema: 'RepresentativeListResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'company_id', 'representative_id'], dateFields: [], datetimeFields: [], enumFields: ['authority_status'] },
    serviceFunction: 'companyService.representativesList',
  },
  {
    id: 'representative-detail',
    endpointPath: '/api/companies/representatives/{representative_id}',
    frontendPath: '/api/companies/representatives/{representative_id}',
    bffPath: '/api/companies/representatives/{representative_id}',
    fastApiPath: '/api/v1/representatives/{representative_id}',
    method: 'GET',
    requestSchema: z.object({ representative_id: uuidString }),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.read'],
    backendAuthorization: ['representatives.read'],
    backendResponseSchema: 'RepresentativeRecordResponse',
    tenantScope: 'required',
    normalization: { uuidFields: ['tenant_id', 'representative_id'], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.representativeDetail',
  },
  {
    id: 'representative-create',
    endpointPath: '/api/v1/representatives',
    frontendPath: '/api/companies/representatives',
    bffPath: '/api/companies/representatives',
    fastApiPath: '/api/v1/representatives',
    frontendRoute: '/api/companies/representatives',
    method: 'POST',
    requestSchema: representativeCreateRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.create'],
    backendAuthorization: ['representatives.create'],
    backendRequestSchema: 'RepresentativeCreateDraftRequest',
    backendResponseSchema: 'RepresentativeRecordResponse',
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id', 'person_id', 'organization_id'],
      dateFields: [],
      datetimeFields: ['base_updated_at'],
      enumFields: ['person_kind', 'record_status'],
    },
    serviceFunction: 'companyService.createRepresentative',
  },
  {
    id: 'representative-update',
    endpointPath: '/api/companies/representatives/{representative_id}',
    frontendPath: '/api/companies/representatives/{representative_id}',
    bffPath: '/api/companies/representatives/{representative_id}',
    fastApiPath: '/api/v1/representatives/{representative_id}',
    method: 'PATCH',
    requestSchema: representativeCreateRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.update'],
    backendAuthorization: ['representatives.update'],
    backendRequestSchema: 'RepresentativeCardUpdateRequest',
    backendResponseSchema: 'RepresentativeRecordResponse',
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id', 'person_id', 'organization_id'],
      dateFields: [],
      datetimeFields: ['base_updated_at'],
      enumFields: ['person_kind', 'record_status'],
    },
    serviceFunction: 'companyService.updateRepresentative',
  },
  {
    id: 'representative-authority-submit',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    frontendRoute: '/api/companies/representatives/{representative_id}/authority',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema,
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.startRepresentativeAuthority',
  },
  {
    id: 'representative-authority-start',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.startRepresentativeAuthority',
  },
  {
    id: 'representative-authority-renew',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.renewRepresentativeAuthority',
  },
  {
    id: 'representative-authority-change-scope',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.changeRepresentativeAuthorityScope',
  },
  {
    id: 'representative-authority-change-limit',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.changeRepresentativeLimit',
  },
  {
    id: 'representative-authority-suspend',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.suspendRepresentativeAuthority',
  },
  {
    id: 'representative-authority-terminate',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.terminateRepresentativeAuthority',
  },
  {
    id: 'representative-authority-correct',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.correctRepresentativeAuthority',
  },
  {
    id: 'representative-authority-reverse',
    endpointPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    frontendPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    bffPath: '/api/companies/representatives/{representative_id}/authority-transactions',
    fastApiPath: '/api/v1/representatives/{representative_id}/authority-transactions',
    method: 'POST',
    requestSchema: representativeAuthorityRequestSchema.partial(),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['representatives.authority.manage'],
    tenantScope: 'required',
    normalization: {
      uuidFields: ['tenant_id', 'company_id', 'representative_id'],
      dateFields: ['effective_date', 'end_date'],
      datetimeFields: ['base_updated_at'],
      enumFields: ['transaction_type'],
    },
    serviceFunction: 'companyService.reverseRepresentativeAuthority',
  },
  {
    id: 'representative-cache-invalidate-relations',
    endpointPath: '/api/companies/representatives',
    frontendPath: '/api/companies/representatives',
    bffPath: '/api/companies/representatives',
    fastApiPath: '/api/v1/representatives',
    method: 'GET',
    requestSchema: z.object({}),
    responseSchema: successResponseSchema,
    errorSchema: safeApiErrorSchema,
    authorization: ['client.cache.invalidate'],
    backendAuthorization: ['representatives.read'],
    backendResponseSchema: 'RepresentativeListResponse',
    tenantScope: 'none',
    normalization: { uuidFields: [], dateFields: [], datetimeFields: [], enumFields: [] },
    serviceFunction: 'companyService.invalidateRelations',
  },
] as const satisfies readonly EdenApiContract[]
