import { afterSalesAreas } from './afterSales.config'
import type { AfterSalesAreaKey, AfterSalesDashboardSummary, AfterSalesRecord, AfterSalesRecordType } from './afterSales.types'
import { getAfterSalesHealth, isAfterSalesWarning } from './afterSales.config'

const now = '2026-05-18T09:00:00.000Z'

export const afterSalesMockRecords: AfterSalesRecord[] = [
  {
    id: 'asr-warranty-001',
    record_no: 'GAR-2026-001',
    record_type: 'warranty',
    title: 'POS cihazı garanti bitiş kontrolü',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    customer_organization_id: 'mock-org-001',
    owner_company_id: 'mock-company-eden',
    owner_company_name: 'Eden Teknoloji',
    related_company_name: 'Eden ERP Satış',
    product_service_name: 'EdenPOS X200',
    product_service_kind: 'device',
    serial_or_license_no: 'X200-TR-88921',
    responsible_employee_id: 'mock-emp-001',
    responsible_employee_name: 'Ayşe Demir',
    sales_record_ref: 'SAT-2025-1842',
    status: 'active',
    priority: 'high',
    start_date: '2025-05-29',
    end_date: '2026-05-29',
    renewal_date: '2026-05-29',
    next_action_date: '2026-05-22',
    warning_count: 2,
    alert_note: 'Garanti bitişine az kaldı, yenileme teklifi hazırlanmalı.',
    notes: 'Cihaz sahada aktif, müşteri uzatma opsiyonunu değerlendirmek istiyor.',
    portal_visibility: 'customer_visible',
    preferred_contact_channel: 'phone',
    contact_name: 'Selin Kara',
    contact_phone: '+90 212 000 00 01',
    contact_email: 'selin.kara@example.com',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-warranty-002',
    record_no: 'GAR-2026-002',
    record_type: 'warranty',
    title: 'Barkod okuyucu değişim süreci',
    customer_display_name: 'Atlas Depo Lojistik',
    customer_organization_id: 'mock-org-002',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: 'Barkod Okuyucu B-10',
    product_service_kind: 'device',
    serial_or_license_no: 'B10-4219',
    responsible_employee_name: 'Mert Kaya',
    sales_record_ref: 'SAT-2025-2110',
    status: 'in_progress',
    priority: 'normal',
    start_date: '2025-09-10',
    end_date: '2026-09-10',
    next_action_date: '2026-05-24',
    warning_count: 0,
    portal_visibility: 'internal',
    preferred_contact_channel: 'email',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-license-001',
    record_no: 'LIS-2026-001',
    record_type: 'license',
    title: 'Eden ERP kullanıcı lisansı yenileme',
    customer_display_name: 'Kuzey Holding',
    customer_organization_id: 'mock-org-003',
    owner_company_name: 'Eden Teknoloji',
    related_company_name: 'Kuzey Grup BT',
    product_service_name: 'Eden ERP Enterprise',
    product_service_kind: 'license',
    serial_or_license_no: 'EDEN-ENT-301',
    responsible_employee_name: 'Can Özkan',
    sales_record_ref: 'SOZ-2025-071',
    status: 'pending',
    priority: 'high',
    start_date: '2025-06-05',
    end_date: '2026-06-05',
    renewal_date: '2026-06-05',
    next_action_date: '2026-05-25',
    warning_count: 3,
    alert_note: '301+ kullanıcı paketi yenileme teklifine dönüştürülecek.',
    notes: 'Grup şirketleri için konsolide raporlama modülü de eklenecek.',
    portal_visibility: 'partner_visible',
    preferred_contact_channel: 'email',
    contact_email: 'bt@example.com',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-license-002',
    record_no: 'LIS-2026-002',
    record_type: 'license',
    title: 'Banka Native entegrasyon lisansı',
    customer_display_name: 'Yıldız Tekstil',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: 'Banka Native Pro',
    product_service_kind: 'software',
    serial_or_license_no: 'BN-PRO-18',
    responsible_employee_name: 'Ayşe Demir',
    status: 'active',
    priority: 'normal',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    renewal_date: '2026-12-15',
    warning_count: 0,
    portal_visibility: 'internal',
    preferred_contact_channel: 'email',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-service-001',
    record_no: 'SRV-2026-001',
    record_type: 'service',
    title: 'Kritik kasa kapanış hatası',
    customer_display_name: 'Mavi Deniz Market A.Ş.',
    customer_organization_id: 'mock-org-001',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: 'Eden ERP Muhasebe',
    product_service_kind: 'software',
    responsible_employee_name: 'Mert Kaya',
    sales_record_ref: 'DESTEK-2026-388',
    status: 'open',
    priority: 'critical',
    start_date: '2026-05-18',
    sla_due_at: '2026-05-19',
    next_action_date: '2026-05-18',
    channel: 'portal',
    warning_count: 4,
    alert_note: 'Kritik açık talep, aynı gün müdahale edilmeli.',
    notes: 'Kapanış sonrası kasa farkı raporunda tutarsızlık bildirildi.',
    portal_visibility: 'customer_visible',
    preferred_contact_channel: 'phone',
    contact_name: 'Selin Kara',
    contact_phone: '+90 212 000 00 01',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-service-002',
    record_no: 'SRV-2026-002',
    record_type: 'service',
    title: 'Rapor filtreleme desteği',
    customer_display_name: 'Atlas Depo Lojistik',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: 'Eden ERP Raporlama',
    product_service_kind: 'service',
    responsible_employee_name: 'Can Özkan',
    status: 'waiting_customer',
    priority: 'normal',
    start_date: '2026-05-14',
    sla_due_at: '2026-05-25',
    warning_count: 0,
    portal_visibility: 'customer_visible',
    preferred_contact_channel: 'portal',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-contract-001',
    record_no: 'BAK-2026-001',
    record_type: 'maintenance_contract',
    title: 'Yıllık bakım sözleşmesi yenileme',
    customer_display_name: 'Yıldız Tekstil',
    customer_organization_id: 'mock-org-004',
    owner_company_name: 'Eden Teknoloji',
    related_company_name: 'Yıldız Tekstil Merkez',
    product_service_name: 'Eden ERP Bakım Paketi',
    product_service_kind: 'service',
    responsible_employee_name: 'Ayşe Demir',
    sales_record_ref: 'SOZ-2025-144',
    status: 'pending',
    priority: 'high',
    start_date: '2025-06-12',
    end_date: '2026-06-12',
    renewal_date: '2026-06-01',
    next_action_date: '2026-05-27',
    warning_count: 2,
    alert_note: 'Sözleşme yenileme görüşmesi planlanmalı.',
    portal_visibility: 'partner_visible',
    preferred_contact_channel: 'email',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'asr-contract-002',
    record_no: 'BAK-2026-002',
    record_type: 'maintenance_contract',
    title: 'Aylık yerinde bakım planı',
    customer_display_name: 'Kuzey Holding',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: 'Yerinde Bakım Hizmeti',
    product_service_kind: 'service',
    responsible_employee_name: 'Mert Kaya',
    status: 'active',
    priority: 'normal',
    start_date: '2026-01-01',
    end_date: '2026-12-31',
    next_action_date: '2026-06-03',
    warning_count: 0,
    portal_visibility: 'internal',
    preferred_contact_channel: 'email',
    record_status: 'active',
    is_deleted: false,
    created_at: now,
    updated_at: now,
  },
]

export function getAfterSalesRecordsByArea(areaKey: AfterSalesAreaKey) {
  const area = afterSalesAreas.find(item => item.key === areaKey)
  if (!area) return []
  return getAfterSalesRecordsByType(area.recordType)
}

export function getAfterSalesRecordsByType(recordType: AfterSalesRecordType) {
  return afterSalesMockRecords.filter(record => record.record_type === recordType)
}

export function getAfterSalesDashboardSummaries(): AfterSalesDashboardSummary[] {
  return afterSalesAreas.map(area => {
    const records = getAfterSalesRecordsByType(area.recordType)
    const activeRecords = records.filter(record => !record.is_deleted && record.record_status === 'active')
    return {
      area,
      activeCount: activeRecords.length,
      warningCount: activeRecords.filter(record => isAfterSalesWarning(record)).length,
      criticalCount: activeRecords.filter(record => getAfterSalesHealth(record) === 'critical').length,
    }
  })
}

export function createAfterSalesRecordSeed(recordType: AfterSalesRecordType, prefix: string): AfterSalesRecord {
  const createdAt = new Date().toISOString()
  return {
    id: `draft-${Date.now()}`,
    record_no: `${prefix}-${new Date().getFullYear()}-NEW`,
    record_type: recordType,
    title: '',
    customer_display_name: '',
    owner_company_name: 'Eden Teknoloji',
    product_service_name: '',
    product_service_kind: recordType === 'license' ? 'license' : recordType === 'service' ? 'service' : 'device',
    responsible_employee_name: '',
    status: recordType === 'service' ? 'open' : 'active',
    priority: 'normal',
    start_date: new Date().toISOString().slice(0, 10),
    end_date: '',
    renewal_date: '',
    next_action_date: '',
    sla_due_at: '',
    warning_count: 0,
    alert_note: '',
    notes: '',
    portal_visibility: 'internal',
    preferred_contact_channel: 'email',
    record_status: 'active',
    is_deleted: false,
    created_at: createdAt,
    updated_at: createdAt,
  }
}
