export const REPORTING_PERMISSIONS = {
  view: 'reporting.view',
  dashboardView: 'reporting.dashboardView',
  export: 'reporting.export',
  admin: 'reporting.admin',
  viewFinancial: 'reporting.viewFinancial',
  viewAuditSummary: 'reporting.viewAuditSummary',
  viewHR: 'reporting.viewHR',
  viewSystem: 'reporting.viewSystem',
  savedViewsManage: 'reporting.savedViewsManage',
  customReportsManage: 'reporting.customReportsManage',
  scheduledReportsManage: 'reporting.scheduledReportsManage',
  exportManage: 'reporting.exportManage',
  dashboardCustomize: 'reporting.dashboardCustomize',
} as const
