CREATE TABLE IF NOT EXISTS public.reference_data (
  key TEXT PRIMARY KEY,
  payload JSONB NOT NULL,
  source_url TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.employees
  ALTER COLUMN dogum_tarihi DROP NOT NULL,
  ALTER COLUMN kan_grubu DROP NOT NULL,
  ALTER COLUMN askerlik_durumu DROP NOT NULL,
  ALTER COLUMN tecil_tarihi DROP NOT NULL,
  ALTER COLUMN is_telefonu DROP NOT NULL,
  ALTER COLUMN acil_kisi_ad DROP NOT NULL,
  ALTER COLUMN acil_kisi_soyad DROP NOT NULL,
  ALTER COLUMN acil_kisi_yakinlik DROP NOT NULL,
  ALTER COLUMN acil_kisi_telefon DROP NOT NULL,
  ALTER COLUMN sgk_giris DROP NOT NULL,
  ALTER COLUMN gorev DROP NOT NULL,
  ALTER COLUMN ust_beden DROP NOT NULL,
  ALTER COLUMN alt_beden DROP NOT NULL,
  ALTER COLUMN ayakkabi DROP NOT NULL,
  ALTER COLUMN kep DROP NOT NULL,
  ALTER COLUMN iban DROP NOT NULL,
  ALTER COLUMN notlar DROP NOT NULL,
  ALTER COLUMN fotograf_url DROP NOT NULL;
