CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.erp_instances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text UNIQUE,
  status text NOT NULL DEFAULT 'active',
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.persons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text,
  last_name text,
  full_name text,
  nationality text,
  national_id text,
  passport_no text,
  birth_date date,
  birth_place text,
  gender text,
  phone text,
  email text,
  address text,
  city text,
  district text,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.organizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legal_name text,
  trade_name text,
  short_name text,
  country text,
  tax_number text,
  registration_number text,
  tax_office text,
  organization_type text,
  phone text,
  email text,
  address text,
  city text,
  district text,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES public.organizations(id),
  trade_name text NOT NULL,
  short_name text,
  tax_number text,
  tax_office text,
  company_type text,
  country text,
  city text,
  district text,
  address text,
  phone text,
  email text,
  website text,
  is_deleted boolean NOT NULL DEFAULT false,
  mersis_number text,
  trade_registry_number text,
  foundation_date date,
  legal_entity text,
  electronic_notification_address text,
  trade_registry_office text,
  parent_company_id uuid REFERENCES public.companies(id),
  company_code text,
  logo_url text,
  e_invoice_taxpayer boolean NOT NULL DEFAULT false,
  e_archive_taxpayer boolean NOT NULL DEFAULT false,
  e_waybill_taxpayer boolean NOT NULL DEFAULT false,
  sgk_workplace_registry_no text,
  sgk_province text,
  sgk_branch text,
  nace_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  risk_class text,
  default_currency text NOT NULL DEFAULT 'TRY',
  default_language text NOT NULL DEFAULT 'tr',
  time_zone text NOT NULL DEFAULT 'Europe/Istanbul',
  fiscal_year_start integer NOT NULL DEFAULT 1,
  hero_images jsonb NOT NULL DEFAULT '[]'::jsonb,
  hero_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  field_history jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  deleted_at timestamptz,
  deleted_by text,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.organization_unit_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  color text,
  icon text,
  parent_type_id uuid REFERENCES public.organization_unit_types(id),
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.organization_units (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  parent_unit_id uuid REFERENCES public.organization_units(id),
  unit_type_id uuid REFERENCES public.organization_unit_types(id),
  name text NOT NULL,
  type text NOT NULL DEFAULT 'department',
  short_name text,
  code text,
  location_id uuid,
  location_name text,
  status text NOT NULL DEFAULT 'active',
  start_date date,
  end_date date,
  sort_order integer NOT NULL DEFAULT 0,
  notes text,
  documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  active boolean NOT NULL DEFAULT true,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.positions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  unit_id uuid REFERENCES public.organization_units(id),
  title text NOT NULL,
  grade text,
  reports_to_position_id uuid REFERENCES public.positions(id),
  is_manager boolean NOT NULL DEFAULT false,
  norm_count integer NOT NULL DEFAULT 1,
  active_count integer NOT NULL DEFAULT 0,
  budget_code text,
  budget_amount numeric,
  work_type text,
  status text NOT NULL DEFAULT 'open',
  employee_id uuid,
  notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.employees (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid REFERENCES public.persons(id),
  employee_no text,
  first_name text NOT NULL,
  last_name text NOT NULL,
  nationality text NOT NULL DEFAULT 'TR',
  national_id text,
  passport_no text,
  gender text,
  birth_place text,
  birth_date date,
  phones jsonb NOT NULL DEFAULT '[]'::jsonb,
  emails jsonb NOT NULL DEFAULT '[]'::jsonb,
  mobile_phone text,
  work_phone text,
  home_phone text,
  email text,
  address text,
  city text,
  district text,
  emergency_contact_first_name text,
  emergency_contact_last_name text,
  emergency_contact_relationship text,
  emergency_contact_phone text,
  sgk_entry_date date,
  exit_date date,
  sgk_entry_method text,
  sgk_entry_reference_no text,
  sgk_entry_reported_by text,
  sgk_entry_insurance_branch text,
  sgk_entry_duty_code text,
  sgk_entry_occupation_code text,
  sgk_entry_csgb_business_line text,
  sgk_entry_has_disability text,
  sgk_entry_has_prior_conviction text,
  sgk_entry_education_code text,
  sgk_entry_graduation_year text,
  sgk_entry_graduation_department text,
  sgk_entry_partial_day_count text,
  sgk_exit_method text,
  sgk_exit_reference_no text,
  sgk_exit_reported_by text,
  sgk_exit_reason text,
  sgk_exit_occupation_code text,
  sgk_exit_csgb_business_line text,
  sgk_exit_percentage_wage_method text,
  sgk_exit_previous_document_type text,
  sgk_exit_previous_earned_wage text,
  sgk_exit_current_document_type text,
  sgk_exit_current_earned_wage text,
  work_status text NOT NULL DEFAULT 'suspended',
  work_type text,
  employment_contract_type text,
  employment_status text,
  record_status text NOT NULL DEFAULT 'draft',
  start_date date,
  marital_status text,
  company_id uuid REFERENCES public.companies(id),
  unit_id uuid REFERENCES public.organization_units(id),
  position_id uuid REFERENCES public.positions(id),
  job_title text,
  is_illiterate boolean NOT NULL DEFAULT false,
  education_schools jsonb NOT NULL DEFAULT '[]'::jsonb,
  foreign_languages jsonb NOT NULL DEFAULT '[]'::jsonb,
  certificates jsonb NOT NULL DEFAULT '[]'::jsonb,
  relatives jsonb NOT NULL DEFAULT '[]'::jsonb,
  entry_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  exit_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  top_size text,
  bottom_size text,
  shoe_size text,
  kep text,
  iban text,
  notes text,
  photo_url text,
  cv_document jsonb,
  diploma_document jsonb,
  field_history jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.employee_work_relations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES public.employees(id),
  company_id uuid REFERENCES public.companies(id),
  unit_id uuid REFERENCES public.organization_units(id),
  position_id uuid REFERENCES public.positions(id),
  relation_type text,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'active',
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.employee_work_lifecycle_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES public.employees(id),
  event_type text NOT NULL,
  event_date date,
  old_record_status text,
  new_record_status text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid
);

CREATE TABLE public.company_partners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  person_id uuid REFERENCES public.persons(id),
  organization_id uuid REFERENCES public.organizations(id),
  first_name text,
  last_name text,
  owner_kind text NOT NULL DEFAULT 'person',
  partner_type text NOT NULL DEFAULT 'person',
  source_type text,
  source_id uuid,
  display_name text,
  partner_name text,
  identity_number text,
  identity_tax_number text,
  share_ratio numeric,
  voting_ratio numeric,
  profit_ratio numeric,
  signature_authority boolean NOT NULL DEFAULT false,
  has_representation_right boolean NOT NULL DEFAULT false,
  share_class text,
  share_units numeric,
  nominal_value numeric,
  capital_amount numeric,
  beneficial_owner boolean NOT NULL DEFAULT false,
  is_beneficial_owner boolean NOT NULL DEFAULT false,
  beneficial_ratio numeric,
  beneficial_note text,
  is_ultimate_controller boolean NOT NULL DEFAULT false,
  has_control_right boolean NOT NULL DEFAULT false,
  control_type text,
  has_board_nomination_right boolean NOT NULL DEFAULT false,
  has_veto_right boolean NOT NULL DEFAULT false,
  has_privileged_share boolean NOT NULL DEFAULT false,
  photo_logo jsonb NOT NULL DEFAULT '[]'::jsonb,
  partner_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'active',
  record_status text,
  document_reference_id uuid,
  notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.company_representatives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  person_id uuid REFERENCES public.persons(id),
  organization_id uuid REFERENCES public.organizations(id),
  person_kind text NOT NULL DEFAULT 'person',
  source_type text,
  source_id uuid,
  display_name text,
  full_name text,
  phone text,
  email text,
  authority_type text,
  authority_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  job_title text,
  status text NOT NULL DEFAULT 'active',
  start_date date,
  end_date date,
  signature_type text,
  signature_degree text,
  transaction_limit numeric,
  payment_approval_limit numeric,
  purchase_approval_limit numeric,
  currency text NOT NULL DEFAULT 'TRY',
  requires_joint_signature boolean NOT NULL DEFAULT false,
  can_approve_alone boolean NOT NULL DEFAULT false,
  bank_authority_level text,
  department_scope text,
  gib_permissions text,
  can_submit_declaration boolean NOT NULL DEFAULT false,
  can_process_e_invoice boolean NOT NULL DEFAULT false,
  sgk_permissions text,
  can_submit_hiring_notice boolean NOT NULL DEFAULT false,
  can_submit_termination_notice boolean NOT NULL DEFAULT false,
  photo_logo jsonb NOT NULL DEFAULT '[]'::jsonb,
  authority_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  representative_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  document_reference_id uuid,
  notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.stakeholders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  person_id uuid REFERENCES public.persons(id),
  organization_id uuid REFERENCES public.organizations(id),
  stakeholder_type text NOT NULL DEFAULT 'person',
  category text,
  display_name text,
  tax_id text,
  phone text,
  email text,
  country text,
  city text,
  status text NOT NULL DEFAULT 'active',
  priority_level text,
  internal_owner_employee_id uuid REFERENCES public.employees(id),
  relationship_start_date date,
  relationship_end_date date,
  iban text,
  bank_name text,
  currency text,
  contract_status text,
  notes text,
  photo_logo jsonb NOT NULL DEFAULT '[]'::jsonb,
  stakeholder_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  stakeholder_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.partner_ownership_lifecycle_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id uuid REFERENCES public.company_partners(id),
  company_id uuid REFERENCES public.companies(id),
  event_type text NOT NULL,
  event_date date,
  old_status text,
  new_status text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid
);

CREATE TABLE public.ownership_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  transaction_no text,
  transaction_type text NOT NULL,
  transaction_date date,
  effective_date date,
  from_partner_id uuid REFERENCES public.company_partners(id),
  to_partner_id uuid REFERENCES public.company_partners(id),
  affected_partner_id uuid REFERENCES public.company_partners(id),
  share_ratio numeric,
  voting_ratio numeric,
  profit_ratio numeric,
  share_units numeric,
  nominal_value numeric,
  capital_amount numeric,
  transfer_price numeric,
  currency text NOT NULL DEFAULT 'TRY',
  has_control_right boolean NOT NULL DEFAULT false,
  control_type text,
  has_veto_right boolean NOT NULL DEFAULT false,
  has_board_nomination_right boolean NOT NULL DEFAULT false,
  has_privileged_share boolean NOT NULL DEFAULT false,
  privilege_type text,
  is_beneficial_owner boolean NOT NULL DEFAULT false,
  beneficial_ratio numeric,
  committed_capital_amount numeric,
  new_capital_amount numeric,
  commitment_date date,
  old_voting_ratio numeric,
  new_voting_ratio numeric,
  old_profit_ratio numeric,
  new_profit_ratio numeric,
  privilege_description text,
  privilege_start_date date,
  privilege_end_date date,
  removed_privilege_type text,
  removal_date date,
  capital_distribution jsonb NOT NULL DEFAULT '[]'::jsonb,
  correction_transaction_id uuid REFERENCES public.ownership_transactions(id),
  correction_reason text,
  new_values jsonb,
  reversal_transaction_id uuid REFERENCES public.ownership_transactions(id),
  reversal_reason text,
  document_status text,
  document_reference_id uuid,
  decision_reference_id uuid,
  document_files jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'draft',
  approval_status text NOT NULL DEFAULT 'draft',
  workflow_status text NOT NULL DEFAULT 'draft',
  description text,
  transaction_reason text,
  exit_reason text,
  justification text,
  notes text,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  approval_notes text,
  rejection_reason text,
  approved_by uuid,
  approved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.record_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id uuid,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  data_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  changed_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_logos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  file_name text,
  file_url text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_tax (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),
  tax_number text,
  tax_office text,
  tax_type text,
  liability_start_date date,
  e_invoice_taxpayer boolean NOT NULL DEFAULT false,
  e_archive_taxpayer boolean NOT NULL DEFAULT false,
  e_waybill_enabled boolean NOT NULL DEFAULT false,
  gib_user_code text,
  has_financial_seal boolean NOT NULL DEFAULT false,
  financial_seal_expiry_date date,
  tax_debt_tracking_active boolean NOT NULL DEFAULT false,
  last_check_date date,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_sgk (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),
  workplace_registry_no text,
  province text,
  branch text,
  registration_date date,
  nace_code text,
  risk_class text,
  uses_incentive boolean NOT NULL DEFAULT false,
  active_incentive_type text,
  incentive_end_date date,
  employee_count integer,
  debt_tracking_active boolean NOT NULL DEFAULT false,
  last_check_date date,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_incentives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),
  has_kosgeb_registration boolean NOT NULL DEFAULT false,
  kosgeb_no text,
  active_support_program text,
  application_date date,
  result_status text,
  incentive_type text,
  incentive_end_date date,
  responsible_person text,
  notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),
  mersis_number text,
  trade_registry_no text,
  registry_office text,
  chamber_registry_no text,
  chamber_name text,
  establishment_registration_date date,
  last_change_date date,
  liquidation_status text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_licenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  license_type text,
  document_no text,
  issuing_authority text,
  start_date date,
  end_date date,
  status text,
  document_file text,
  reminder_days integer,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_public_channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id),
  kep_address text,
  kep_provider text,
  e_notification_address text,
  e_notification_active boolean NOT NULL DEFAULT false,
  e_government_authority_status text,
  official_notification_email text,
  official_notification_phone text,
  has_web_service_integration boolean NOT NULL DEFAULT false,
  api_notes text,
  history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.nace_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nace_code text NOT NULL UNIQUE,
  description text,
  hazard_class text,
  source_name text,
  source_url text,
  source_reference text,
  valid_from date,
  valid_to date,
  is_active boolean NOT NULL DEFAULT true,
  last_checked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.nace_reference_update_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_name text,
  source_name text,
  source_url text,
  status text,
  message text,
  imported_count integer NOT NULL DEFAULT 0,
  updated_count integer NOT NULL DEFAULT 0,
  deactivated_count integer NOT NULL DEFAULT 0,
  raw_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid
);

CREATE TABLE public.company_nace_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id),
  nace_code_id uuid NOT NULL REFERENCES public.nace_codes(id),
  is_primary boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active',
  start_date date,
  end_date date,
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.reference_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_key text NOT NULL UNIQUE,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_name text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.company_vehicles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  assigned_employee_id uuid REFERENCES public.employees(id),
  plate_no text,
  brand text,
  model text,
  model_year integer,
  vehicle_type text,
  ownership_type text,
  fuel_type text,
  status text NOT NULL DEFAULT 'active',
  registration_date date,
  inspection_expiry_date date,
  insurance_expiry_date date,
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamptz,
  deleted_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.entity_bank_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_kind text NOT NULL,
  entity_id uuid NOT NULL,
  account_holder_name text,
  iban text,
  account_no text,
  bank_code text,
  bank_name text,
  branch_code text,
  branch_name text,
  currency text NOT NULL DEFAULT 'TRY',
  is_default boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active',
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.bank_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  bank_name text NOT NULL,
  provider_code text,
  integration_type text,
  connection_status text,
  credential_id uuid,
  environment text,
  base_url text,
  last_test_at timestamptz,
  last_sync_at timestamptz,
  status text NOT NULL DEFAULT 'active',
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.bank_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  bank_connection_id uuid REFERENCES public.bank_connections(id),
  branch_name text,
  branch_code text,
  iban text,
  account_no text,
  account_name text,
  currency text NOT NULL DEFAULT 'TRY',
  account_type text,
  opening_date date,
  is_default boolean NOT NULL DEFAULT false,
  last_balance numeric,
  last_sync_at timestamptz,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.bank_cards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  bank_connection_id uuid REFERENCES public.bank_connections(id),
  linked_bank_account_id uuid REFERENCES public.bank_accounts(id),
  branch_name text,
  branch_code text,
  last_four_digits text,
  card_name text,
  currency text NOT NULL DEFAULT 'TRY',
  card_type text,
  is_default boolean NOT NULL DEFAULT false,
  limit_amount numeric,
  available_limit numeric,
  statement_day integer,
  payment_due_day integer,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.financial_institution_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  bank_connection_id uuid REFERENCES public.bank_connections(id),
  bank_account_id uuid REFERENCES public.bank_accounts(id),
  bank_card_id uuid REFERENCES public.bank_cards(id),
  source_type text,
  movement_type text,
  movement_date date,
  value_date date,
  description text,
  counterparty_name text,
  counterparty_iban text,
  reference_no text,
  source text,
  external_transaction_id text,
  direction text,
  amount numeric,
  currency text NOT NULL DEFAULT 'TRY',
  raw_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  match_status text NOT NULL DEFAULT 'waiting',
  matched_pre_accounting_movement_id uuid,
  matched_at timestamptz,
  matched_by uuid,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.account_card_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  entity_kind text NOT NULL,
  person_id uuid REFERENCES public.persons(id),
  organization_id uuid REFERENCES public.organizations(id),
  account_code text,
  default_currency text NOT NULL DEFAULT 'TRY',
  payment_term_days integer NOT NULL DEFAULT 0,
  collection_term_days integer NOT NULL DEFAULT 0,
  risk_limit numeric NOT NULL DEFAULT 0,
  credit_limit numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active',
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version integer NOT NULL DEFAULT 1
);

CREATE TABLE public.account_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id),
  movement_type text NOT NULL,
  movement_date date NOT NULL,
  description text,
  performed_by_person_id uuid,
  counterparty_kind text NOT NULL,
  counterparty_person_id uuid,
  counterparty_organization_id uuid,
  direction text NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'TRY',
  exchange_rate numeric NOT NULL DEFAULT 1,
  payment_method text,
  payment_source_type text,
  payment_source_id uuid,
  linked_ownership_transaction_id uuid REFERENCES public.ownership_transactions(id),
  capital_relation_type text,
  offset_amount numeric,
  document_status text,
  document_reference_id uuid,
  invoice_match_status text,
  bank_match_status text,
  reconciliation_status text,
  row_health_status text,
  status text NOT NULL DEFAULT 'draft',
  workflow_status text NOT NULL DEFAULT 'none',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT account_movements_performed_by_person_id_fkey FOREIGN KEY (performed_by_person_id) REFERENCES public.persons(id),
  CONSTRAINT account_movements_counterparty_person_id_fkey FOREIGN KEY (counterparty_person_id) REFERENCES public.persons(id),
  CONSTRAINT account_movements_counterparty_organization_id_fkey FOREIGN KEY (counterparty_organization_id) REFERENCES public.organizations(id)
);

CREATE TABLE public.cash_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_date date,
  income numeric NOT NULL DEFAULT 0,
  expense numeric NOT NULL DEFAULT 0,
  description text,
  project text,
  document_no text,
  counterparty text,
  bank_name text,
  account_type text,
  account_no text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.module_licenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_key text NOT NULL UNIQUE,
  name text,
  status text NOT NULL DEFAULT 'active',
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.submodule_licenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_key text NOT NULL,
  submodule_key text NOT NULL,
  name text,
  status text NOT NULL DEFAULT 'active',
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (module_key, submodule_key)
);

CREATE TABLE public.system_parameters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parameter_key text NOT NULL UNIQUE,
  value jsonb NOT NULL DEFAULT 'null'::jsonb,
  scope text,
  module_key text,
  description text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.integration_parameters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_key text NOT NULL,
  parameter_key text NOT NULL,
  value jsonb NOT NULL DEFAULT 'null'::jsonb,
  credential_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  environment text,
  status text NOT NULL DEFAULT 'active',
  notes text,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider_key, parameter_key, environment)
);

CREATE TABLE public.roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  role_key text NOT NULL UNIQUE,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  permission_key text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.role_permissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL REFERENCES public.roles(id),
  permission_id uuid NOT NULL REFERENCES public.permissions(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (role_id, permission_id)
);

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL REFERENCES public.roles(id),
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role_id)
);

CREATE VIEW public.v_current_ownership AS
SELECT
  company_id,
  id AS partner_id,
  display_name,
  COALESCE(share_ratio, 0) AS current_share_ratio,
  COALESCE(voting_ratio, 0) AS current_voting_ratio,
  COALESCE(profit_ratio, 0) AS current_profit_ratio,
  COALESCE(capital_amount, 0) AS current_capital_amount,
  COALESCE(share_units, 0) AS current_share_units
FROM public.company_partners
WHERE is_deleted = false;

CREATE VIEW public.v_account_cards AS
SELECT
  s.company_id,
  s.entity_kind,
  s.person_id,
  s.organization_id,
  COALESCE(p.full_name, o.legal_name, o.short_name) AS display_name,
  COALESCE(p.national_id, p.passport_no) AS identity_no,
  o.tax_number AS tax_no,
  ARRAY[s.entity_kind]::text[] AS roles,
  s.account_code,
  0::numeric AS official_balance,
  0::numeric AS pending_balance,
  0::numeric AS projected_balance,
  s.default_currency AS currency,
  NULL::date AS last_movement_date,
  'normal'::text AS risk_status,
  s.status
FROM public.account_card_settings s
LEFT JOIN public.persons p ON p.id = s.person_id
LEFT JOIN public.organizations o ON o.id = s.organization_id
WHERE s.is_deleted = false;

CREATE INDEX idx_companies_active_name ON public.companies(is_deleted, short_name, trade_name);
CREATE INDEX idx_employees_active_name ON public.employees(record_status, last_name, first_name);
CREATE INDEX idx_company_partners_company_active ON public.company_partners(company_id, is_deleted, status);
CREATE INDEX idx_company_representatives_company_active ON public.company_representatives(company_id, is_deleted, status);
CREATE INDEX idx_stakeholders_company_active ON public.stakeholders(company_id, is_deleted, status);
CREATE INDEX idx_company_vehicles_active ON public.company_vehicles(is_deleted, company_id, plate_no);
CREATE INDEX idx_ownership_transactions_company_status ON public.ownership_transactions(company_id, is_deleted, approval_status);
CREATE INDEX idx_account_movements_list ON public.account_movements(is_deleted, movement_date);
CREATE INDEX idx_financial_institution_movements_list ON public.financial_institution_movements(is_deleted, movement_date, match_status);
