import type { ProjectionDefinition } from '../projection.types'

export const currentRepresentativeAuthoritiesProjection: ProjectionDefinition = {
  key: 'currentRepresentativeAuthorities',
  name: 'Guncel temsil yetkileri projection',
  version: '2026-05-26.1',
  sourceName: 'v_current_representative_authorities',
  sourceType: 'view',
  sourceTables: [
    'v_current_representative_authorities',
    'company_representatives',
    'company_representative_authority_transactions',
  ],
  defaultSort: 'representative_display_name',
  defaultDirection: 'asc',
  fields: [
    'id',
    'tenant_id',
    'company_id',
    'representative_id',
    'representative_display_name',
    'authority_types',
    'authority_status',
    'scope_type',
    'branch_id',
    'branch_name',
    'organization_unit_id',
    'organization_unit_name',
    'facility_id',
    'facility_name',
    'scope_label',
    'start_date',
    'end_date',
    'updated_at',
  ],
  searchableFields: ['representative_display_name', 'scope_label', 'branch_name', 'organization_unit_name', 'facility_name'],
  sortableFields: {
    representative_display_name: 'representative_display_name',
    authority_status: 'authority_status',
    scope_type: 'scope_type',
    start_date: 'start_date',
    updated_at: 'updated_at',
  },
  statusField: 'authority_status',
  tenantScoped: true,
  companyScoped: true,
  cacheMs: 60_000,
  fallback: {
    type: 'query_builder',
    tableName: 'company_representatives',
  },
}
