import type { ProjectionDefinition } from '../projection.types'

export const currentOwnershipProjection: ProjectionDefinition = {
  key: 'currentOwnership',
  name: 'Guncel ortaklik dagilimi projection',
  version: '2026-05-26.1',
  sourceName: 'v_current_ownership',
  sourceType: 'view',
  sourceTables: ['v_current_ownership', 'company_partners', 'ownership_transactions'],
  defaultSort: 'partner_display_name',
  defaultDirection: 'asc',
  fields: [
    'id',
    'tenant_id',
    'company_id',
    'partner_id',
    'partner_display_name',
    'share_ratio',
    'voting_ratio',
    'profit_ratio',
    'capital_amount',
    'share_units',
    'record_status',
    'effective_date',
    'transaction_id',
    'updated_at',
  ],
  searchableFields: ['partner_display_name'],
  sortableFields: {
    partner_display_name: 'partner_display_name',
    share_ratio: 'share_ratio',
    capital_amount: 'capital_amount',
    effective_date: 'effective_date',
    updated_at: 'updated_at',
  },
  statusField: 'record_status',
  tenantScoped: true,
  companyScoped: true,
  cacheMs: 60_000,
  fallback: {
    type: 'query_builder',
    tableName: 'company_partners',
  },
}
