import type { ProjectionDefinition } from '../projection.types'

export const partnerListProjection: ProjectionDefinition = {
  key: 'partnerList',
  name: 'Ortaklarimiz liste projection',
  version: '2026-05-26.1',
  sourceName: 'v_company_partner_list_projection',
  sourceType: 'view',
  sourceTables: ['company_partners', 'v_current_ownership', 'companies'],
  defaultSort: 'display_name',
  defaultDirection: 'asc',
  fields: [
    'id',
    'company_id',
    'company_name',
    'display_name',
    'owner_kind',
    'partner_type',
    'record_status',
    'current_share_ratio',
    'current_voting_ratio',
    'current_profit_ratio',
    'current_capital_amount',
    'current_share_units',
    'representative_authority_count',
    'created_at',
    'updated_at',
    'version',
  ],
  searchableFields: ['display_name', 'company_name'],
  sortableFields: {
    display_name: 'display_name',
    company_name: 'company_name',
    partner_type: 'partner_type',
    record_status: 'record_status',
    updated_at: 'updated_at',
    created_at: 'created_at',
  },
  statusField: 'record_status',
  tenantScoped: true,
  companyScoped: true,
  cacheMs: 60_000,
  fallback: {
    type: 'query_builder',
    tableName: 'company_partners',
  },
}
