import type { ProjectionDefinition } from '../projection.types'

export const stakeholderListProjection: ProjectionDefinition = {
  key: 'stakeholderList',
  name: 'Paydaslar liste projection',
  version: '2026-05-26.1',
  sourceName: 'stakeholders',
  sourceType: 'table',
  sourceTables: ['stakeholders', 'companies'],
  defaultSort: 'display_name',
  defaultDirection: 'asc',
  fields: [
    'id',
    'company_id',
    'display_name',
    'stakeholder_type',
    'category',
    'record_status',
    'status',
    'country',
    'city',
    'priority_level',
    'created_at',
    'updated_at',
    'version',
  ],
  searchableFields: ['display_name', 'stakeholder_type', 'category', 'city'],
  sortableFields: {
    display_name: 'display_name',
    stakeholder_type: 'stakeholder_type',
    category: 'category',
    status: 'status',
    record_status: 'record_status',
    updated_at: 'updated_at',
    created_at: 'created_at',
  },
  statusField: 'record_status',
  tenantScoped: true,
  companyScoped: true,
  cacheMs: 60_000,
  fallback: {
    type: 'query_builder',
    tableName: 'stakeholders',
  },
}
