export interface FeatureFlag {
  key: string
  moduleKey: string
  label: string
  defaultEnabled: boolean
  description?: string
  dependencies?: string[]
  risk?: string
}

export const featureFlags = [
  {
    key: 'actionGuide.enabled',
    moduleKey: 'settings',
    label: 'Islem Rehberi',
    description: 'Kullaniciyi dogru modul, kurulum veya resmi islem yoluna yonlendirir.',
    defaultEnabled: true,
  },
  {
    key: 'guidedTour.enabled',
    moduleKey: 'settings',
    label: 'Rehberli tur',
    description: 'Urun ekranlarinda kisa tanitim turlari gosterir.',
    defaultEnabled: true,
  },
  {
    key: 'pilot.demoMode',
    moduleKey: 'settings',
    label: 'Pilot demo modu',
    description: 'NEXT_PUBLIC_DEMO_MODE ile demo ortami rozeti ve pilot guvenlik uyarilarini etkinlestirir.',
    defaultEnabled: false,
  },
  {
    key: 'pilot.demoSeed',
    moduleKey: 'settings',
    label: 'Pilot demo seed',
    description: 'Demo tenant, rol, senaryo verisi ve validation script altyapisini pilot ortam icin hazirlar.',
    defaultEnabled: false,
  },
  {
    key: 'search.enabled',
    moduleKey: 'settings',
    label: 'Global arama',
    description: 'Kayit, islem, rapor, belge ve ayarlari global arama ile bulur.',
    defaultEnabled: true,
  },
  {
    key: 'search.commandPalette',
    moduleKey: 'settings',
    label: 'Komut paleti',
    description: 'Ctrl/Cmd+K ile command palette deneyimini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'search.recentItems',
    moduleKey: 'settings',
    label: 'Son acilanlar',
    description: 'Kullanici bazli son acilan kayit ve sik kullanilan arama ogelerini tutar.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.enabled',
    moduleKey: 'dataQuality',
    label: 'Veri kalitesi',
    description: 'Master data kalite skorlari, duplicate review ve governance sayfasini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.duplicateDetection',
    moduleKey: 'dataQuality',
    label: 'Duplicate detection',
    description: 'Master kisi/kurum, paydas, cari, calisan, asset ve belge duplicate adaylarini tespit eder.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.merge',
    moduleKey: 'dataQuality',
    label: 'Guvenli merge',
    description: 'Merge preview, relation impact, onay ve auditli merge islemlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.qualityScores',
    moduleKey: 'dataQuality',
    label: 'Kalite skorlari',
    description: 'Kayit bazli 0-100 kalite skoru, eksik alan ve relation warning hesaplar.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.actionCenterWarnings',
    moduleKey: 'dataQuality',
    label: 'Action Center kalite uyarilari',
    description: 'Acil veri kalite bulgularini yetkili kullanicilar icin Is Merkezi uyarilarina tasir.',
    defaultEnabled: true,
  },
  {
    key: 'dataQuality.importIntegration',
    moduleKey: 'dataQuality',
    label: 'Import duplicate entegrasyonu',
    description: 'Import validation sirasinda duplicate warning ve existing master onerilerini destekler.',
    defaultEnabled: true,
  },
  {
    key: 'adminConsole.enabled',
    moduleKey: 'adminConsole',
    label: 'Admin Console',
    description: 'Calisma alani, moduller, feature flags, saglik ve sistem ayarlari merkezi.',
    defaultEnabled: true,
  },
  {
    key: 'adminConsole.workspaceSettings',
    moduleKey: 'adminConsole',
    label: 'Calisma alani ayarlari',
    description: 'Tenant seviyesinde dil, para birimi, zaman dilimi ve profil ayarlarini yonetir.',
    defaultEnabled: true,
  },
  {
    key: 'adminConsole.healthDashboard',
    moduleKey: 'adminConsole',
    label: 'Saglik dashboardu',
    description: 'Backend, DB, storage, outbox, worker ve email durumlarini admin icin ozetler.',
    defaultEnabled: true,
  },
  {
    key: 'adminConsole.outboxAdmin',
    moduleKey: 'adminConsole',
    label: 'Outbox admin',
    description: 'Failed event retry, dispatch once ve worker backlog izleme akislarini etkinlestirir.',
    risk: 'Sistem olaylari tekrar calistirilabilir; sadece yetkili admin kullanmalidir.',
    defaultEnabled: true,
  },
  {
    key: 'adminConsole.technicalPage',
    moduleKey: 'adminConsole',
    label: 'Teknik admin sayfasi',
    description: 'Secret gostermeden versiyon, environment ve derin saglik bilgilerini system.admin icin acar.',
    risk: 'Teknik ayrintilar sadece system.admin kapsaminda gorunmelidir.',
    defaultEnabled: true,
  },
  {
    key: 'processEngine.enabled',
    moduleKey: 'process',
    label: 'Surec motoru',
    description: 'Gorev, onay ve surec adimlarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'auditLog.enabled',
    moduleKey: 'audit',
    label: 'Denetim izi',
    description: 'Kritik islemler icin audit kaydi olusturur ve gorunur kilar.',
    defaultEnabled: true,
  },
  {
    key: 'actionCenter.enabled',
    moduleKey: 'actionCenter',
    label: 'Is merkezi',
    description: 'Gorev, onay, tamamlanamayan islem ve sistem uyarilarini tek yerde toplar.',
    dependencies: ['process', 'audit'],
    defaultEnabled: true,
  },
  {
    key: 'reporting.savedViews',
    moduleKey: 'reporting',
    label: 'Kayitli gorunumler',
    description: 'Kullanici bazli ve paylasimli rapor filtre/kolon gorunumlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'reporting.customReports',
    moduleKey: 'reporting',
    label: 'Ozel raporlar',
    description: 'Whitelist kaynaklardan ozel rapor tanimlari olusturmayi etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'reporting.scheduledReports',
    moduleKey: 'reporting',
    label: 'Zamanlanmis raporlar',
    description: 'Raporlarin gunluk/haftalik/aylik calismasini ve alicilara iletilmesini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'reporting.exportJobs',
    moduleKey: 'reporting',
    label: 'Export joblari',
    description: 'Rapor export isteklerini auditli job olarak yonetir.',
    defaultEnabled: true,
  },
  {
    key: 'reporting.crossModuleReports',
    moduleKey: 'reporting',
    label: 'Moduller arasi raporlar',
    description: 'Sirket 360, operasyon risk, finansal belge eksikligi, servis ve HR hazirlik raporlarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.enabled',
    moduleKey: 'automation',
    label: 'Workflow Automation',
    description: 'Registry kontrollu otomasyon kurali, calisma logu ve guvenli action template altyapisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.eventRules',
    moduleKey: 'automation',
    label: 'Event rules',
    description: 'Outbox/domain eventleri ile tetiklenen otomasyonlari etkinlestirir.',
    dependencies: ['outbox'],
    defaultEnabled: true,
  },
  {
    key: 'automation.scheduledRules',
    moduleKey: 'automation',
    label: 'Scheduled rules',
    description: 'Saatlik/gunluk/haftalik/aylik otomasyon kural calismalarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.conditionRules',
    moduleKey: 'automation',
    label: 'Condition rules',
    description: 'Whitelist projection ve tablo alanlari uzerinden kosul degerlendirmeyi etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.ruleTemplates',
    moduleKey: 'automation',
    label: 'Rule templates',
    description: 'Hazir belge, gorev, CRM, servis, muhasebe ve HR otomasyon sablonlarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.simulation',
    moduleKey: 'automation',
    label: 'Rule simulation',
    description: 'Gercek aksiyon uretmeden matched record ve action preview hesaplamasini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'automation.emailActions',
    moduleKey: 'automation',
    label: 'Email actions',
    description: 'Otomasyon aksiyonlarinin e-posta kuyrugu entegrasyonunu etkinlestirir.',
    dependencies: ['notifications'],
    defaultEnabled: true,
  },
  {
    key: 'automation.taskActions',
    moduleKey: 'automation',
    label: 'Task actions',
    description: 'Otomasyonlardan proje/surec takip gorevi uretimini etkinlestirir.',
    dependencies: ['project_management'],
    defaultEnabled: true,
  },
  {
    key: 'automation.notificationActions',
    moduleKey: 'automation',
    label: 'Notification actions',
    description: 'Otomasyonlardan bildirim ve Is Merkezi uyarisi uretimini etkinlestirir.',
    dependencies: ['notifications'],
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.enabled',
    moduleKey: 'aiCopilot',
    label: 'AI Copilot',
    description: 'Baglamsal AI paneli, kayit ozeti ve guvenli islem rehberligini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.recordSummary',
    moduleKey: 'aiCopilot',
    label: 'Kayit ozeti',
    description: 'Secili kaydi ve pending action uyarilarini ozetler.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.formAssist',
    moduleKey: 'aiCopilot',
    label: 'Form assist',
    description: 'Kullanici metninden form alan onerileri uretir; mutation yapmaz.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.documentIntelligence',
    moduleKey: 'aiCopilot',
    label: 'Belge zekasi',
    description: 'Belge ozeti ve alan cikarim onerilerini insan onayi gerektiren taslak olarak uretir.',
    dependencies: ['documents'],
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.safeActions',
    moduleKey: 'aiCopilot',
    label: 'Safe AI actions',
    description: 'Registry kontrollu action preview ve guvenli yonlendirme kartlarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.adminAssist',
    moduleKey: 'aiCopilot',
    label: 'Admin assist',
    description: 'Kurulum, readiness ve sistem eksiklerini yetkili kullaniciya aciklar.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.feedback',
    moduleKey: 'aiCopilot',
    label: 'AI feedback',
    description: 'Kullanici AI cevap kalitesi icin geri bildirim verebilir.',
    defaultEnabled: true,
  },
  {
    key: 'aiCopilot.history',
    moduleKey: 'aiCopilot',
    label: 'AI history',
    description: 'Sanitize edilmis AI cevap gecmisini kullanici ve admin icin saklar.',
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.enabled',
    moduleKey: 'customerPortal',
    label: 'Musteri portali',
    description: 'Dis musterilerin kendi urun, servis, belge ve bildirimlerine sinirli erisimini etkinlestirir.',
    dependencies: ['crm', 'after_sales'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.serviceRequests',
    moduleKey: 'customerPortal',
    label: 'Portal servis talepleri',
    description: 'Portal kullanicisinin scoped kurulu urun icin servis talebi olusturmasini etkinlestirir.',
    dependencies: ['after_sales'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.installedAssets',
    moduleKey: 'customerPortal',
    label: 'Portal kurulu urunleri',
    description: 'Musteriye ait kurulu urunleri portalda listeler.',
    dependencies: ['after_sales'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.documents',
    moduleKey: 'customerPortal',
    label: 'Portal belgeleri',
    description: 'Paylasilmis belge goruntuleme ve sinirli belge yukleme akisini etkinlestirir.',
    dependencies: ['documents'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.notifications',
    moduleKey: 'customerPortal',
    label: 'Portal bildirimleri',
    description: 'Musteri odakli bildirim listesini etkinlestirir.',
    dependencies: ['notifications'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.invitations',
    moduleKey: 'customerPortal',
    label: 'Portal davetleri',
    description: 'Internal kullanicinin musteri portal kullanicisi davet etmesini etkinlestirir.',
    dependencies: ['crm'],
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.branding',
    moduleKey: 'customerPortal',
    label: 'Portal marka ayarlari',
    description: 'Portal shell icinde musteri/tenant odakli sade marka gorunumunu etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'customerPortal.customerComments',
    moduleKey: 'customerPortal',
    label: 'Portal musteri yorumlari',
    description: 'Portal servis taleplerine musteri yorumu ve ek bilgisi kabul eder.',
    defaultEnabled: true,
  },
  {
    key: 'integrations.enabled',
    moduleKey: 'integrations',
    label: 'Integration Hub',
    description: 'Dis sistemlerle webhook, inbound event ve credential yonetimi altyapisini etkinlestirir.',
    dependencies: ['outbox'],
    defaultEnabled: true,
  },
  {
    key: 'integrations.outboundWebhooks',
    moduleKey: 'integrations',
    label: 'Outbound webhooks',
    description: 'Outbox eventlerinden imzali webhook teslimati uretilmesini etkinlestirir.',
    dependencies: ['outbox'],
    defaultEnabled: true,
  },
  {
    key: 'integrations.inboundWebhooks',
    moduleKey: 'integrations',
    label: 'Inbound webhooks',
    description: 'Dis sistemlerden imzali inbound payload kabulunu etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'integrations.credentials',
    moduleKey: 'integrations',
    label: 'Integration credentials',
    description: 'API key ve webhook secret olusturma, rotate ve revoke akisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'integrations.deliveryRetry',
    moduleKey: 'integrations',
    label: 'Webhook retry',
    description: 'Basarisiz teslimatlari retry/dead-letter akisiyle izler.',
    defaultEnabled: true,
  },
  {
    key: 'integrations.eventSubscriptions',
    moduleKey: 'integrations',
    label: 'Event subscriptions',
    description: 'Registry kontrollu event aboneliklerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'integrations.inboundServiceRequest',
    moduleKey: 'integrations',
    label: 'Inbound servis talebi',
    description: 'Dis sistem servis taleplerinin after-sales kanalina normalize edilmesini etkinlestirir.',
    dependencies: ['after_sales'],
    defaultEnabled: true,
  },
  {
    key: 'integrations.webhookSigning',
    moduleKey: 'integrations',
    label: 'Webhook signing',
    description: 'Outbound ve inbound payloadlarda HMAC imza kontrolunu etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'branches.facilityAutoCreate',
    moduleKey: 'branches',
    label: 'Sube acilisinda tesis/lokasyon olusturma',
    description: 'Sube Acilisi sirasinda tesis/lokasyon kaydinin otomatik olusmasini saglar.',
    dependencies: ['facilities'],
    defaultEnabled: true,
  },
  {
    key: 'branches.organizationAutoCreate',
    moduleKey: 'branches',
    label: 'Sube acilisinda organizasyon birimi olusturma',
    description: 'Sube Acilisi sirasinda organizasyon birimi kaydinin otomatik olusmasini saglar.',
    dependencies: ['organization'],
    defaultEnabled: true,
  },
  {
    key: 'branches.documentUpdate',
    moduleKey: 'branches',
    label: 'Sube belge guncelleme islemleri',
    description: 'Sube belgeleri icin ayri belge guncelleme akisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'representatives.scopeAuthority',
    moduleKey: 'representatives',
    label: 'Kapsam bazli temsil yetkisi',
    description: 'Temsil yetkilerini sirket geneli, sube, organizasyon veya tesis kapsamina indirger.',
    dependencies: ['branches', 'organization', 'facilities'],
    defaultEnabled: true,
  },
  {
    key: 'facilities.freeCreate',
    moduleKey: 'facilities',
    label: 'Serbest tesis/lokasyon olusturma',
    description: 'Tesisler/Lokasyonlar sayfasindan subeden bagimsiz fiziksel lokasyon olusturulabilsin.',
    defaultEnabled: true,
  },
  {
    key: 'organization.positionManagement',
    moduleKey: 'organization',
    label: 'Kadro/Pozisyon yonetimi',
    description: 'Organizasyon birimleri altinda kadro ve pozisyon yonetimini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'audit.export',
    moduleKey: 'audit',
    label: 'Denetim raporu disa aktarimi',
    description: 'Denetim izi raporlarinin maskeli CSV/Excel ciktisini etkinlestirir.',
    risk: 'Disa aktarim yetkisi ve tarih araligi zorunlu olmalidir.',
    defaultEnabled: true,
  },
  {
    key: 'dataImport.enabled',
    moduleKey: 'importExport',
    label: 'Data import',
    description: 'Sablonlu dosya yukleme, mapping, validation ve onayli import akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'dataImport.csv',
    moduleKey: 'importExport',
    label: 'CSV import',
    description: 'CSV dosyalarindan import parse akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'dataImport.xlsx',
    moduleKey: 'importExport',
    label: 'XLSX import',
    description: 'XLSX dosyalarindan import parse akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'dataExport.enabled',
    moduleKey: 'importExport',
    label: 'Data export',
    description: 'Maskeli ve auditli CSV export job akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'bulkOperations.enabled',
    moduleKey: 'importExport',
    label: 'Bulk operations',
    description: 'Kontrollu bulk action dry-run ve confirm akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'bulkOperations.confirmationRequired',
    moduleKey: 'importExport',
    label: 'Bulk onay zorunlulugu',
    description: 'Bulk action icin dry-run sonrasi kullanici onayi gerektirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.enabled',
    moduleKey: 'documents',
    label: 'Belge yonetimi',
    description: 'Merkezi belge metadata, relation ve storage akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.preview',
    moduleKey: 'documents',
    label: 'Belge onizleme',
    description: 'Belge onizleme icin kontrollu signed URL uretimini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.versioning',
    moduleKey: 'documents',
    label: 'Belge versiyonlama',
    description: 'Replace/new version akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.verification',
    moduleKey: 'documents',
    label: 'Belge dogrulama',
    description: 'Belge verify/reject statulerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.accessLogs',
    moduleKey: 'documents',
    label: 'Belge erisim loglari',
    description: 'Belge view/download/preview erisimlerini loglar.',
    defaultEnabled: true,
  },
  {
    key: 'documents.mobileCameraUpload',
    moduleKey: 'documents',
    label: 'Mobil kamera yukleme',
    description: 'Mobil cihazlarda fotograf cek/yukle inputunu etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.requirements',
    moduleKey: 'documents',
    label: 'Belge gereksinimleri',
    description: 'Operation bazli required/optional belge slotlarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.signedUrlDownload',
    moduleKey: 'documents',
    label: 'Signed URL ile indirme',
    description: 'Belge indirme/onizleme icin kisa omurlu signed URL uretir.',
    defaultEnabled: true,
  },
  {
    key: 'documents.expiryAlerts',
    moduleKey: 'documents',
    label: 'Belge sure uyarilari',
    description: 'Suresi dolan ve 30 gun icinde dolacak belgeleri Is Merkezi uyarilarina tasir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.enabled',
    moduleKey: 'notifications',
    label: 'Bildirimler',
    description: 'Kullanici bildirimlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.inApp',
    moduleKey: 'notifications',
    label: 'Uygulama ici bildirim',
    description: 'Header bildirim paneli ve okunmamis sayaci etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.email',
    moduleKey: 'notifications',
    label: 'E-posta bildirimi',
    description: 'Bildirimlerden e-posta kuyrugu olusturulmasini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.reminders',
    moduleKey: 'notifications',
    label: 'Hatirlatmalar',
    description: 'Zamanlanmis reminder batch islerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.digest',
    moduleKey: 'notifications',
    label: 'Bildirim ozeti',
    description: 'Gunluk/haftalik digest tercihlerini etkinlestirir.',
    defaultEnabled: false,
  },
  {
    key: 'notifications.systemWarnings',
    moduleKey: 'notifications',
    label: 'Sistem uyarilari',
    description: 'Sistem ve guvenlik uyarilarini ilgili yetkililere iletir.',
    defaultEnabled: true,
  },
  {
    key: 'notifications.emailTemplates',
    moduleKey: 'notifications',
    label: 'E-posta sablonlari',
    description: 'Baslangic e-posta sablonlarini ve degisken render altyapisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'process.approvals',
    moduleKey: 'process',
    label: 'Surec onaylari',
    description: 'Surec icinde onay bekleyen adimlari etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'process.tasks',
    moduleKey: 'process',
    label: 'Surec gorevleri',
    description: 'Kullanicilara atanabilen surec gorevlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.leaveManagement',
    moduleKey: 'hr',
    label: 'Izin yonetimi',
    description: 'Izin turleri, izin talepleri, onay ve bakiye takibini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.attendance',
    moduleKey: 'hr',
    label: 'Devam-devamsizlik',
    description: 'Manuel devam kayitlari, devamsizlik ve fazla mesai hazirligini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.workSchedules',
    moduleKey: 'hr',
    label: 'Calisma planlari',
    description: 'Haftalik calisma plani ve calisana plan atamalarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.timesheets',
    moduleKey: 'hr',
    label: 'Puantaj',
    description: 'Puantaj donemi, hesaplama, onay ve kilit akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.payrollPreparation',
    moduleKey: 'hr',
    label: 'Bordro hazirligi',
    description: 'Puantajdan bordro hazirlik verisi uretimini etkinlestirir; tutar hesaplamaz.',
    defaultEnabled: true,
  },
  {
    key: 'hr.leaveApprovals',
    moduleKey: 'hr',
    label: 'Izin onaylari',
    description: 'Izin onay bekleyen islerini Action Center ve bildirimlere tasir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.overtime',
    moduleKey: 'hr',
    label: 'Fazla mesai',
    description: 'Devam kayitlarinda fazla mesai saatlerini hesaplar ve puantaja tasir.',
    defaultEnabled: true,
  },
  {
    key: 'hr.attendanceImport',
    moduleKey: 'hr',
    label: 'Devam import',
    description: 'Manuel import hazirligi icin toplu devam kaydi endpointini etkinlestirir.',
    defaultEnabled: false,
  },
  {
    key: 'crm.leads',
    moduleKey: 'crm',
    label: 'Lead yonetimi',
    description: 'Lead kaydi, kaynak, durum ve duplicate uyarilarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.opportunities',
    moduleKey: 'crm',
    label: 'Firsat yonetimi',
    description: 'Satis firsatlari, tutar, olasilik ve kapanis takibini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.pipeline',
    moduleKey: 'crm',
    label: 'Pipeline',
    description: 'Pipeline ve asama bazli firsat takibini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.followups',
    moduleKey: 'crm',
    label: 'Takip otomasyonu',
    description: 'Next follow-up tarihi gelen lead/firsatlari Action Center ve gorevlere tasir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.proposals',
    moduleKey: 'crm',
    label: 'Teklif baglantisi',
    description: 'Firsat uzerinde teklif belge durumu ve hazirlik baglantilarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.leadConversion',
    moduleKey: 'crm',
    label: 'Lead donusumu',
    description: 'Lead kaydini paydas, musteri ve firsata donusturme akislarini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.opportunityKanban',
    moduleKey: 'crm',
    label: 'Firsat kanban',
    description: 'Pipeline kolonlari ile firsat board gorunumunu etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'crm.crmNotifications',
    moduleKey: 'crm',
    label: 'CRM bildirimleri',
    description: 'Lead atama, takip zamani ve firsat asamasi bildirimlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.maintenancePlanning',
    moduleKey: 'after_sales',
    label: 'Bakim planlama',
    description: 'Periyodik bakim planlari ve bakimi gelen kurulu urunleri etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.fieldService',
    moduleKey: 'after_sales',
    label: 'Saha servis',
    description: 'Teknisyen atama, saha gorevi ve servis durum akisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.mobileServiceFlow',
    moduleKey: 'after_sales',
    label: 'Mobil servis akisi',
    description: 'Tek sutun teknisyen servis akisi, checklist, fotograf ve sonuc girisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.serviceChecklist',
    moduleKey: 'after_sales',
    label: 'Servis checklist',
    description: 'Urun/servis turu bazli checklist sablonlari ve servis sonuc checklistlerini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.partsUsed',
    moduleKey: 'after_sales',
    label: 'Kullanilan parcalar',
    description: 'Serviste kullanilan parca ve malzeme hazirlik bilgisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.customerSignature',
    moduleKey: 'after_sales',
    label: 'Musteri imzasi placeholder',
    description: 'Servis raporunda musteri imzasi alanini future entegrasyon icin gosterir.',
    defaultEnabled: false,
  },
  {
    key: 'afterSales.serviceReport',
    moduleKey: 'after_sales',
    label: 'Servis raporu',
    description: 'Servis raporu JSON/HTML onizleme akisini etkinlestirir.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.warrantyCheck',
    moduleKey: 'after_sales',
    label: 'Garanti kontrolu',
    description: 'Kurulu urun garanti kapsam kontrolunu servis akisina baglar.',
    defaultEnabled: true,
  },
  {
    key: 'afterSales.technicianAssignment',
    moduleKey: 'after_sales',
    label: 'Teknisyen atama',
    description: 'Saha servis gorevleri icin teknisyen/user/calisan atamasini etkinlestirir.',
    defaultEnabled: true,
  },
] satisfies FeatureFlag[]

const featureFlagByKey = new Map(featureFlags.map(flag => [flag.key, flag]))

export function listFeatureFlags() {
  return [...featureFlags]
}

export function listFeatureFlagsForModule(moduleKey: string) {
  return featureFlags.filter(flag => flag.moduleKey === moduleKey)
}

export function getFeatureFlag(key: string) {
  return featureFlagByKey.get(key) || null
}

export function getDefaultFeatureFlagMap() {
  return Object.fromEntries(featureFlags.map(flag => [flag.key, flag.defaultEnabled])) as Record<string, boolean>
}

export function isFeatureFlagEnabled(key: string, runtimeFlags?: Record<string, boolean>) {
  if (runtimeFlags && Object.prototype.hasOwnProperty.call(runtimeFlags, key)) {
    return Boolean(runtimeFlags[key])
  }
  return getFeatureFlag(key)?.defaultEnabled ?? true
}
