import { registerListProjection } from '@/lib/read-models/readModelRegistry'

export const companyListProjection = registerListProjection({
  key: 'companies.list',
  moduleKey: 'sirket',
  entityType: 'company',
  sourceName: 'v_company_list_projection',
  sourceType: 'view',
  version: '2026-05-25.1',
  defaultColumns: [
    'id',
    'organization_id',
    'short_name',
    'trade_name',
    'tax_number',
    'tax_office',
    'company_type',
    'city',
    'district',
    'phone',
    'email',
    'logo_url',
    'is_deleted',
    'record_status',
    'company_status',
    'committed_capital_amount',
    'paid_capital_amount',
    'default_currency',
    'tenant_id',
    'updated_at',
    'created_at',
  ],
  searchableFields: ['short_name', 'trade_name', 'tax_number'],
  sortableFields: {
    short_name: 'short_name',
    trade_name: 'trade_name',
    tax_number: 'tax_number',
    tax_office: 'tax_office',
    company_type: 'company_type',
    is_deleted: 'is_deleted',
    lifecycle_status: 'record_status',
    record_status: 'record_status',
    company_status: 'company_status',
    updated_at: 'updated_at',
    created_at: 'created_at',
  },
  defaultSort: 'short_name',
  tenantScopeTable: 'companies',
})

export const companyPartnerListProjection = registerListProjection({
  key: 'company_partners.list',
  moduleKey: 'sirket',
  entityType: 'company_partner',
  sourceName: 'v_company_partner_list_projection',
  sourceType: 'view',
  version: '2026-05-25.1',
  defaultColumns: [
    'id',
    'company_id',
    'company_name',
    'person_id',
    'organization_id',
    'owner_kind',
    'partner_type',
    'display_name',
    'partner_name',
    'identity_number',
    'identity_tax_number',
    'share_ratio',
    'voting_ratio',
    'profit_ratio',
    'current_share_ratio',
    'current_voting_ratio',
    'current_profit_ratio',
    'current_capital_amount',
    'current_share_units',
    'representative_authority_count',
    'start_date',
    'end_date',
    'status',
    'record_status',
    'is_deleted',
    'source_type',
    'source_id',
    'tenant_id',
    'created_at',
    'updated_at',
  ],
  searchableFields: ['display_name', 'partner_name', 'identity_number', 'identity_tax_number', 'company_name'],
  sortableFields: {
    display_name: 'display_name',
    partner_name: 'partner_name',
    company_name: 'company_name',
    identity_number: 'identity_number',
    share_ratio: 'current_share_ratio',
    current_share_ratio: 'current_share_ratio',
    voting_ratio: 'current_voting_ratio',
    profit_ratio: 'current_profit_ratio',
    status: 'status',
    record_status: 'record_status',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: 'created_at',
  tenantScopeTable: 'company_partners',
  companyScopeField: 'company_id',
  statusField: 'record_status',
  passiveValue: 'passive',
})
